/* BANG CHU DE DUNG CHUNG — sinh boi tools/build_topics.py, DUNG SUA TAY.
   Gop 794 tu co vi du + 2649 tu Oxford thanh 26 chu de chung.
   index.html doc file nay roi xep lai lop nhom khi chay; 3 file du lieu goc
   (data-vocab.js / -plus / -oxford) giu nguyen, van la noi chua t/ipa/p/vn/ex. */
window.TOPIC_DEF=[
 {id:"ox-work",title:"Công việc, công ty & nghề nghiệp",icon:"i-users",c:"noi"},
 {id:"ox-biz",title:"Kinh doanh, bán hàng & đàm phán",icon:"i-scale",c:"damphan"},
 {id:"ox-money",title:"Tiền bạc, giá cả & ngân hàng",icon:"i-table",c:"damphan"},
 {id:"ox-food",title:"Ăn uống & ngành F&B",icon:"i-star",c:"noi"},
 {id:"ox-people",title:"Con người, gia đình & quan hệ",icon:"i-users",c:"noi"},
 {id:"ox-body",title:"Cơ thể, sức khoẻ & tai nạn",icon:"i-alert",c:"nghe"},
 {id:"ox-feel",title:"Cảm xúc & thái độ",icon:"i-flame",c:"noi"},
 {id:"ox-mind",title:"Suy nghĩ, ý kiến & khái niệm",icon:"i-quote",c:"doc"},
 {id:"ox-home",title:"Nhà cửa & đồ đạc",icon:"i-layers",c:"nghe"},
 {id:"ox-clothes",title:"Quần áo & ngoại hình",icon:"i-star",c:"nghe"},
 {id:"ox-travel",title:"Đi lại, du lịch & phương tiện",icon:"i-flag",c:"nghe"},
 {id:"ox-place",title:"Địa điểm, thành phố & phương hướng",icon:"i-flag",c:"nghe"},
 {id:"ox-nature",title:"Thiên nhiên, động vật & thời tiết",icon:"i-sun",c:"nghe"},
 {id:"ox-time",title:"Thời gian & lịch",icon:"i-cal",c:"doc"},
 {id:"ox-number",title:"Số lượng, đo lường & kích thước",icon:"i-table",c:"doc"},
 {id:"ox-edu",title:"Học hành, ngôn ngữ & khoa học",icon:"i-book",c:"doc"},
 {id:"ox-tech",title:"Công nghệ, máy móc & vật liệu",icon:"i-file",c:"doc"},
 {id:"ox-media",title:"Truyền thông, âm thanh & giải trí",icon:"i-headphones",c:"nghe"},
 {id:"ox-sport",title:"Thể thao & sở thích",icon:"i-trophy",c:"nghe"},
 {id:"ox-law",title:"Luật pháp, tội phạm & chính trị",icon:"i-scale",c:"damphan"},
 {id:"ox-society",title:"Xã hội, tôn giáo & lịch sử",icon:"i-flag",c:"doc"},
 {id:"ox-action",title:"Động từ hành động & chuyển động",icon:"i-play",c:"noi"},
 {id:"ox-change",title:"Động từ thay đổi, tăng giảm & kết quả",icon:"i-arrow",c:"noi"},
 {id:"ox-adj",title:"Tính từ mô tả & đánh giá",icon:"i-pen",c:"viet"},
 {id:"ox-adv",title:"Trạng từ & mức độ",icon:"i-pen",c:"viet"},
 {id:"ox-gram",title:"Từ nối, giới từ & từ ngữ pháp",icon:"i-file",c:"viet"},
];
window.TOPIC_OF={
 "a":"gram","abandon":"action","abandoned":"adj","ability":"mind","able":"adj","about":"gram",
 "above":"place","abroad":"travel","absence":"mind","absent":"work","absolute":"adj","absolutely":"adv",
 "absorb":"action","abuse":"law","academic":"edu","accent":"edu","accept":"mind","acceptable":"adj",
 "access":"tech","accident":"body","accidental":"adj","accidentally":"adv","accommodation":"travel","accompany":"action",
 "according to":"gram","account":"tech","accurate":"adj","accurately":"adv","accuse":"law","achieve":"change",
 "achievement":"work","acid":"tech","acknowledge":"mind","acquire":"change","across":"place","act":"action",
 "action":"action","active":"adj","actively":"adv","activity":"action","actor":"media","actress":"media",
 "actual":"adj","actually":"adv","adapt":"change","add":"number","addition":"number","additional":"adj",
 "address":"place","adequate":"adj","adequately":"adv","adjust":"change","admiration":"feel","admire":"feel",
 "admit":"mind","adopt":"change","adult":"people","advance":"change","advanced":"adj","advantage":"mind",
 "adventure":"travel","advertise":"biz","advertisement":"biz","advertising":"biz","advice":"mind","advise":"mind",
 "affair":"society","affect":"change","affection":"feel","afford":"money","afraid":"feel","after":"gram",
 "afternoon":"time","afterwards":"time","again":"adv","against":"gram","age":"people","aged":"adj",
 "agency":"biz","agenda":"work","agent":"biz","aggressive":"feel","ago":"time","agree":"mind",
 "agreement":"biz","ahead":"place","aid":"society","aim":"work","air":"nature","air conditioner":"home",
 "aircraft":"travel","airport":"travel","alarm":"tech","alarmed":"feel","alarming":"adj","alcohol":"food",
 "alcoholic":"food","alive":"body","all":"gram","all right":"gram","allied":"society","allow":"mind",
 "ally":"society","almost":"adv","alone":"adj","along":"place","alongside":"gram","aloud":"adv",
 "alphabet":"edu","alphabetical":"edu","alphabetically":"edu","already":"adv","also":"adv","alter":"change",
 "alternative":"mind","alternatively":"adv","although":"gram","altogether":"adv","always":"adv","amaze":"feel",
 "amazed":"feel","amazing":"adj","ambition":"work","ambitious":"feel","ambulance":"body","among":"place",
 "amount":"number","amuse":"feel","amused":"feel","amusing":"adj","analysis":"mind","ancient":"time",
 "and":"gram","anger":"feel","angle":"number","angrily":"adv","angry":"feel","animal":"nature",
 "ankle":"body","anniversary":"time","announce":"mind","annoy":"feel","annoyed":"feel","annoying":"adj",
 "annual":"time","annually":"adv","another":"gram","answer":"mind","anti":"gram","anticipate":"mind",
 "anxiety":"feel","anxious":"feel","anxiously":"adv","anyone":"gram","anything":"gram","anyway":"adv",
 "anywhere":"gram","apart":"adv","apart from":"gram","apartment":"home","apologize":"mind","app":"tech",
 "apparent":"adj","apparently":"adv","appeal":"mind","appear":"change","appearance":"clothes","apple":"food",
 "application":"work","apply":"work","appoint":"work","appointment":"work","appreciate":"feel","approach":"action",
 "appropriate":"adj","approval":"mind","approve":"mind","approve of":"mind","approving":"adj","approximate":"number",
 "approximately":"number","April":"time","area":"place","argue":"mind","argument":"mind","arise":"change",
 "arm":"body","armed":"law","arms":"law","army":"law","around":"place","arrange":"work",
 "arrangement":"work","arrest":"law","arrival":"travel","arrive":"travel","arrow":"tech","art":"media",
 "article":"media","artificial":"adj","artificially":"adv","artist":"media","artistic":"adj","as":"gram",
 "as well":"gram","ashamed":"feel","aside":"adv","ask":"mind","asleep":"body","aspect":"mind",
 "assist":"work","assistance":"work","assistant":"work","associate":"mind","association":"society","assume":"mind",
 "assure":"mind","at least":"gram","atmosphere":"nature","atom":"tech","attach":"work","attached":"adj",
 "attachment":"work","attack":"law","attempt":"action","attempted":"adj","attend":"work","attention":"mind",
 "attitude":"feel","attorney":"law","attract":"feel","attraction":"feel","attractive":"adj","audience":"media",
 "August":"time","aunt":"people","author":"media","authority":"law","automatic":"tech","automatically":"adv",
 "autumn":"time","available":"work","average":"number","avoid":"action","awake":"body","award":"work",
 "aware":"mind","away":"adv","awful":"adj","awfully":"adv","awkward":"adj","awkwardly":"adv",
 "back":"body","background":"mind","backup":"tech","backward":"place","backwards":"place","bacteria":"body",
 "bad":"adj","bad-tempered":"feel","badly":"adv","bag":"clothes","baggage":"travel","bake":"food",
 "balance":"number","ball":"sport","ban":"law","band":"media","bandage":"body","bank":"money",
 "bar":"food","bargain":"biz","barrier":"place","base":"place","basic":"adj","basically":"adv",
 "basis":"mind","bath":"home","bathroom":"home","battery":"tech","battle":"law","bay":"nature",
 "be":"gram","beach":"nature","beak":"nature","bear":"feel","beard":"body","beat":"action",
 "beautiful":"adj","beautifully":"adv","beauty":"clothes","because":"gram","become":"change","bed":"home",
 "bedroom":"home","beef":"food","beer":"food","before":"gram","begin":"change","beginning":"time",
 "behalf":"gram","behave":"people","behind":"place","belief":"mind","believe":"mind","bell":"tech",
 "belong":"mind","below":"place","belt":"clothes","bend":"action","beneath":"gram","benefit":"biz",
 "bent":"adj","beside":"place","besides":"gram","bet":"sport","betting":"sport","between":"place",
 "beyond":"gram","bicycle":"travel","bid":"biz","big":"adj","bill":"food","bin":"home",
 "biology":"edu","bird":"nature","birth":"people","birthday":"time","biscuit":"food","bit":"number",
 "bite":"action","bitter":"food","bitterly":"adv","black":"adj","blade":"tech","blame":"mind",
 "blank":"adj","blankly":"adv","blind":"body","block":"place","blonde":"clothes","blood":"body",
 "blow":"action","blue":"adj","board":"work","boat":"travel","body":"body","boil":"food",
 "bomb":"law","bone":"body","book":"biz","booking":"food","boot":"clothes","border":"place",
 "bore":"feel","bored":"feel","boring":"adj","born":"people","borrow":"money","boss":"work",
 "both":"gram","bother":"feel","bottle":"food","bottom":"place","bound":"adj","bowl":"home",
 "box":"home","boy":"people","boyfriend":"people","brain":"body","branch":"biz","brand":"biz",
 "brave":"feel","bread":"food","break":"action","breakfast":"food","breast":"body","breath":"body",
 "breathe":"body","breathing":"body","breed":"nature","brick":"tech","bridge":"place","brief":"adj",
 "briefly":"adv","bright":"adj","brightly":"adv","brilliant":"adj","bring":"action","broad":"adj",
 "broadcast":"media","broadly":"adv","broken":"adj","brother":"people","brown":"adj","brush":"home",
 "bubble":"nature","budget":"money","bug":"tech","build":"action","building":"place","bullet":"law",
 "bunch":"number","burn":"action","burnt":"adj","burst":"action","bury":"action","bus":"travel",
 "bush":"nature","business":"biz","busy":"feel","but":"gram","butter":"food","button":"tech",
 "buy":"biz","buyer":"biz","by":"gram","by the way":"gram","bye":"gram","cabinet":"home",
 "cable":"tech","café":"food","cake":"food","calculate":"number","calculation":"number","call":"work",
 "calm":"feel","calmly":"adv","camera":"tech","camp":"travel","campaign":"biz","camping":"travel",
 "cancel":"biz","cancer":"body","candidate":"work","candy":"food","cap":"clothes","capable of":"adj",
 "capacity":"number","capital":"money","cappuccino":"food","captain":"sport","capture":"action","car":"travel",
 "card":"money","cardboard":"tech","care":"feel","career":"work","careful":"feel","carefully":"adv",
 "careless":"feel","carelessly":"adv","carpet":"home","carrot":"food","carry":"action","cart":"biz",
 "case":"mind","cash":"money","cashier":"food","cast":"media","castle":"place","cat":"nature",
 "catch":"action","category":"mind","cause":"mind","CD":"tech","cease":"change","ceiling":"home",
 "celebrate":"society","celebration":"society","cell":"body","cent":"money","centimetre":"number","central":"place",
 "centre":"place","century":"time","ceremony":"society","certain":"adj","certainly":"adv","certificate":"edu",
 "chain":"biz","chair":"home","challenge":"work","chamber":"place","chance":"mind","change":"change",
 "channel":"media","chapter":"edu","character":"people","characteristic":"mind","charge":"money","charger":"tech",
 "charity":"society","chart":"work","chase":"action","chat":"mind","cheap":"adj","cheaply":"adv",
 "cheat":"law","check":"work","cheek":"body","cheerful":"feel","cheerfully":"adv","cheese":"food",
 "chef":"food","chemical":"tech","chemist":"edu","chemistry":"edu","cheque":"money","chest":"body",
 "chew":"food","chicken":"food","chief":"work","child":"people","chin":"body","chip":"food",
 "chocolate":"food","choice":"mind","choose":"mind","chop":"food","church":"society","cigarette":"body",
 "cinema":"media","circle":"number","circumstance":"mind","citizen":"society","city":"place","civil":"society",
 "claim":"mind","clap":"action","class":"edu","classic":"adj","classroom":"edu","clean":"adj",
 "clear":"adj","clearly":"adv","clerk":"work","clever":"adj","click":"tech","client":"biz",
 "climate":"nature","climb":"action","climbing":"sport","clock":"time","close":"biz","closed":"adj",
 "closely":"adv","closet":"home","cloth":"clothes","clothes":"clothes","clothing":"clothes","cloud":"tech",
 "club":"sport","coach":"sport","coal":"tech","coast":"nature","coat":"clothes","code":"tech",
 "coffee":"food","coin":"money","cold":"adj","coldly":"adv","collapse":"change","colleague":"work",
 "collect":"action","collection":"mind","college":"edu","color":"adj","coloured":"adj","column":"media",
 "combination":"mind","combine":"change","come":"action","comedy":"media","comfort":"feel","comfortable":"feel",
 "comfortably":"adv","command":"work","comment":"mind","commercial":"biz","commission":"money","commit":"action",
 "commitment":"biz","committee":"work","common":"adj","commonly":"adv","communicate":"mind","communication":"mind",
 "community":"society","company":"biz","compare":"mind","comparison":"mind","compete":"biz","competition":"biz",
 "competitive":"adj","competitor":"biz","complain":"biz","complaint":"biz","complete":"adj","completely":"adv",
 "complex":"adj","complicate":"change","complicated":"adj","computer":"tech","concentrate":"mind","concentration":"mind",
 "concept":"mind","concern":"feel","concerned":"adj","concerning":"gram","concert":"media","conclude":"mind",
 "conclusion":"mind","concrete":"tech","condition":"biz","conduct":"action","conference":"work","confidence":"feel",
 "confident":"feel","confidently":"adv","confine":"action","confined":"adj","confirm":"work","conflict":"society",
 "confront":"action","confuse":"mind","confused":"feel","confusing":"adj","confusion":"mind","congratulations":"society",
 "congress":"law","connect":"work","connection":"mind","conscious":"mind","consequence":"mind","conservative":"law",
 "consider":"mind","considerable":"adj","considerably":"adv","consideration":"mind","consist of":"mind","constant":"adj",
 "constantly":"adv","construct":"tech","construction":"tech","consult":"work","consumer":"biz","contact":"work",
 "contain":"mind","container":"home","contemporary":"time","content":"mind","contest":"sport","context":"mind",
 "continent":"place","continue":"change","continuous":"adj","continuously":"adv","contract":"biz","contrast":"mind",
 "contrasting":"adj","contribute":"society","contribution":"society","control":"work","controlled":"adj","convenient":"adj",
 "convention":"work","conventional":"adj","conversation":"mind","convert":"change","convince":"mind","cook":"food",
 "cooker":"home","cookie":"food","cooking":"food","cool":"adj","cooperate":"work","cope":"feel",
 "copy":"action","core":"mind","corner":"place","correct":"adj","correctly":"adv","cost":"money",
 "cottage":"home","cotton":"clothes","cough":"body","coughing":"body","council":"law","count":"number",
 "counter":"food","country":"place","countryside":"nature","county":"place","couple":"people","courage":"feel",
 "course":"edu","court":"law","cousin":"people","cover":"action","covered":"adj","covering":"tech",
 "cow":"nature","crack":"tech","cracked":"adj","craft":"media","crash":"travel","crazy":"adj",
 "cream":"food","create":"change","creative":"feel","creature":"nature","credit":"money","credit card":"money",
 "crime":"law","criminal":"law","crisis":"society","crisp":"adj","criterion":"mind","critical":"adj",
 "criticism":"mind","criticize":"mind","crop":"nature","cross":"action","crowd":"people","crowded":"adj",
 "crown":"society","crucial":"adj","cruel":"feel","crush":"action","cry":"feel","cultural":"adj",
 "culture":"society","cup":"home","cupboard":"home","curb":"place","cure":"body","curious":"feel",
 "curiously":"adv","curl":"clothes","curly":"adj","current":"adj","currently":"adv","curtain":"home",
 "curve":"number","curved":"adj","custom":"society","customer":"biz","customs":"travel","cut":"action",
 "cycle":"number","cycling":"sport","dad":"people","daily":"time","damage":"change","damp":"adj",
 "dance":"media","dancer":"media","dancing":"media","danger":"body","dangerous":"body","dare":"feel",
 "dark":"adj","dashboard":"tech","data":"tech","database":"tech","date":"time","daughter":"people",
 "day":"time","dead":"body","deadline":"work","deaf":"body","deal":"biz","dear":"work",
 "death":"body","debate":"mind","debt":"money","decade":"time","decay":"change","December":"time",
 "decide":"mind","decision":"mind","declare":"mind","decline":"change","decorate":"home","decoration":"home",
 "decorative":"adj","decrease":"change","deep":"adj","deeply":"adv","defeat":"sport","defence":"law",
 "defend":"law","define":"mind","definite":"adj","definitely":"adv","definition":"mind","degree":"edu",
 "delay":"travel","deliberate":"adj","deliberately":"adv","delicate":"adj","delicious":"food","delight":"feel",
 "delighted":"feel","deliver":"biz","delivery":"food","demand":"biz","demonstrate":"mind","dentist":"body",
 "deny":"mind","depart":"travel","department":"work","departure":"travel","depend on":"mind","deploy":"tech",
 "deposit":"money","depress":"feel","depressed":"feel","depressing":"adj","depth":"number","derive":"mind",
 "describe":"mind","description":"mind","desert":"nature","deserted":"adj","deserve":"mind","design":"work",
 "desire":"feel","desk":"home","desperate":"feel","desperately":"adv","despite":"gram","dessert":"food",
 "destroy":"change","destruction":"change","detail":"mind","detailed":"adj","determination":"feel","determine":"mind",
 "determined":"feel","develop":"change","development":"change","device":"tech","devote":"feel","devoted":"adj",
 "diagram":"edu","diamond":"clothes","diary":"edu","dictionary":"edu","die":"body","diet":"food",
 "difference":"mind","different":"adj","differently":"adv","difficult":"adj","difficulty":"mind","dig":"action",
 "dinner":"food","direct":"action","direction":"place","directly":"adv","director":"work","dirt":"home",
 "dirty":"adj","disabled":"body","disadvantage":"mind","disagree":"mind","disagreement":"mind","disappear":"change",
 "disappoint":"feel","disappointed":"feel","disappointing":"adj","disappointment":"feel","disapproval":"mind","disapprove of":"mind",
 "disapproving":"adj","disaster":"society","discipline":"edu","discount":"money","discover":"mind","discovery":"mind",
 "discuss":"mind","discussion":"mind","disease":"body","disgust":"feel","disgusted":"feel","disgusting":"adj",
 "dish":"food","dishonest":"feel","dishonestly":"adv","disk":"tech","dislike":"feel","dismiss":"work",
 "display":"biz","dissolve":"change","distance":"number","distinguish":"mind","distribute":"biz","distribution":"biz",
 "district":"place","disturb":"action","disturbing":"adj","divide":"number","division":"number","divorce":"people",
 "divorced":"adj","do":"action","doctor":"body","document":"work","dog":"nature","dollar":"money",
 "domestic":"adj","dominate":"change","door":"home","dot":"number","double":"number","doubt":"mind",
 "down":"place","download":"tech","downstairs":"home","downward":"place","downwards":"place","dozen":"number",
 "draft":"work","drag":"action","drama":"media","dramatic":"adj","dramatically":"adv","draw":"media",
 "drawer":"home","drawing":"media","dream":"mind","dress":"clothes","dressed":"adj","drink":"food",
 "drive":"travel","driver":"travel","driving":"travel","drop":"action","drug":"body","drugstore":"body",
 "drum":"media","drunk":"adj","dry":"adj","due":"adj","dull":"adj","dump":"action",
 "during":"gram","dust":"home","duty":"work","DVD":"tech","dying":"adj","each":"gram",
 "each other":"gram","ear":"body","early":"time","earn":"money","earth":"nature","ease":"mind",
 "easily":"adv","east":"place","eastern":"place","easy":"adj","eat":"food","economic":"money",
 "economy":"money","edge":"place","edition":"media","editor":"media","educate":"edu","educated":"adj",
 "education":"edu","effect":"mind","effective":"adj","effectively":"adv","efficient":"adj","efficiently":"adv",
 "effort":"work","egg":"food","either":"gram","elbow":"body","elderly":"people","elect":"law",
 "election":"law","electric":"tech","electrical":"tech","electricity":"tech","electronic":"tech","elegant":"adj",
 "element":"mind","elevator":"home","else":"gram","elsewhere":"gram","email":"work","embarrass":"feel",
 "embarrassed":"feel","embarrassing":"adj","embarrassment":"feel","emerge":"change","emergency":"body","emotion":"feel",
 "emotional":"feel","emotionally":"adv","emphasis":"mind","emphasize":"mind","empire":"society","employ":"work",
 "employee":"work","employer":"work","employment":"work","empty":"adj","enable":"change","encounter":"action",
 "encourage":"feel","encouragement":"feel","end":"time","ending":"time","enemy":"society","energy":"tech",
 "engage":"work","engaged":"people","engine":"tech","engineer":"work","engineering":"tech","enjoy":"feel",
 "enjoyable":"adj","enjoyment":"feel","enormous":"adj","enough":"adv","enquiry":"mind","ensure":"mind",
 "enter":"action","entertain":"media","entertainer":"media","entertaining":"adj","entertainment":"media","enthusiasm":"feel",
 "enthusiastic":"feel","entire":"adj","entirely":"adv","entitle":"mind","entrance":"place","entry":"place",
 "envelope":"work","environment":"nature","environmental":"adj","equal":"number","equally":"adv","equipment":"tech",
 "equivalent":"number","error":"tech","escape":"action","especially":"adv","espresso":"food","essay":"edu",
 "essential":"adj","essentially":"adv","establish":"biz","estate":"place","estimate":"number","euro":"money",
 "even":"adv","evening":"time","event":"society","eventually":"adv","ever":"adv","every":"gram",
 "everything":"gram","everywhere":"gram","evidence":"law","evil":"feel","ex-":"gram","exact":"adj",
 "exactly":"adv","exaggerate":"mind","exaggerated":"adj","exam":"edu","examination":"edu","examine":"mind",
 "example":"mind","excellent":"adj","except":"gram","exception":"mind","exchange":"biz","excite":"feel",
 "excited":"feel","excitement":"feel","exciting":"adj","exclude":"mind","excluding":"gram","excuse":"mind",
 "executive":"work","exercise":"body","exhibit":"media","exhibition":"media","exist":"mind","existence":"mind",
 "exit":"place","expand":"change","expect":"mind","expectation":"mind","expected":"adj","expense":"money",
 "expensive":"adj","experience":"work","experienced":"adj","experiment":"edu","expert":"work","explain":"mind",
 "explanation":"mind","explode":"change","explore":"travel","explosion":"change","export":"biz","expose":"action",
 "express":"mind","expression":"mind","extend":"change","extension":"work","extensive":"adj","extent":"number",
 "extra":"adj","extraordinary":"adj","extreme":"adj","extremely":"adv","eye":"body","face":"body",
 "facility":"place","fact":"mind","factor":"mind","factory":"work","fail":"change","failure":"change",
 "faint":"adj","faintly":"adv","fair":"feel","fairly":"adv","faith":"society","faithful":"feel",
 "faithfully":"adv","fall":"action","FALSE":"adj","fame":"media","familiar":"adj","family":"people",
 "famous":"adj","fan":"home","fancy":"feel","far":"place","farm":"nature","farmer":"work",
 "farming":"nature","fashion":"clothes","fashionable":"adj","fast":"adj","fasten":"action","fat":"adj",
 "father":"people","faucet":"home","fault":"mind","favour":"feel","favourite":"adj","fear":"feel",
 "feather":"nature","feature":"tech","February":"time","federal":"law","fee":"money","feed":"food",
 "feel":"feel","feeling":"feel","fellow":"people","female":"people","fence":"home","festival":"society",
 "fetch":"action","fever":"body","few":"number","field":"nature","fight":"law","fighting":"law",
 "figure":"number","file":"work","fill":"action","film":"media","final":"adj","finally":"adv",
 "finance":"money","financial":"adj","find":"action","fine":"adj","finely":"adv","finger":"body",
 "finish":"change","finished":"adj","fire":"body","firm":"biz","firmly":"adv","first":"number",
 "fish":"food","fishing":"sport","fit":"body","fix":"tech","fixed":"adj","flag":"society",
 "flame":"nature","flash":"tech","flat":"home","flavour":"food","flesh":"body","flexible":"feel",
 "flight":"travel","float":"action","flood":"nature","floor":"home","flour":"food","flow":"action",
 "flower":"nature","flu":"body","fly":"action","flying":"travel","focus":"mind","fold":"action",
 "folder":"work","folding":"adj","follow":"action","follow-up":"work","following":"adj","food":"food",
 "foot":"body","football":"sport","for":"gram","for example":"gram","force":"change","forecast":"nature",
 "foreign":"travel","forest":"nature","forever":"time","forget":"mind","forgive":"feel","fork":"home",
 "form":"work","formal":"adj","formally":"adv","former":"time","formerly":"adv","formula":"edu",
 "fortune":"money","forward":"work","found":"biz","foundation":"biz","frame":"tech","free":"adj",
 "freedom":"society","freely":"adv","freeze":"food","frequent":"adj","frequently":"adv","fresh":"food",
 "freshly":"adv","Friday":"time","fridge":"home","friend":"people","friendly":"feel","friendship":"people",
 "frighten":"feel","frightened":"feel","frightening":"adj","from":"gram","front":"place","frozen":"adj",
 "fruit":"food","fry":"food","fuel":"tech","full":"adj","fully":"adv","fun":"feel",
 "function":"tech","fund":"money","fundamental":"adj","funeral":"society","funny":"feel","fur":"nature",
 "furniture":"home","further":"adj","future":"time","gain":"change","gallon":"number","gamble":"sport",
 "gambling":"sport","game":"sport","gap":"place","garage":"home","garbage":"home","garden":"home",
 "gas":"tech","gasoline":"travel","gate":"home","gather":"action","gear":"travel","general":"adj",
 "generally":"adv","generate":"change","generation":"people","generous":"feel","generously":"adv","gentle":"feel",
 "gentleman":"people","gently":"adv","genuine":"adj","genuinely":"adv","geography":"edu","get":"action",
 "get back to you":"work","giant":"adj","gift":"society","girl":"people","girlfriend":"people","give":"action",
 "glad":"feel","glass":"home","glasses":"clothes","global":"adj","glove":"clothes","glue":"tech",
 "go":"action","go ahead":"mind","goal":"work","god":"society","gold":"money","good":"adj",
 "goodbye":"mind","goods":"biz","govern":"law","government":"law","governor":"law","grab":"action",
 "grade":"edu","gradual":"adj","gradually":"adv","grain":"food","gram":"number","grammar":"edu",
 "grand":"adj","grandchild":"people","granddaughter":"people","grandfather":"people","grandmother":"people","grandparent":"people",
 "grandparents":"people","grandson":"people","grant":"money","grass":"nature","grateful":"feel","grave":"society",
 "gray":"adj","great":"adj","greatly":"adv","green":"adj","grey":"adj","groceries":"food",
 "grocery":"food","ground":"place","group":"people","grow":"change","growth":"change","guarantee":"biz",
 "guard":"law","guess":"mind","guest":"food","guide":"travel","guilty":"law","gun":"law",
 "guy":"people","habit":"people","hair":"body","hairdresser":"clothes","half":"number","hall":"home",
 "hammer":"tech","hand":"body","handle":"work","hang":"action","hang up":"work","happen":"change",
 "happily":"adv","happiness":"feel","happy":"feel","hard":"adj","hard-working":"feel","hardly":"adv",
 "hardware":"tech","harm":"body","harmful":"adj","harmless":"adj","hat":"clothes","hate":"feel",
 "hatred":"feel","have":"action","he":"gram","head":"body","headache":"body","heal":"body",
 "health":"body","healthy":"body","hear":"action","hearing":"body","heart":"body","heat":"nature",
 "heating":"home","heaven":"society","heavily":"adv","heavy":"adj","heel":"body","height":"number",
 "hell":"society","hello":"mind","help":"action","helpful":"feel","hence":"gram","her":"gram",
 "here":"place","hero":"society","hers":"gram","herself":"gram","hesitate":"mind","hi":"gram",
 "hide":"action","high":"adj","highlight":"mind","highly":"adv","highway":"travel","hill":"nature",
 "him":"gram","himself":"gram","hip":"body","hire":"work","his":"gram","historical":"adj",
 "history":"society","hit":"action","hobby":"sport","hold":"work","hold on":"work","hole":"place",
 "holiday":"time","hollow":"adj","holy":"society","home":"home","hometown":"place","homework":"edu",
 "honest":"feel","honestly":"adv","honour":"society","hook":"tech","hope":"feel","hopeful":"feel",
 "horizontal":"number","horn":"travel","horror":"feel","horse":"nature","hospital":"body","host":"media",
 "hot":"adj","hotel":"travel","hour":"time","house":"home","household":"home","housing":"home",
 "how":"gram","however":"gram","huge":"adj","human":"people","humorous":"adj","humour":"feel",
 "hundred":"number","hungry":"body","hunt":"sport","hunting":"sport","hurry":"action","hurt":"body",
 "husband":"people","I didn't catch that":"mind","ice":"food","ice cream":"food","idea":"mind","ideal":"adj",
 "ideally":"adv","identify":"mind","identity":"people","if":"gram","ignore":"mind","ill":"body",
 "illegal":"law","illegally":"adv","illness":"body","illustrate":"mind","image":"media","imaginary":"adj",
 "imagination":"mind","imagine":"mind","immediate":"adj","immediately":"adv","immoral":"feel","impact":"change",
 "impatient":"feel","impatiently":"adv","implication":"mind","imply":"mind","import":"biz","importance":"mind",
 "important":"adj","importantly":"adv","impose":"law","impossible":"adj","impress":"feel","impressed":"feel",
 "impression":"mind","impressive":"adj","improve":"change","improvement":"change","in":"gram","in case of":"gram",
 "in fact":"gram","in front of":"place","in general":"gram","inability":"mind","incentive":"biz","inch":"number",
 "incident":"society","include":"mind","including":"gram","income":"money","increase":"change","increasingly":"adv",
 "indeed":"adv","independence":"society","independent":"adj","independently":"adv","index":"edu","indicate":"mind",
 "indication":"mind","indirect":"adj","indirectly":"adv","individual":"people","indoor":"adj","indoors":"place",
 "industrial":"adj","industry":"biz","inevitable":"adj","inevitably":"adv","infect":"body","infected":"adj",
 "infection":"body","infectious":"adj","influence":"change","inform":"mind","informal":"adj","information":"mind",
 "ingredient":"food","initial":"adj","initially":"adv","initiative":"work","injure":"body","injured":"body",
 "injury":"body","ink":"work","inner":"adj","innocent":"law","insect":"nature","insert":"action",
 "inside":"place","insist on":"mind","install":"tech","installment":"money","instance":"mind","instead":"adv",
 "institute":"edu","institution":"society","instruction":"mind","instrument":"media","insult":"feel","insulting":"adj",
 "insurance":"money","intelligence":"mind","intelligent":"adj","intend":"mind","intended":"adj","intention":"mind",
 "interest":"mind","interested":"feel","interesting":"adj","interior":"home","internal":"adj","international":"adj",
 "internet":"tech","interpret":"mind","interpretation":"mind","interrupt":"mind","interruption":"mind","interval":"time",
 "interview":"work","into":"gram","introduce":"mind","introduction":"mind","invent":"tech","invention":"tech",
 "invest":"money","investigate":"law","investigation":"law","investment":"money","invitation":"society","invite":"work",
 "invoice":"money","involve":"mind","involvement":"mind","iron":"clothes","irritate":"feel","irritated":"feel",
 "irritating":"adj","island":"nature","issue":"work","it":"gram","item":"biz","its":"gram",
 "itself":"gram","jacket":"clothes","jam":"food","January":"time","jealous":"feel","jeans":"clothes",
 "jelly":"food","jewellery":"clothes","job":"work","join":"work","joint":"adj","jointly":"adv",
 "joke":"feel","journalist":"media","journey":"travel","joy":"feel","judge":"law","judgement":"mind",
 "juice":"food","July":"time","jump":"action","June":"time","junior":"work","just":"adv",
 "justice":"law","justified":"adj","justify":"mind","keen":"feel","keep":"action","keep in touch":"work",
 "key":"home","keyboard":"tech","kick":"action","kid":"people","kids":"people","kill":"law",
 "killing":"law","kilometre":"number","kind":"feel","kindly":"adv","kindness":"feel","king":"society",
 "kiss":"people","kitchen":"home","knee":"body","knife":"home","knit":"clothes","knitted":"adj",
 "knitting":"clothes","knock":"action","knot":"tech","know":"mind","knowledge":"mind","label":"biz",
 "labour":"work","lack of":"number","lacking":"adj","lady":"people","lake":"nature","lamp":"home",
 "land":"place","landscape":"nature","lane":"travel","language":"edu","laptop":"tech","large":"adj",
 "largely":"adv","last":"time","late":"time","later":"time","latest":"adj","latte":"food",
 "latter":"gram","laugh":"feel","launch":"biz","law":"law","lawyer":"law","lay":"action",
 "layer":"number","lazy":"feel","lead":"work","leader":"work","leading":"adj","leaf":"nature",
 "league":"sport","lean":"action","learn":"edu","least":"number","leather":"clothes","leave":"action",
 "lecture":"edu","left":"place","leg":"body","legal":"law","legally":"adv","lemon":"food",
 "lend":"money","length":"number","less":"number","lesson":"edu","let":"mind","letter":"work",
 "level":"number","library":"edu","licence":"law","license":"law","lid":"home","lie":"action",
 "life":"people","lift":"action","light":"home","lightly":"adv","like":"gram","likely":"adj",
 "limit":"number","limited":"adj","line":"place","link":"tech","lip":"body","liquid":"tech",
 "list":"work","listen":"mind","listen to":"action","literature":"edu","litre":"number","little":"number",
 "live":"people","lively":"adj","living":"people","load":"action","loan":"money","local":"adj",
 "locally":"adv","locate":"place","located":"adj","location":"place","lock":"home","logic":"mind",
 "logical":"adj","login":"tech","lonely":"feel","long":"adj","look":"action","look forward":"work",
 "loose":"adj","loosely":"adv","lord":"society","lorry":"travel","lose":"change","loss":"money",
 "lost":"adj","loud":"feel","loudly":"adv","love":"feel","lovely":"adj","lover":"people",
 "low":"adj","loyal":"feel","luck":"mind","lucky":"adj","luggage":"travel","lump":"number",
 "lunch":"food","lung":"body","machine":"tech","machinery":"tech","mad":"feel","magazine":"media",
 "magic":"media","mail":"work","main":"adj","mainly":"adv","maintain":"change","major":"adj",
 "majority":"number","make":"action","make-up":"clothes","male":"people","mall":"place","man":"people",
 "manage":"work","management":"work","manager":"work","manner":"people","manufacture":"biz","manufacturer":"biz",
 "manufacturing":"biz","many":"number","map":"travel","March":"time","margin":"money","mark":"edu",
 "market":"biz","marketing":"biz","marriage":"people","married":"people","marry":"people","mass":"number",
 "massive":"adj","master":"edu","match":"sport","matching":"adj","mate":"people","material":"tech",
 "matter":"mind","maximum":"number","may":"gram","maybe":"adv","mayor":"law","me":"gram",
 "meal":"food","mean":"mind","meaning":"mind","means":"mind","meanwhile":"time","measure":"number",
 "measurement":"number","meat":"food","media":"media","medical":"body","medicine":"body","medium":"adj",
 "meet":"work","meeting":"work","melt":"change","member":"society","membership":"society","memory":"mind",
 "mental":"body","mentally":"adv","mention":"mind","menu":"food","mere":"adj","merely":"adv",
 "mess":"home","message":"work","metal":"tech","method":"mind","metre":"number","midday":"time",
 "middle":"place","midnight":"time","mild":"adj","mile":"number","military":"law","milk":"food",
 "million":"number","mind":"mind","mine":"gram","mineral":"tech","minimum":"number","minister":"law",
 "ministry":"law","minor":"adj","minority":"number","minute":"time","mirror":"home","miss":"feel",
 "missing":"adj","mistake":"mind","mistaken":"adj","mix":"change","mixed":"adj","mixture":"number",
 "mobile":"adj","mobile phone":"tech","model":"biz","modern":"adj","moment":"time","Monday":"time",
 "money":"money","monitor":"tech","month":"time","monthly":"time","mood":"feel","moon":"nature",
 "moral":"feel","morally":"adv","more":"number","more or less":"gram","moreover":"gram","morning":"time",
 "most":"number","mostly":"adv","mother":"people","motion":"action","motivated":"feel","motor":"tech",
 "motorbike":"travel","motorcycle":"travel","mount":"action","mountain":"nature","mouse":"nature","mouth":"body",
 "move":"action","movement":"action","movie":"media","movie theater":"media","moving":"adj","Mr":"people",
 "Mrs":"people","Ms":"people","much":"number","mud":"nature","multiply":"number","mum":"people",
 "murder":"law","muscle":"body","museum":"media","music":"media","musical":"adj","musician":"media",
 "must":"gram","my":"gram","myself":"gram","mysterious":"adj","mystery":"mind","nail":"body",
 "naked":"adj","name":"people","napkin":"food","narrow":"adj","nation":"society","national":"adj",
 "natural":"adj","naturally":"adv","nature":"nature","navy":"law","near":"place","nearby":"place",
 "nearly":"adv","neat":"adj","neatly":"adv","necessarily":"adv","necessary":"adj","neck":"body",
 "need":"mind","needle":"clothes","negative":"feel","negotiate":"biz","negotiation":"biz","neighbor":"people",
 "neighbour":"people","neighbourhood":"place","neither":"gram","nephew":"people","nerve":"body","nervous":"feel",
 "nervously":"adv","nest":"nature","net":"sport","network":"tech","never":"adv","nevertheless":"gram",
 "new":"adj","newly":"adv","news":"media","newspaper":"media","next":"gram","nice":"adj",
 "nicely":"adv","niece":"people","night":"time","nobody":"gram","noise":"media","noisily":"adv",
 "noisy":"adj","non-":"gram","none":"gram","nonsense":"mind","noodle":"food","nor":"gram",
 "normal":"adj","normally":"adv","north":"place","northern":"place","nose":"body","not":"gram",
 "note":"work","nothing":"gram","notice":"mind","noticeable":"adj","notification":"tech","novel":"media",
 "November":"time","now":"time","nowhere":"gram","nuclear":"tech","number":"number","nurse":"body",
 "nut":"food","o clock":"time","o'clock":"time","obey":"law","object":"mind","objection":"biz",
 "objective":"work","observation":"mind","observe":"mind","obtain":"change","obvious":"adj","obviously":"adv",
 "occasion":"society","occasionally":"adv","occupied":"adj","occupy":"place","occur":"change","ocean":"nature",
 "October":"time","odd":"adj","oddly":"adv","of":"gram","of course":"gram","off":"gram",
 "offence":"law","offend":"feel","offensive":"adj","offer":"biz","office":"work","officer":"law",
 "official":"adj","officially":"adv","often":"adv","oh":"gram","oil":"food","old":"adj",
 "old-fashioned":"adj","on":"gram","on the phone":"work","once":"time","one":"number","onion":"food",
 "only":"adv","onto":"gram","open":"action","opening":"place","openly":"adv","operate":"tech",
 "operation":"body","opinion":"mind","opponent":"sport","opportunity":"biz","oppose":"mind","opposed":"adj",
 "opposing":"adj","opposite":"place","opposition":"law","option":"mind","orange":"food","order":"biz",
 "ordinary":"adj","organ":"body","organization":"work","organize":"work","organized":"adj","origin":"mind",
 "original":"adj","originally":"adv","other":"gram","otherwise":"gram","ought to":"gram","our":"gram",
 "ours":"gram","ourselves":"gram","out of":"gram","outdoor":"adj","outdoors":"place","outer":"adj",
 "outline":"mind","output":"biz","outside":"place","outstanding":"adj","oven":"home","over":"place",
 "overall":"adj","overcome":"change","owe":"money","own":"money","owner":"money","pace":"number",
 "pack":"action","package":"biz","packaging":"biz","packet":"biz","page":"media","pain":"body",
 "painful":"body","paint":"media","painter":"media","painting":"media","pair":"number","palace":"place",
 "pale":"adj","pan":"home","panel":"tech","pants":"clothes","paper":"work","parallel":"number",
 "parent":"people","parents":"people","park":"place","parking":"travel","parliament":"law","part":"number",
 "particular":"adj","particularly":"adv","partly":"adv","partner":"biz","partnership":"biz","party":"society",
 "pass":"action","passage":"media","passenger":"travel","passing":"adj","passport":"travel","password":"tech",
 "past":"time","path":"place","patience":"feel","patient":"feel","pattern":"mind","pause":"time",
 "pay":"money","payment":"money","peace":"society","peaceful":"adj","peak":"number","peak hours":"food",
 "pen":"work","pence":"money","pencil":"work","penny":"money","pension":"money","people":"people",
 "pepper":"food","per":"number","percent":"number","perfect":"adj","perfectly":"adv","perform":"media",
 "performance":"work","performer":"media","perhaps":"adv","period":"time","permanent":"adj","permanently":"adv",
 "permission":"tech","permit":"law","person":"people","personal":"adj","personality":"people","personally":"adv",
 "persuade":"mind","pet":"nature","petrol":"travel","phase":"time","philosophy":"edu","phone":"tech",
 "photocopy":"work","photograph":"media","photographer":"media","photography":"media","phrase":"edu","physical":"adj",
 "physically":"adv","physics":"edu","piano":"media","pick":"action","picture":"media","piece":"number",
 "pig":"nature","pile":"number","pill":"body","pilot":"travel","pin":"clothes","pink":"adj",
 "pint":"number","pipe":"tech","pitch":"biz","pity":"feel","place":"place","plain":"adj",
 "plan":"work","plane":"travel","planet":"nature","planning":"work","plant":"nature","plastic":"tech",
 "plate":"home","platform":"travel","play":"sport","player":"sport","pleasant":"adj","pleasantly":"adv",
 "please":"mind","pleased":"feel","pleasing":"adj","pleasure":"feel","plenty":"number","plot":"media",
 "plug":"tech","plus":"number","pocket":"clothes","poem":"media","poetry":"media","point":"mind",
 "pointed":"adj","poison":"body","poisonous":"adj","pole":"tech","police":"law","policy":"work",
 "polish":"home","polite":"feel","politely":"adv","political":"adj","politically":"adv","politician":"law",
 "politics":"law","pollution":"nature","pool":"sport","poor":"adj","pop":"media","popular":"adj",
 "population":"society","port":"travel","portion":"food","pose":"action","position":"place","positive":"feel",
 "possess":"money","possession":"money","possibility":"mind","possible":"adj","possibly":"adv","post":"work",
 "post office":"work","postpone":"work","pot":"home","potato":"food","potential":"mind","potentially":"adv",
 "pound":"money","pour":"food","powder":"food","power":"change","powerful":"adj","practical":"adj",
 "practically":"adv","practice":"edu","practise":"edu","praise":"feel","prayer":"society","precise":"adj",
 "precisely":"adv","predict":"mind","prefer":"mind","preference":"mind","pregnant":"body","premises":"place",
 "preparation":"work","prepare":"work","prepared":"adj","presence":"place","present":"work","presentation":"work",
 "preserve":"change","president":"law","press":"media","pressure":"feel","presumably":"adv","pretend":"mind",
 "pretty":"adj","prevent":"change","previous":"adj","previously":"adv","price":"money","pride":"feel",
 "priest":"society","primarily":"adv","primary":"adj","prime minister":"law","prince":"society","princess":"society",
 "principle":"mind","print":"work","printer":"tech","printing":"work","prior":"adj","priority":"work",
 "prison":"law","prisoner":"law","private":"adj","privately":"adv","prize":"sport","probable":"adj",
 "probably":"adv","problem":"mind","procedure":"work","proceed":"action","process":"work","produce":"biz",
 "producer":"biz","product":"biz","production":"biz","profession":"work","professional":"work","professor":"edu",
 "profit":"money","program":"tech","programme":"media","progress":"change","project":"work","promise":"mind",
 "promote":"work","promotion":"work","prompt":"adj","promptly":"adv","pronounce":"edu","pronunciation":"edu",
 "proof":"mind","proper":"adj","properly":"adv","property":"money","proportion":"number","proposal":"biz",
 "propose":"mind","prospect":"biz","protect":"change","protection":"change","protest":"law","proud":"feel",
 "proudly":"adv","prove":"mind","provide":"biz","public":"adj","publication":"media","publicity":"media",
 "publicly":"adv","publish":"media","publishing":"media","pull":"action","punch":"action","punish":"law",
 "punishment":"law","pupil":"edu","purchase":"biz","pure":"adj","purely":"adv","purple":"adj",
 "purpose":"mind","pursue":"action","push":"action","put":"action","qualification":"work","qualified":"adj",
 "qualify":"work","quality":"biz","quantity":"number","quarter":"number","queen":"society","question":"mind",
 "queue":"biz","quick":"adj","quickly":"adv","quiet":"feel","quietly":"adv","quit":"work",
 "quite":"adv","quote":"biz","race":"sport","racing":"sport","radio":"media","rail":"travel",
 "railway":"travel","rain":"nature","raise":"change","range":"number","rank":"number","rapid":"adj",
 "rapidly":"adv","rare":"adj","rarely":"adv","rate":"number","rather":"adv","raw":"adj",
 "reach":"action","react":"change","reaction":"change","read":"edu","reader":"edu","reading":"edu",
 "ready":"adj","real":"adj","realistic":"adj","reality":"mind","realize":"mind","really":"adv",
 "rear":"place","reason":"mind","reasonable":"adj","reasonably":"adv","recall":"mind","receipt":"money",
 "receive":"work","recent":"adj","recently":"adv","reception":"work","recipe":"food","reckon":"mind",
 "recognition":"mind","recognize":"mind","recommend":"mind","record":"media","recording":"media","recover":"body",
 "red":"adj","reduce":"change","reduction":"change","refer to":"mind","reference":"biz","referral":"biz",
 "reflect":"mind","reform":"law","refrigerator":"home","refund":"money","refusal":"mind","refuse":"mind",
 "regard":"mind","regarding":"gram","regards":"work","region":"place","regional":"adj","register":"work",
 "regret":"feel","regular":"adj","regularly":"adv","regulation":"law","reject":"mind","relate":"mind",
 "related to":"mind","relation":"people","relationship":"people","relative":"people","relatively":"adv","relax":"feel",
 "relaxed":"feel","relaxing":"adj","release":"change","relevant":"adj","reliable":"feel","relief":"feel",
 "religion":"society","religious":"adj","rely on":"mind","remain":"change","remaining":"adj","remains":"number",
 "remark":"mind","remarkable":"adj","remarkably":"adv","remember":"mind","remind":"mind","reminder":"work",
 "remote":"home","removal":"change","remove":"change","rent":"money","rented":"adj","repair":"tech",
 "repeat":"mind","repeated":"adj","repeatedly":"adv","replace":"change","reply":"work","report":"work",
 "represent":"mind","representative":"work","reproduce":"change","reputation":"biz","request":"mind","require":"mind",
 "requirement":"work","reschedule":"work","rescue":"body","research":"edu","reservation":"food","reserve":"biz",
 "resident":"place","resist":"change","resistance":"change","resolve":"mind","resort":"travel","resource":"biz",
 "respect":"feel","respond":"mind","response":"mind","responsibility":"work","responsible":"work","rest":"body",
 "restaurant":"food","restore":"change","restrict":"law","restricted":"adj","restriction":"law","result":"change",
 "retain":"change","retire":"work","retired":"adj","retirement":"work","return":"action","reveal":"mind",
 "reverse":"change","review":"mind","revise":"edu","revision":"edu","revolution":"society","reward":"work",
 "rhythm":"media","rice":"food","rich":"adj","rid":"change","ride":"travel","rider":"sport",
 "ridiculous":"adj","riding":"sport","right":"place","rightly":"adv","ring":"action","rise":"change",
 "risk":"biz","rival":"biz","river":"nature","road":"travel","rob":"law","rock":"nature",
 "role":"work","roll":"action","romantic":"adj","roof":"home","room":"home","root":"nature",
 "rope":"tech","rough":"adj","roughly":"adv","round":"adj","rounded":"adj","route":"travel",
 "routine":"work","row":"number","royal":"society","rub":"action","rubber":"tech","rubbish":"home",
 "rude":"feel","rudely":"adv","ruin":"change","ruined":"adj","rule":"law","ruler":"law",
 "rumour":"mind","run":"action","runner":"sport","running":"sport","rural":"adj","rush":"action",
 "sack":"work","sad":"feel","sadly":"adv","sadness":"feel","safe":"adj","safely":"adv",
 "safety":"body","sail":"travel","sailing":"sport","sailor":"travel","salad":"food","salary":"money",
 "sale":"biz","salt":"food","salty":"adj","same":"adj","sample":"biz","sand":"nature",
 "satisfaction":"feel","satisfied":"feel","satisfy":"feel","satisfying":"adj","Saturday":"time","sauce":"food",
 "save":"money","saving":"money","say":"mind","scale":"number","scare":"feel","scared":"feel",
 "scene":"media","schedule":"work","scheme":"work","school":"edu","science":"edu","scientific":"adj",
 "scientist":"edu","scissors":"home","score":"sport","scratch":"action","scream":"feel","screen":"tech",
 "screw":"tech","sea":"nature","seal":"action","search":"action","season":"time","seat":"travel",
 "second":"time","secondary":"adj","secret":"mind","secretary":"work","secretly":"adv","section":"number",
 "sector":"biz","secure":"adj","security":"tech","see":"action","seed":"nature","seek":"action",
 "seem":"mind","select":"mind","selection":"mind","self":"people","self-":"gram","sell":"biz",
 "senate":"law","senator":"law","send":"work","senior":"work","sense":"mind","sensible":"adj",
 "sensitive":"feel","sentence":"edu","separate":"action","separated":"adj","separately":"adv","separation":"people",
 "September":"time","series":"media","serious":"feel","seriously":"adv","servant":"work","serve":"food",
 "server":"tech","service":"biz","session":"work","set":"number","setting":"tech","settle":"change",
 "several":"number","severe":"adj","severely":"adv","sew":"clothes","sewing":"clothes","sex":"people",
 "sexual":"adj","sexually":"adv","shade":"nature","shadow":"nature","shake":"action","shall":"gram",
 "shallow":"adj","shame":"feel","shape":"number","shaped":"adj","share":"biz","sharp":"adj",
 "sharply":"adv","shave":"body","she":"gram","sheep":"nature","sheet":"home","shelf":"home",
 "shell":"nature","shelter":"place","shift":"food","shine":"nature","shiny":"adj","ship":"travel",
 "shirt":"clothes","shock":"feel","shocked":"feel","shocking":"adj","shoe":"clothes","shoes":"clothes",
 "shoot":"action","shooting":"sport","shop":"biz","shopping":"biz","short":"adj","shortly":"adv",
 "shot":"sport","should":"gram","shoulder":"body","shout":"mind","show":"mind","shower":"home",
 "shut":"action","shy":"feel","siblings":"people","sick":"body","side":"place","sideways":"place",
 "sight":"body","sign":"mind","signal":"tech","signature":"work","significant":"adj","significantly":"adv",
 "silence":"media","silent":"adj","silk":"clothes","silly":"adj","silver":"money","similar":"adj",
 "similarly":"adv","simple":"adj","simply":"adv","since":"gram","sincere":"feel","sincerely":"work",
 "sing":"media","singer":"media","singing":"media","single":"people","sink":"home","sir":"people",
 "sister":"people","sit":"action","situation":"mind","size":"number","skilful":"adj","skilfully":"adv",
 "skill":"work","skilled":"adj","skin":"body","skirt":"clothes","sky":"nature","sleep":"body",
 "sleeve":"clothes","slice":"food","slide":"action","slight":"adj","slightly":"adv","slip":"action",
 "slope":"place","slow":"adj","slowly":"adv","small":"adj","smart":"feel","smash":"action",
 "smell":"body","smile":"feel","smoke":"body","smoking":"body","smooth":"adj","smoothie":"food",
 "smoothly":"adv","snack":"food","snake":"nature","snow":"nature","so":"gram","soap":"home",
 "social":"adj","socially":"adv","society":"society","sock":"clothes","soft":"adj","softly":"adv",
 "software":"tech","soil":"nature","soldier":"law","solid":"adj","solution":"biz","solve":"mind",
 "some":"gram","somehow":"adv","something":"gram","sometimes":"adv","somewhat":"adv","somewhere":"gram",
 "son":"people","song":"media","soon":"time","sore":"body","sorry":"mind","sort":"mind",
 "soul":"society","sound":"media","soup":"food","sour":"food","source":"mind","south":"place",
 "southern":"place","space":"place","spare":"adj","speak":"mind","speak up":"mind","speaker":"media",
 "special":"adj","specialist":"work","specially":"adv","specific":"adj","specifically":"adv","speech":"mind",
 "speed":"number","spell":"edu","spelling":"edu","spend":"money","spice":"food","spicy":"food",
 "spider":"nature","spin":"action","spirit":"society","spiritual":"adj","spite":"feel","split":"change",
 "spoil":"change","spoken":"adj","spoon":"home","sport":"sport","spot":"place","spray":"action",
 "spread":"action","spreadsheet":"work","spring":"time","square":"number","squeeze":"action","stable":"adj",
 "staff":"work","stage":"media","stair":"home","stamp":"work","stand":"action","standard":"adj",
 "star":"media","stare":"action","start":"change","state":"law","statement":"mind","station":"travel",
 "statue":"media","status":"society","stay":"action","steadily":"adv","steady":"adj","steal":"law",
 "steam":"nature","steel":"tech","steep":"adj","steeply":"adv","steer":"travel","step":"action",
 "stick":"action","sticky":"adj","stiff":"adj","stiffly":"adv","still":"adv","sting":"body",
 "stir":"food","stock":"biz","stomach":"body","stone":"tech","stop":"action","store":"biz",
 "storm":"nature","story":"media","stove":"home","straight":"place","strain":"body","strange":"adj",
 "strangely":"adv","stranger":"people","strategy":"work","stream":"nature","street":"place","strength":"body",
 "stress":"feel","stressed":"feel","stretch":"action","strict":"feel","strictly":"adv","strike":"work",
 "striking":"adj","string":"tech","strip":"number","stripe":"clothes","striped":"adj","stroke":"body",
 "strong":"feel","strongly":"adv","structure":"tech","struggle":"change","student":"edu","studio":"media",
 "study":"edu","stuff":"mind","stupid":"adj","style":"clothes","subject":"work","substance":"tech",
 "substantial":"adj","substantially":"adv","substitute":"change","succeed":"change","success":"change","successful":"adj",
 "successfully":"adv","such":"gram","suck":"action","sudden":"adj","suddenly":"adv","suffer":"feel",
 "suffering":"feel","sufficient":"adj","sufficiently":"adv","sugar":"food","suggest":"mind","suggestion":"mind",
 "suit":"clothes","suitable":"adj","suitcase":"travel","suited":"adj","sum":"number","summary":"work",
 "summer":"time","sun":"nature","Sunday":"time","sunny":"adj","superior":"adj","supermarket":"biz",
 "supply":"biz","support":"work","supporter":"sport","suppose":"mind","sure":"adj","surely":"adv",
 "surface":"place","surname":"people","surprise":"feel","surprised":"feel","surprising":"adj","surprisingly":"adv",
 "surround":"place","surrounding":"adj","surroundings":"place","survey":"biz","survive":"change","suspect":"law",
 "suspicion":"law","suspicious":"feel","swallow":"food","swear":"mind","swearing":"mind","sweat":"body",
 "sweater":"clothes","sweep":"home","sweet":"food","swell":"body","swelling":"body","swim":"sport",
 "swimming":"sport","swimming pool":"sport","swing":"action","switch":"tech","swollen":"adj","symbol":"mind",
 "sympathetic":"feel","sympathy":"feel","sync":"tech","system":"tech","table":"home","tablet":"tech",
 "tackle":"action","tail":"nature","take":"action","takeaway":"food","talk":"mind","tall":"adj",
 "tank":"tech","tap":"home","tape":"tech","target":"work","task":"work","taste":"food",
 "tax":"money","taxi":"travel","tea":"food","teach":"edu","teacher":"edu","teaching":"edu",
 "team":"work","tear":"action","technical":"adj","technique":"work","technology":"tech","telephone":"tech",
 "television":"media","tell":"mind","temperature":"number","temporarily":"adv","temporary":"adj","tend":"mind",
 "tendency":"mind","tension":"feel","tent":"travel","term":"biz","terrible":"adj","terribly":"adv",
 "test":"edu","text":"media","than":"gram","thank":"mind","thanks":"mind","that":"gram",
 "the":"gram","theatre":"media","their":"gram","theirs":"gram","them":"gram","theme":"mind",
 "themselves":"gram","then":"gram","theory":"mind","there":"place","therefore":"gram","they":"gram",
 "thick":"adj","thickly":"adv","thickness":"number","thief":"law","thin":"adj","thing":"mind",
 "think":"mind","thinking":"mind","thirsty":"body","this":"gram","thorough":"adj","thoroughly":"adv",
 "though":"gram","thought":"mind","thousand":"number","thread":"clothes","threat":"law","threaten":"law",
 "threatening":"adj","throat":"body","through":"place","throughout":"gram","throw":"action","thumb":"body",
 "Thursday":"time","thus":"gram","ticket":"travel","tidy":"adj","tie":"clothes","tight":"adj",
 "tightly":"adv","till":"gram","time":"time","timetable":"time","tin":"home","tiny":"adj",
 "tip":"food","tire":"body","tired":"feel","tiring":"adj","title":"media","to":"gram",
 "to be honest":"gram","today":"time","toe":"body","together":"adv","toilet":"home","tomato":"food",
 "tomorrow":"time","ton":"number","tone":"media","tongue":"body","tonight":"time","tonne":"number",
 "too":"adv","tool":"tech","tooth":"body","top":"place","topic":"mind","total":"number",
 "totally":"adv","touch":"action","tough":"adj","tour":"travel","tourist":"travel","toward":"place",
 "towards":"gram","towel":"home","tower":"place","town":"place","toy":"home","trace":"mind",
 "track":"travel","trade":"biz","trading":"biz","tradition":"society","traditional":"adj","traditionally":"adv",
 "traffic":"travel","train":"work","training":"work","transfer":"change","transform":"change","translate":"edu",
 "translation":"edu","transparent":"adj","transport":"travel","trap":"action","travel":"travel","traveller":"travel",
 "tray":"food","treat":"feel","treatment":"body","tree":"nature","trend":"biz","trial":"law",
 "triangle":"number","trick":"mind","trip":"travel","tropical":"adj","trouble":"mind","trousers":"clothes",
 "truck":"travel","true":"adj","truly":"adv","trust":"feel","truth":"mind","try":"action",
 "try on":"clothes","tube":"tech","Tuesday":"time","tune":"media","tunnel":"travel","turn":"action",
 "turnover":"money","twice":"number","twin":"people","twist":"action","twisted":"adj","type":"mind",
 "typical":"adj","typically":"adv","tyre":"travel","ugly":"adj","ultimate":"adj","ultimately":"adv",
 "umbrella":"clothes","unable":"adj","unacceptable":"adj","uncertain":"adj","uncle":"people","uncomfortable":"adj",
 "unconscious":"body","uncontrolled":"adj","under":"place","underground":"travel","underneath":"gram","understand":"mind",
 "understanding":"mind","underwater":"place","underwear":"clothes","undo":"action","unemployed":"work","unemployment":"work",
 "unexpected":"adj","unexpectedly":"adv","unfair":"adj","unfairly":"adv","unfortunate":"adj","unfortunately":"adv",
 "unfriendly":"adj","unhappiness":"feel","unhappy":"feel","uniform":"clothes","unimportant":"adj","union":"work",
 "unique":"adj","unit":"number","unite":"change","united":"adj","universe":"nature","university":"edu",
 "unkind":"adj","unknown":"adj","unless":"gram","unlike":"gram","unlikely":"adj","unload":"action",
 "unlucky":"adj","unnecessary":"adj","unpleasant":"adj","unreasonable":"adj","unsteady":"adj","unsuccessful":"adj",
 "untidy":"adj","Unusual":"adj","unusually":"adv","Unwilling":"feel","unwillingly":"adv","up":"place",
 "upload":"tech","upon":"gram","upper":"adj","upsell":"biz","upset":"feel","upsetting":"adj",
 "upside down":"place","upstairs":"home","upward":"place","upwards":"place","urban":"adj","urge":"mind",
 "urgent":"adj","us":"gram","use":"action","used":"adj","useful":"adj","useless":"adj",
 "user":"tech","usual":"adj","usually":"adv","vacation":"travel","valid":"adj","valley":"nature",
 "valuable":"adj","value":"biz","van":"travel","variation":"change","varied":"adj","variety":"number",
 "various":"adj","vary":"change","vast":"adj","vegetable":"food","vehicle":"travel","venture":"biz",
 "version":"tech","vertical":"number","very":"adv","via":"gram","victim":"law","victory":"sport",
 "video":"media","view":"mind","village":"place","violence":"law","violent":"adj","violently":"adv",
 "virtually":"adv","virus":"body","visa":"travel","visible":"adj","vision":"mind","visit":"travel",
 "visitor":"people","vital":"adj","vocabulary":"edu","voice":"media","voicemail":"work","volume":"number",
 "vote":"law","wage":"money","waist":"body","wait":"action","waiter":"food","waitress":"food",
 "wake":"body","wake up":"body","walk":"action","walking":"sport","wall":"home","wallet":"clothes",
 "wander":"action","want":"feel","war":"law","warm":"adj","warmth":"nature","warn":"mind",
 "warning":"mind","warranty":"biz","wash":"home","washing":"home","waste":"change","watch":"clothes",
 "water":"food","wave":"nature","way":"mind","we":"gram","weak":"feel","weakness":"body",
 "wealth":"money","weapon":"law","wear":"clothes","weather":"nature","web":"tech","website":"tech",
 "wedding":"society","Wednesday":"time","week":"time","weekend":"time","weekly":"time","weigh":"number",
 "weight":"body","welcome":"mind","well":"adv","well known":"adj","west":"place","western":"place",
 "wet":"adj","what":"gram","whatever":"gram","wheel":"travel","when":"gram","whenever":"gram",
 "where":"gram","whereas":"gram","wherever":"gram","whether":"gram","which":"gram","while":"gram",
 "whilst":"gram","whisper":"mind","whistle":"media","white":"adj","who":"gram","whoever":"gram",
 "whole":"adj","whom":"gram","whose":"gram","why":"gram","wide":"adj","widely":"adv",
 "width":"number","wife":"people","wifi":"tech","wild":"adj","wildly":"adv","will":"gram",
 "willing":"feel","willingly":"adv","willingness":"feel","win":"biz","wind":"nature","window":"home",
 "wine":"food","wing":"nature","winner":"sport","winning":"adj","winter":"time","wire":"tech",
 "wise":"adj","wish":"feel","with":"gram","withdraw":"money","within":"gram","without":"gram",
 "witness":"law","woman":"people","wonder":"mind","wonderful":"adj","wood":"tech","wooden":"adj",
 "wool":"clothes","work":"work","worker":"work","workflow":"work","working":"adj","world":"place",
 "worried":"feel","worry":"feel","worrying":"adj","worse":"adj","worship":"society","worth":"money",
 "would":"gram","wound":"body","wounded":"body","wrap":"action","wrap up":"work","wrapping":"biz",
 "wrist":"body","write":"edu","writer":"media","writing":"edu","written":"adj","wrong":"adj",
 "wrongly":"adv","yard":"number","yawn":"body","year":"time","yearly":"time","yellow":"adj",
 "yes":"gram","yesterday":"time","yet":"adv","you":"gram","young":"adj","your":"gram",
 "yours":"gram","yourself":"gram","youth":"people","zero":"number","zone":"place",
};
