/* 600 từ vựng thông dụng theo chủ đề — cho web Sổ tay học tiếng Anh.
   Mỗi từ: t=từ, ipa=phiên âm (giọng Mỹ), p=loại từ (v/n/adj/adv/phr/prep),
   vn=nghĩa tiếng Việt, ex=ví dụ 1 câu, tip=mẹo (không bắt buộc).
   IPA soạn tay theo kiểu Cambridge (US) — có thể còn vài chỗ cần dò lại. */
window.VOCAB600=[
{id:"daily-verbs",title:"Động từ đời sống",icon:"i-play",c:"noi",words:[
 {t:"go",ipa:"ɡoʊ",p:"v",vn:"đi",ex:"I go to the office every morning."},
 {t:"come",ipa:"kʌm",p:"v",vn:"đến, tới",ex:"Can you come to the meeting at 9?"},
 {t:"get",ipa:"ɡet",p:"v",vn:"lấy, nhận; trở nên",ex:"I get a lot of emails every day."},
 {t:"make",ipa:"meɪk",p:"v",vn:"làm, tạo ra",ex:"Let's make a plan for next week."},
 {t:"take",ipa:"teɪk",p:"v",vn:"lấy, cầm; mất (thời gian)",ex:"The waiter takes the order on a tablet."},
 {t:"do",ipa:"duː",p:"v",vn:"làm",ex:"What do you do for a living?"},
 {t:"have",ipa:"hæv",p:"v",vn:"có",ex:"We have five outlets in the city."},
 {t:"see",ipa:"siː",p:"v",vn:"thấy, gặp; hiểu",ex:"I see what you mean."},
 {t:"know",ipa:"noʊ",p:"v",vn:"biết",ex:"I know that company well."},
 {t:"think",ipa:"θɪŋk",p:"v",vn:"nghĩ",ex:"I think the price is fair.",tip:"Âm /θ/ — lưỡi giữa 2 hàm răng."},
 {t:"want",ipa:"wɑːnt",p:"v",vn:"muốn",ex:"Do they want the POS or the KDS?"},
 {t:"need",ipa:"niːd",p:"v",vn:"cần",ex:"You need a stable internet connection."},
 {t:"use",ipa:"juːz",p:"v",vn:"dùng, sử dụng",ex:"How many staff will use the system?"},
 {t:"find",ipa:"faɪnd",p:"v",vn:"tìm, tìm thấy",ex:"I can't find the receipt."},
 {t:"give",ipa:"ɡɪv",p:"v",vn:"đưa, cho",ex:"Let me give you a quick demo."},
 {t:"tell",ipa:"tel",p:"v",vn:"nói, kể, bảo",ex:"Please tell me if you have a problem."},
 {t:"work",ipa:"wɜːrk",p:"v",vn:"làm việc; hoạt động",ex:"It also works offline."},
 {t:"call",ipa:"kɔːl",p:"v",vn:"gọi (điện)",ex:"I'll call you back this afternoon."},
 {t:"try",ipa:"traɪ",p:"v",vn:"thử; cố gắng",ex:"You can try it free for 14 days."},
 {t:"ask",ipa:"æsk",p:"v",vn:"hỏi; yêu cầu",ex:"Can I ask you a few questions?"},
 {t:"feel",ipa:"fiːl",p:"v",vn:"cảm thấy",ex:"I feel confident about this deal."},
 {t:"become",ipa:"bɪˈkʌm",p:"v",vn:"trở thành",ex:"He became our biggest client."},
 {t:"leave",ipa:"liːv",p:"v",vn:"rời đi; để lại",ex:"Don't leave before we sign."},
 {t:"put",ipa:"pʊt",p:"v",vn:"đặt, để",ex:"Put the tablet near the counter."},
 {t:"mean",ipa:"miːn",p:"v",vn:"nghĩa là, có ý",ex:"What do you mean by that?"},
 {t:"keep",ipa:"kiːp",p:"v",vn:"giữ",ex:"Keep the receipt for your records."},
 {t:"let",ipa:"let",p:"v",vn:"để, cho phép",ex:"Let me check and get back to you."},
 {t:"begin",ipa:"bɪˈɡɪn",p:"v",vn:"bắt đầu",ex:"We begin the installation next month."},
 {t:"seem",ipa:"siːm",p:"v",vn:"có vẻ",ex:"The client seems interested."},
 {t:"help",ipa:"help",p:"v",vn:"giúp",ex:"How can I help you today?"},
 {t:"talk",ipa:"tɔːk",p:"v",vn:"nói chuyện",ex:"Can we talk about the price?"},
 {t:"turn",ipa:"tɜːrn",p:"v",vn:"quay, rẽ; bật/tắt",ex:"Turn on the tablet before the shift."},
 {t:"start",ipa:"stɑːrt",p:"v",vn:"bắt đầu",ex:"Let's start the meeting."},
 {t:"show",ipa:"ʃoʊ",p:"v",vn:"cho xem, chỉ",ex:"Let me show you the dashboard."},
 {t:"hear",ipa:"hɪr",p:"v",vn:"nghe (thấy)",ex:"Sorry, I didn't hear that."},
 {t:"play",ipa:"pleɪ",p:"v",vn:"chơi; phát (nhạc)",ex:"We play soft music in the café."},
 {t:"run",ipa:"rʌn",p:"v",vn:"chạy; vận hành, điều hành",ex:"She runs three coffee shops."},
 {t:"move",ipa:"muːv",p:"v",vn:"di chuyển, chuyển",ex:"Let's move to the next point."},
 {t:"live",ipa:"lɪv",p:"v",vn:"sống",ex:"I live in Ho Chi Minh City."},
 {t:"believe",ipa:"bɪˈliːv",p:"v",vn:"tin",ex:"I believe this will help your business."},
 {t:"bring",ipa:"brɪŋ",p:"v",vn:"mang, đem (tới)",ex:"Bring your laptop to the demo."},
 {t:"happen",ipa:"ˈhæpən",p:"v",vn:"xảy ra",ex:"What happened last month?"},
 {t:"write",ipa:"raɪt",p:"v",vn:"viết",ex:"I'll write you a full quote."},
 {t:"sit",ipa:"sɪt",p:"v",vn:"ngồi",ex:"Please sit, I'll be right with you."},
 {t:"stand",ipa:"stænd",p:"v",vn:"đứng",ex:"The waiter stands near the door."},
 {t:"lose",ipa:"luːz",p:"v",vn:"mất; thua",ex:"You lose money from inventory mistakes."},
 {t:"pay",ipa:"peɪ",p:"v",vn:"trả (tiền)",ex:"Customers can pay by e-wallet."},
 {t:"meet",ipa:"miːt",p:"v",vn:"gặp",ex:"Nice to meet you."},
 {t:"include",ipa:"ɪnˈkluːd",p:"v",vn:"bao gồm",ex:"The fee includes training and support."},
 {t:"continue",ipa:"kənˈtɪnjuː",p:"v",vn:"tiếp tục",ex:"Let's continue after lunch."}
]},
{id:"work-verbs",title:"Động từ công việc & hành động",icon:"i-target",c:"tonghop",words:[
 {t:"send",ipa:"send",p:"v",vn:"gửi",ex:"I'll send you the contract tomorrow."},
 {t:"receive",ipa:"rɪˈsiːv",p:"v",vn:"nhận",ex:"Did you receive my email?"},
 {t:"manage",ipa:"ˈmænɪdʒ",p:"v",vn:"quản lý",ex:"I manage a small sales team."},
 {t:"lead",ipa:"liːd",p:"v",vn:"dẫn dắt, lãnh đạo",ex:"I lead the sales team in the south."},
 {t:"sell",ipa:"sel",p:"v",vn:"bán",ex:"We sell software to restaurants."},
 {t:"buy",ipa:"baɪ",p:"v",vn:"mua",ex:"Most owners buy the yearly plan."},
 {t:"deliver",ipa:"dɪˈlɪvər",p:"v",vn:"giao (hàng); thực hiện",ex:"We deliver the setup in three weeks."},
 {t:"install",ipa:"ɪnˈstɔːl",p:"v",vn:"cài đặt, lắp đặt",ex:"We install the POS on site."},
 {t:"fix",ipa:"fɪks",p:"v",vn:"sửa",ex:"Our team can fix the issue remotely."},
 {t:"check",ipa:"tʃek",p:"v",vn:"kiểm tra",ex:"Let me check with my manager."},
 {t:"confirm",ipa:"kənˈfɜːrm",p:"v",vn:"xác nhận",ex:"Let me confirm what we agreed."},
 {t:"agree",ipa:"əˈɡriː",p:"v",vn:"đồng ý",ex:"We agree on the payment terms."},
 {t:"arrange",ipa:"əˈreɪndʒ",p:"v",vn:"sắp xếp, thu xếp",ex:"I'll arrange a demo for your team."},
 {t:"explain",ipa:"ɪkˈspleɪn",p:"v",vn:"giải thích",ex:"Let me explain the price structure."},
 {t:"discuss",ipa:"dɪˈskʌs",p:"v",vn:"thảo luận, bàn",ex:"Can we discuss this next week?"},
 {t:"decide",ipa:"dɪˈsaɪd",p:"v",vn:"quyết định",ex:"When can you decide?"},
 {t:"plan",ipa:"plæn",p:"v",vn:"lên kế hoạch",ex:"We plan to open two new branches."},
 {t:"prepare",ipa:"prɪˈper",p:"v",vn:"chuẩn bị",ex:"I'll prepare a demo for Friday."},
 {t:"report",ipa:"rɪˈpɔːrt",p:"v",vn:"báo cáo",ex:"She reports to me every Monday."},
 {t:"contact",ipa:"ˈkɑːntækt",p:"v",vn:"liên hệ",ex:"Please contact me if you have questions."},
 {t:"train",ipa:"treɪn",p:"v",vn:"đào tạo, huấn luyện",ex:"We train your staff in two sessions."},
 {t:"hire",ipa:"haɪr",p:"v",vn:"tuyển, thuê",ex:"We need to hire two more people."},
 {t:"promote",ipa:"prəˈmoʊt",p:"v",vn:"thăng chức; quảng bá",ex:"I want to promote her to team lead."},
 {t:"join",ipa:"dʒɔɪn",p:"v",vn:"tham gia",ex:"I'll join your demo with the client."},
 {t:"close",ipa:"kloʊz",p:"v",vn:"chốt (deal); đóng",ex:"He closed two deals this month."},
 {t:"increase",ipa:"ɪnˈkriːs",p:"v",vn:"tăng",ex:"We want to increase revenue by 20%.",tip:"Danh từ đọc IN-crease, động từ in-CREASE."},
 {t:"reduce",ipa:"rɪˈduːs",p:"v",vn:"giảm",ex:"This reduces your inventory costs."},
 {t:"save",ipa:"seɪv",p:"v",vn:"tiết kiệm; lưu",ex:"It saves you two hours a day."},
 {t:"spend",ipa:"spend",p:"v",vn:"tiêu (tiền), dành (thời gian)",ex:"How much do you spend on software now?"},
 {t:"earn",ipa:"ɜːrn",p:"v",vn:"kiếm được",ex:"The shop earns more during peak hours."},
 {t:"charge",ipa:"tʃɑːrdʒ",p:"v",vn:"tính phí; sạc",ex:"We charge a monthly fee per outlet."},
 {t:"book",ipa:"bʊk",p:"v",vn:"đặt (chỗ, lịch)",ex:"I'd like to book a demo for Monday."},
 {t:"cancel",ipa:"ˈkænsəl",p:"v",vn:"hủy",ex:"You can cancel anytime in the first month."},
 {t:"change",ipa:"tʃeɪndʒ",p:"v",vn:"thay đổi",ex:"Has your job changed since you started?"},
 {t:"improve",ipa:"ɪmˈpruːv",p:"v",vn:"cải thiện",ex:"I want to improve my English."},
 {t:"solve",ipa:"sɑːlv",p:"v",vn:"giải quyết",ex:"Our system solves the paper problem."},
 {t:"handle",ipa:"ˈhændl̩",p:"v",vn:"xử lý, đảm nhận",ex:"Can your staff handle the tablet?"},
 {t:"provide",ipa:"prəˈvaɪd",p:"v",vn:"cung cấp",ex:"We provide software for cafés."},
 {t:"suggest",ipa:"səˈdʒest",p:"v",vn:"đề xuất, gợi ý",ex:"I suggest we start with two outlets."},
 {t:"recommend",ipa:"ˌrekəˈmend",p:"v",vn:"khuyên dùng",ex:"I recommend the yearly plan."},
 {t:"compare",ipa:"kəmˈper",p:"v",vn:"so sánh",ex:"Expensive compared to what?"},
 {t:"choose",ipa:"tʃuːz",p:"v",vn:"chọn",ex:"You can choose the modules you need."},
 {t:"accept",ipa:"əkˈsept",p:"v",vn:"chấp nhận",ex:"Do you accept these terms?"},
 {t:"refuse",ipa:"rɪˈfjuːz",p:"v",vn:"từ chối",ex:"He refused the first offer."},
 {t:"complain",ipa:"kəmˈpleɪn",p:"v",vn:"phàn nàn",ex:"Customers complain about slow service."},
 {t:"apologize",ipa:"əˈpɑːlədʒaɪz",p:"v",vn:"xin lỗi",ex:"I apologize for the delay."},
 {t:"remind",ipa:"rɪˈmaɪnd",p:"v",vn:"nhắc",ex:"Please remind me before Friday."},
 {t:"schedule",ipa:"ˈskedʒuːl",p:"v",vn:"lên lịch",ex:"Let's schedule the go-live.",tip:"Anh đọc SHED-yool, Mỹ đọc SKE-jool."},
 {t:"negotiate",ipa:"nɪˈɡoʊʃieɪt",p:"v",vn:"đàm phán",ex:"We can negotiate the price."},
 {t:"cooperate",ipa:"koʊˈɑːpəreɪt",p:"v",vn:"hợp tác",ex:"Both teams cooperate on the setup."}
]},
{id:"self-family",title:"Bản thân & gia đình",icon:"i-users",c:"noi",words:[
 {t:"name",ipa:"neɪm",p:"n",vn:"tên",ex:"My name is Thuy."},
 {t:"age",ipa:"eɪdʒ",p:"n",vn:"tuổi",ex:"People of all ages use our app."},
 {t:"job",ipa:"dʒɑːb",p:"n",vn:"công việc",ex:"I really enjoy my job."},
 {t:"hometown",ipa:"ˈhoʊmtaʊn",p:"n",vn:"quê nhà",ex:"My hometown is a small town in the north."},
 {t:"family",ipa:"ˈfæməli",p:"n",vn:"gia đình",ex:"I have a small family."},
 {t:"parents",ipa:"ˈperənts",p:"n",vn:"bố mẹ",ex:"My parents live in the countryside."},
 {t:"mother",ipa:"ˈmʌðər",p:"n",vn:"mẹ",ex:"My mother is a teacher."},
 {t:"father",ipa:"ˈfɑːðər",p:"n",vn:"bố",ex:"My father ran a small shop."},
 {t:"brother",ipa:"ˈbrʌðər",p:"n",vn:"anh/em trai",ex:"My brother works in marketing."},
 {t:"sister",ipa:"ˈsɪstər",p:"n",vn:"chị/em gái",ex:"I have one older sister."},
 {t:"siblings",ipa:"ˈsɪblɪŋz",p:"n",vn:"anh chị em ruột",ex:"I have two siblings."},
 {t:"son",ipa:"sʌn",p:"n",vn:"con trai",ex:"They have a son and a daughter."},
 {t:"daughter",ipa:"ˈdɔːtər",p:"n",vn:"con gái",ex:"My daughter is five years old."},
 {t:"child",ipa:"tʃaɪld",p:"n",vn:"đứa trẻ",ex:"Every child in the family speaks English."},
 {t:"kids",ipa:"kɪdz",p:"n",vn:"bọn trẻ (thân mật)",ex:"The café is popular with families and kids."},
 {t:"wife",ipa:"waɪf",p:"n",vn:"vợ",ex:"My wife also works in sales."},
 {t:"husband",ipa:"ˈhʌzbənd",p:"n",vn:"chồng",ex:"Her husband owns two restaurants."},
 {t:"married",ipa:"ˈmerid",p:"adj",vn:"đã kết hôn",ex:"I'm married with one child."},
 {t:"single",ipa:"ˈsɪŋɡl̩",p:"adj",vn:"độc thân; đơn lẻ",ex:"He is single and lives alone."},
 {t:"cousin",ipa:"ˈkʌzn̩",p:"n",vn:"anh/chị/em họ",ex:"My cousin helped me start the business.",tip:"Đọc KU-zần, s như /z/."},
 {t:"uncle",ipa:"ˈʌŋkl̩",p:"n",vn:"chú/bác/cậu",ex:"My uncle owns a coffee farm."},
 {t:"aunt",ipa:"ænt",p:"n",vn:"cô/dì/bác gái",ex:"My aunt lives near my office."},
 {t:"grandparents",ipa:"ˈɡrænperənts",p:"n",vn:"ông bà",ex:"My grandparents live in Hue."},
 {t:"grandmother",ipa:"ˈɡrænmʌðər",p:"n",vn:"bà",ex:"My grandmother cooks very well."},
 {t:"grandfather",ipa:"ˈɡrænfɑːðər",p:"n",vn:"ông",ex:"My grandfather taught me to work hard."},
 {t:"friend",ipa:"frend",p:"n",vn:"bạn",ex:"A friend introduced me to this client."},
 {t:"neighbor",ipa:"ˈneɪbər",p:"n",vn:"hàng xóm",ex:"My neighbor runs a small bakery."},
 {t:"boss",ipa:"bɔːs",p:"n",vn:"sếp",ex:"Let me check with my boss."},
 {t:"colleague",ipa:"ˈkɑːliːɡ",p:"n",vn:"đồng nghiệp",ex:"My colleague will join the call."},
 {t:"team",ipa:"tiːm",p:"n",vn:"đội, nhóm",ex:"I lead a team of five."},
 {t:"hobby",ipa:"ˈhɑːbi",p:"n",vn:"sở thích",ex:"My hobby is cycling on weekends."},
 {t:"weekend",ipa:"ˈwiːkend",p:"n",vn:"cuối tuần",ex:"I take an English class every weekend."},
 {t:"birthday",ipa:"ˈbɜːrθdeɪ",p:"n",vn:"sinh nhật",ex:"We give customers a gift on their birthday."},
 {t:"health",ipa:"helθ",p:"n",vn:"sức khỏe",ex:"Good sleep is important for your health."},
 {t:"tall",ipa:"tɔːl",p:"adj",vn:"cao",ex:"He is tall and easy to notice."},
 {t:"short",ipa:"ʃɔːrt",p:"adj",vn:"thấp; ngắn",ex:"Let's keep the meeting short."},
 {t:"young",ipa:"jʌŋ",p:"adj",vn:"trẻ",ex:"Most of my team are young."},
 {t:"old",ipa:"oʊld",p:"adj",vn:"già; cũ",ex:"Their old system is very slow."},
 {t:"kind",ipa:"kaɪnd",p:"adj",vn:"tử tế",ex:"She is kind to every customer."},
 {t:"friendly",ipa:"ˈfrendli",p:"adj",vn:"thân thiện",ex:"Our staff are friendly and helpful."},
 {t:"honest",ipa:"ˈɑːnɪst",p:"adj",vn:"trung thực",ex:"To be honest, I'm not sure.",tip:"H câm: đọc ON-ist."},
 {t:"patient",ipa:"ˈpeɪʃnt",p:"adj",vn:"kiên nhẫn",ex:"You must be patient with new staff."},
 {t:"confident",ipa:"ˈkɑːnfɪdənt",p:"adj",vn:"tự tin",ex:"I feel confident about this deal."},
 {t:"shy",ipa:"ʃaɪ",p:"adj",vn:"nhút nhát",ex:"I was shy when I started selling."},
 {t:"funny",ipa:"ˈfʌni",p:"adj",vn:"vui, hài hước",ex:"He is funny and easy to talk to."},
 {t:"smart",ipa:"smɑːrt",p:"adj",vn:"thông minh",ex:"She is smart and learns fast."},
 {t:"hard-working",ipa:"ˌhɑːrdˈwɜːrkɪŋ",p:"adj",vn:"chăm chỉ",ex:"My team is young but hard-working."},
 {t:"generous",ipa:"ˈdʒenərəs",p:"adj",vn:"hào phóng",ex:"He is generous with tips."},
 {t:"polite",ipa:"pəˈlaɪt",p:"adj",vn:"lịch sự",ex:"Always be polite on the phone."},
 {t:"calm",ipa:"kɑːm",p:"adj",vn:"bình tĩnh",ex:"Stay calm when a customer complains.",tip:"L câm: đọc KAAM."}
]},
{id:"home-things",title:"Nhà ở & đồ vật hằng ngày",icon:"i-book",c:"viet",words:[
 {t:"house",ipa:"haʊs",p:"n",vn:"nhà",ex:"I live in a house with my family."},
 {t:"apartment",ipa:"əˈpɑːrtmənt",p:"n",vn:"căn hộ",ex:"I live in a small apartment downtown."},
 {t:"room",ipa:"ruːm",p:"n",vn:"phòng",ex:"The meeting room is on the third floor."},
 {t:"kitchen",ipa:"ˈkɪtʃən",p:"n",vn:"bếp",ex:"The kitchen sees the order immediately."},
 {t:"bedroom",ipa:"ˈbedruːm",p:"n",vn:"phòng ngủ",ex:"My bedroom is also my home office."},
 {t:"bathroom",ipa:"ˈbæθruːm",p:"n",vn:"phòng tắm/vệ sinh",ex:"The restaurant has a clean bathroom."},
 {t:"door",ipa:"dɔːr",p:"n",vn:"cửa",ex:"The waiter stands near the door."},
 {t:"window",ipa:"ˈwɪndoʊ",p:"n",vn:"cửa sổ",ex:"I like a table by the window."},
 {t:"table",ipa:"ˈteɪbl̩",p:"n",vn:"bàn",ex:"We manage every table from one screen."},
 {t:"chair",ipa:"tʃer",p:"n",vn:"ghế",ex:"Please have a chair."},
 {t:"bed",ipa:"bed",p:"n",vn:"giường",ex:"Get out of bed and speak English."},
 {t:"desk",ipa:"desk",p:"n",vn:"bàn làm việc",ex:"My desk is always full of papers."},
 {t:"phone",ipa:"foʊn",p:"n",vn:"điện thoại",ex:"The owner checks revenue on his phone."},
 {t:"laptop",ipa:"ˈlæptɑːp",p:"n",vn:"máy tính xách tay",ex:"Bring your laptop to the demo."},
 {t:"computer",ipa:"kəmˈpjuːtər",p:"n",vn:"máy tính",ex:"People or computers — which is better?"},
 {t:"key",ipa:"kiː",p:"n",vn:"chìa khóa; then chốt",ex:"Listening is the key skill in sales."},
 {t:"bag",ipa:"bæɡ",p:"n",vn:"túi, cặp",ex:"I keep a tablet in my bag."},
 {t:"wallet",ipa:"ˈwɑːlɪt",p:"n",vn:"ví",ex:"Now people pay without a wallet."},
 {t:"clock",ipa:"klɑːk",p:"n",vn:"đồng hồ (treo)",ex:"There's a clock above the counter."},
 {t:"light",ipa:"laɪt",p:"n",vn:"đèn; ánh sáng",ex:"Turn off the lights after closing."},
 {t:"water",ipa:"ˈwɔːtər",p:"n",vn:"nước",ex:"Can I get you some water?"},
 {t:"food",ipa:"fuːd",p:"n",vn:"đồ ăn",ex:"The food comes out faster with the KDS."},
 {t:"coffee",ipa:"ˈkɔːfi",p:"n",vn:"cà phê",ex:"We sell software to coffee chains."},
 {t:"tea",ipa:"tiː",p:"n",vn:"trà",ex:"Would you like tea or coffee?"},
 {t:"car",ipa:"kɑːr",p:"n",vn:"ô tô",ex:"I go to clients by car."},
 {t:"motorbike",ipa:"ˈmoʊtərbaɪk",p:"n",vn:"xe máy",ex:"Most staff come to work by motorbike."},
 {t:"street",ipa:"striːt",p:"n",vn:"đường phố",ex:"There are many cafés on this street."},
 {t:"city",ipa:"ˈsɪti",p:"n",vn:"thành phố",ex:"We work in every big city in Vietnam."},
 {t:"district",ipa:"ˈdɪstrɪkt",p:"n",vn:"quận",ex:"The coffee chain is in District 3."},
 {t:"building",ipa:"ˈbɪldɪŋ",p:"n",vn:"tòa nhà",ex:"Our office is in that building."},
 {t:"floor",ipa:"flɔːr",p:"n",vn:"tầng; sàn",ex:"The demo is on the fifth floor."},
 {t:"wall",ipa:"wɔːl",p:"n",vn:"tường",ex:"The menu is on the wall."},
 {t:"clothes",ipa:"kloʊðz",p:"n",vn:"quần áo",ex:"Staff wear clean clothes on shift.",tip:"Đọc gọn KLOHZ."},
 {t:"shoes",ipa:"ʃuːz",p:"n",vn:"giày",ex:"Wear comfortable shoes for a long shift."},
 {t:"watch",ipa:"wɑːtʃ",p:"n",vn:"đồng hồ đeo tay",ex:"He looked at his watch and left."},
 {t:"glasses",ipa:"ˈɡlæsɪz",p:"n",vn:"kính (mắt)",ex:"I wear glasses when I read."},
 {t:"umbrella",ipa:"ʌmˈbrelə",p:"n",vn:"ô, dù",ex:"We give umbrellas to loyal customers."},
 {t:"fridge",ipa:"frɪdʒ",p:"n",vn:"tủ lạnh",ex:"The drinks are in the fridge."},
 {t:"fan",ipa:"fæn",p:"n",vn:"quạt",ex:"Turn on the fan, it's hot."},
 {t:"air conditioner",ipa:"ˈer kənˌdɪʃənər",p:"n",vn:"máy lạnh",ex:"The café has a strong air conditioner."},
 {t:"television",ipa:"ˈteləvɪʒn̩",p:"n",vn:"tivi",ex:"There's a television in the waiting area."},
 {t:"remote",ipa:"rɪˈmoʊt",p:"n",vn:"điều khiển từ xa; từ xa",ex:"We can fix it by remote."},
 {t:"charger",ipa:"ˈtʃɑːrdʒər",p:"n",vn:"bộ sạc",ex:"Don't forget your charger."},
 {t:"internet",ipa:"ˈɪntərnet",p:"n",vn:"mạng internet",ex:"If the internet is down, you can still sell."},
 {t:"wifi",ipa:"ˈwaɪfaɪ",p:"n",vn:"wifi",ex:"We offer free wifi for guests."},
 {t:"battery",ipa:"ˈbætəri",p:"n",vn:"pin",ex:"The tablet battery lasts all day."},
 {t:"screen",ipa:"skriːn",p:"n",vn:"màn hình",ex:"The kitchen sees the order on a screen."},
 {t:"button",ipa:"ˈbʌtn̩",p:"n",vn:"nút bấm",ex:"Press this button to print the bill."},
 {t:"drawer",ipa:"drɔːr",p:"n",vn:"ngăn kéo",ex:"The cash is in the drawer."},
 {t:"shelf",ipa:"ʃelf",p:"n",vn:"kệ, giá",ex:"We track every item on the shelf."}
]},
{id:"office-tech",title:"Văn phòng & phần mềm",icon:"i-file",c:"doc",words:[
 {t:"client",ipa:"ˈklaɪənt",p:"n",vn:"khách hàng (doanh nghiệp)",ex:"I'll join your demo with the client."},
 {t:"customer",ipa:"ˈkʌstəmər",p:"n",vn:"khách hàng",ex:"The customer is always in a hurry."},
 {t:"meeting",ipa:"ˈmiːtɪŋ",p:"n",vn:"cuộc họp",ex:"Let's set up a meeting for Monday."},
 {t:"deadline",ipa:"ˈdedlaɪn",p:"n",vn:"hạn chót",ex:"Please update the pipeline before the deadline."},
 {t:"project",ipa:"ˈprɑːdʒekt",p:"n",vn:"dự án",ex:"This project has three phases."},
 {t:"task",ipa:"tæsk",p:"n",vn:"nhiệm vụ, việc",ex:"Each person has a clear task."},
 {t:"email",ipa:"ˈiːmeɪl",p:"n",vn:"thư điện tử",ex:"I'll send you the details by email."},
 {t:"file",ipa:"faɪl",p:"n",vn:"tệp, hồ sơ",ex:"The file is too big to send."},
 {t:"folder",ipa:"ˈfoʊldər",p:"n",vn:"thư mục",ex:"Keep the contracts in one folder."},
 {t:"document",ipa:"ˈdɑːkjumənt",p:"n",vn:"tài liệu",ex:"I attached the document to the email."},
 {t:"data",ipa:"ˈdeɪtə",p:"n",vn:"dữ liệu",ex:"All your data is safe in the cloud."},
 {t:"app",ipa:"æp",p:"n",vn:"ứng dụng",ex:"The owner opens the app on his phone."},
 {t:"software",ipa:"ˈsɔːftwer",p:"n",vn:"phần mềm",ex:"We provide software for restaurants."},
 {t:"hardware",ipa:"ˈhɑːrdwer",p:"n",vn:"phần cứng",ex:"The hardware includes a tablet and a printer."},
 {t:"system",ipa:"ˈsɪstəm",p:"n",vn:"hệ thống",ex:"What system are you using now?"},
 {t:"account",ipa:"əˈkaʊnt",p:"n",vn:"tài khoản",ex:"We create an account for each outlet."},
 {t:"password",ipa:"ˈpæswɜːrd",p:"n",vn:"mật khẩu",ex:"Please change your password every month."},
 {t:"login",ipa:"ˈlɔːɡɪn",p:"n",vn:"đăng nhập",ex:"Each staff has their own login."},
 {t:"dashboard",ipa:"ˈdæʃbɔːrd",p:"n",vn:"bảng điều khiển",ex:"The dashboard shows revenue by branch."},
 {t:"feature",ipa:"ˈfiːtʃər",p:"n",vn:"tính năng",ex:"Last month we launched a new feature."},
 {t:"version",ipa:"ˈvɜːrʒn̩",p:"n",vn:"phiên bản",ex:"The new version is faster."},
 {t:"bug",ipa:"bʌɡ",p:"n",vn:"lỗi phần mềm",ex:"We fixed the bug this morning."},
 {t:"issue",ipa:"ˈɪʃuː",p:"n",vn:"vấn đề, sự cố",ex:"If you have any issue, tell me."},
 {t:"error",ipa:"ˈerər",p:"n",vn:"lỗi",ex:"The screen showed an error."},
 {t:"cloud",ipa:"klaʊd",p:"n",vn:"đám mây",ex:"The data is stored in the cloud."},
 {t:"server",ipa:"ˈsɜːrvər",p:"n",vn:"máy chủ",ex:"The server was down for a minute."},
 {t:"database",ipa:"ˈdeɪtəbeɪs",p:"n",vn:"cơ sở dữ liệu",ex:"All orders go into one database."},
 {t:"backup",ipa:"ˈbækʌp",p:"n",vn:"bản sao lưu",ex:"We make a backup every night."},
 {t:"device",ipa:"dɪˈvaɪs",p:"n",vn:"thiết bị",ex:"It works on any device."},
 {t:"tablet",ipa:"ˈtæblət",p:"n",vn:"máy tính bảng",ex:"The waiter takes the order on a tablet."},
 {t:"user",ipa:"ˈjuːzər",p:"n",vn:"người dùng",ex:"How many users will you have?"},
 {t:"setting",ipa:"ˈsetɪŋ",p:"n",vn:"cài đặt, thiết lập",ex:"You can change the tax in the settings."},
 {t:"sync",ipa:"sɪŋk",p:"v",vn:"đồng bộ",ex:"Orders sync to the cloud in real time."},
 {t:"deploy",ipa:"dɪˈplɔɪ",p:"v",vn:"triển khai",ex:"We deploy the update overnight."},
 {t:"notification",ipa:"ˌnoʊtɪfɪˈkeɪʃn̩",p:"n",vn:"thông báo",ex:"The kitchen gets a notification for each order."},
 {t:"message",ipa:"ˈmesɪdʒ",p:"n",vn:"tin nhắn",ex:"I'll send you a message when it's ready."},
 {t:"link",ipa:"lɪŋk",p:"n",vn:"đường liên kết",ex:"I'll send you the link to the demo."},
 {t:"download",ipa:"ˈdaʊnloʊd",p:"v",vn:"tải xuống",ex:"You can download the report as a PDF."},
 {t:"upload",ipa:"ˈʌploʊd",p:"v",vn:"tải lên",ex:"Upload your menu photos here."},
 {t:"printer",ipa:"ˈprɪntər",p:"n",vn:"máy in",ex:"The bill goes straight to the printer."},
 {t:"network",ipa:"ˈnetwɜːrk",p:"n",vn:"mạng lưới",ex:"A weak network slows everything down."},
 {t:"security",ipa:"sɪˈkjʊrəti",p:"n",vn:"bảo mật, an ninh",ex:"Security is very important for payments."},
 {t:"access",ipa:"ˈækses",p:"n",vn:"quyền truy cập",ex:"The manager has full access."},
 {t:"permission",ipa:"pərˈmɪʃn̩",p:"n",vn:"quyền, sự cho phép",ex:"Staff need permission to give a discount."},
 {t:"spreadsheet",ipa:"ˈspredʃiːt",p:"n",vn:"bảng tính",ex:"I used to track sales in a spreadsheet."},
 {t:"chart",ipa:"tʃɑːrt",p:"n",vn:"biểu đồ",ex:"The chart shows sales going up."},
 {t:"presentation",ipa:"ˌpriːzenˈteɪʃn̩",p:"n",vn:"bài thuyết trình",ex:"I'll prepare a short presentation."},
 {t:"reminder",ipa:"rɪˈmaɪndər",p:"n",vn:"lời nhắc",ex:"Set a reminder for the follow-up call."},
 {t:"workflow",ipa:"ˈwɜːrkfloʊ",p:"n",vn:"quy trình làm việc",ex:"Our system fits your daily workflow."},
 {t:"attachment",ipa:"əˈtætʃmənt",p:"n",vn:"tệp đính kèm",ex:"The quote is in the attachment."}
]},
{id:"fnb",title:"Ngành F&B: nhà hàng & cà phê",icon:"i-book",c:"damphan",words:[
 {t:"restaurant",ipa:"ˈrestərɑːnt",p:"n",vn:"nhà hàng",ex:"We work with restaurants of all sizes."},
 {t:"café",ipa:"kæˈfeɪ",p:"n",vn:"quán cà phê",ex:"This café has twenty branches."},
 {t:"waiter",ipa:"ˈweɪtər",p:"n",vn:"phục vụ nam",ex:"The waiter takes the order on a tablet."},
 {t:"waitress",ipa:"ˈweɪtrəs",p:"n",vn:"phục vụ nữ",ex:"The waitress brings the bill to the table."},
 {t:"chef",ipa:"ʃef",p:"n",vn:"đầu bếp chính",ex:"The chef sees the order on the screen."},
 {t:"cook",ipa:"kʊk",p:"n",vn:"đầu bếp; nấu",ex:"The cook prepares the dish quickly."},
 {t:"guest",ipa:"ɡest",p:"n",vn:"khách (đến ăn)",ex:"We seat the guest by the window."},
 {t:"bill",ipa:"bɪl",p:"n",vn:"hóa đơn (tính tiền)",ex:"Can I have the bill, please?"},
 {t:"tip",ipa:"tɪp",p:"n",vn:"tiền boa; mẹo",ex:"He left a big tip."},
 {t:"dish",ipa:"dɪʃ",p:"n",vn:"món ăn",ex:"This dish is our best seller."},
 {t:"drink",ipa:"drɪŋk",p:"n",vn:"đồ uống",ex:"Would you like a drink first?"},
 {t:"meal",ipa:"miːl",p:"n",vn:"bữa ăn",ex:"A full meal takes about thirty minutes."},
 {t:"breakfast",ipa:"ˈbrekfəst",p:"n",vn:"bữa sáng",ex:"We serve breakfast from seven."},
 {t:"lunch",ipa:"lʌntʃ",p:"n",vn:"bữa trưa",ex:"Lunch is our peak hour."},
 {t:"dinner",ipa:"ˈdɪnər",p:"n",vn:"bữa tối",ex:"Let's continue after dinner."},
 {t:"espresso",ipa:"eˈspresoʊ",p:"n",vn:"cà phê espresso",ex:"One espresso, please."},
 {t:"latte",ipa:"ˈlɑːteɪ",p:"n",vn:"cà phê latte",ex:"A latte is their most popular drink."},
 {t:"cappuccino",ipa:"ˌkæpəˈtʃiːnoʊ",p:"n",vn:"cà phê cappuccino",ex:"She ordered a cappuccino."},
 {t:"juice",ipa:"dʒuːs",p:"n",vn:"nước ép",ex:"Fresh orange juice is on the menu."},
 {t:"smoothie",ipa:"ˈsmuːði",p:"n",vn:"sinh tố",ex:"Their mango smoothie sells well."},
 {t:"ice",ipa:"aɪs",p:"n",vn:"đá",ex:"Would you like ice with that?"},
 {t:"sugar",ipa:"ˈʃʊɡər",p:"n",vn:"đường",ex:"No sugar in my coffee, please."},
 {t:"milk",ipa:"mɪlk",p:"n",vn:"sữa",ex:"We ran out of milk this morning."},
 {t:"bread",ipa:"bred",p:"n",vn:"bánh mì",ex:"The bread is baked fresh every day."},
 {t:"cake",ipa:"keɪk",p:"n",vn:"bánh ngọt",ex:"A slice of cake goes with the coffee."},
 {t:"rice",ipa:"raɪs",p:"n",vn:"cơm, gạo",ex:"Rice comes with every main dish."},
 {t:"noodle",ipa:"ˈnuːdl̩",p:"n",vn:"mì, bún",ex:"Their noodle soup is famous."},
 {t:"soup",ipa:"suːp",p:"n",vn:"súp, canh",ex:"The soup of the day is pumpkin."},
 {t:"sauce",ipa:"sɔːs",p:"n",vn:"nước sốt",ex:"Each dish has its own sauce."},
 {t:"spicy",ipa:"ˈspaɪsi",p:"adj",vn:"cay",ex:"Is this dish spicy?"},
 {t:"sweet",ipa:"swiːt",p:"adj",vn:"ngọt",ex:"The dessert is very sweet."},
 {t:"fresh",ipa:"freʃ",p:"adj",vn:"tươi, mới",ex:"We use fresh ingredients only."},
 {t:"delicious",ipa:"dɪˈlɪʃəs",p:"adj",vn:"ngon",ex:"The food here is delicious."},
 {t:"serve",ipa:"sɜːrv",p:"v",vn:"phục vụ",ex:"We serve about 200 guests a day."},
 {t:"portion",ipa:"ˈpɔːrʃn̩",p:"n",vn:"khẩu phần",ex:"The portion is large for the price."},
 {t:"reservation",ipa:"ˌrezərˈveɪʃn̩",p:"n",vn:"đặt chỗ trước",ex:"Do you have a reservation?"},
 {t:"booking",ipa:"ˈbʊkɪŋ",p:"n",vn:"lượt đặt",ex:"The system manages every booking."},
 {t:"takeaway",ipa:"ˈteɪkəweɪ",p:"n",vn:"mang đi",ex:"Is this for takeaway or dine-in?"},
 {t:"delivery",ipa:"dɪˈlɪvəri",p:"n",vn:"giao hàng",ex:"We connect to every delivery app."},
 {t:"counter",ipa:"ˈkaʊntər",p:"n",vn:"quầy",ex:"Please pay at the counter."},
 {t:"cashier",ipa:"kæˈʃɪr",p:"n",vn:"thu ngân",ex:"The cashier uses the POS all day."},
 {t:"shift",ipa:"ʃɪft",p:"n",vn:"ca làm",ex:"She works the morning shift."},
 {t:"recipe",ipa:"ˈresəpi",p:"n",vn:"công thức nấu",ex:"Every drink has a fixed recipe.",tip:"Đọc RE-sồ-pi, không đọc như 'receipt'."},
 {t:"ingredient",ipa:"ɪnˈɡriːdiənt",p:"n",vn:"nguyên liệu",ex:"We track every ingredient in stock."},
 {t:"napkin",ipa:"ˈnæpkɪn",p:"n",vn:"khăn giấy",ex:"Put a napkin with every order."},
 {t:"tray",ipa:"treɪ",p:"n",vn:"khay",ex:"The waiter carries drinks on a tray."},
 {t:"menu",ipa:"ˈmenjuː",p:"n",vn:"thực đơn",ex:"Can I see the menu, please?"},
 {t:"snack",ipa:"snæk",p:"n",vn:"đồ ăn nhẹ",ex:"We also sell light snacks."},
 {t:"dessert",ipa:"dɪˈzɜːrt",p:"n",vn:"món tráng miệng",ex:"Would you like a dessert?",tip:"Nhấn âm 2: đi-ZỜT."},
 {t:"peak hours",ipa:"ˌpiːk ˈaʊərz",p:"phr",vn:"giờ cao điểm",ex:"The system is fast even in peak hours."}
]},
{id:"sales",title:"Bán hàng & đàm phán",icon:"i-scale",c:"damphan",words:[
 {t:"sale",ipa:"seɪl",p:"n",vn:"việc bán hàng, doanh số",ex:"We had a good month for sales."},
 {t:"proposal",ipa:"prəˈpoʊzl̩",p:"n",vn:"đề xuất, bản chào",ex:"I'll send you a full proposal."},
 {t:"benefit",ipa:"ˈbenɪfɪt",p:"n",vn:"lợi ích",ex:"The main benefit is saving time."},
 {t:"value",ipa:"ˈvæljuː",p:"n",vn:"giá trị",ex:"The software pays for itself in value."},
 {t:"solution",ipa:"səˈluːʃn̩",p:"n",vn:"giải pháp",ex:"We offer a complete solution."},
 {t:"problem",ipa:"ˈprɑːbləm",p:"n",vn:"vấn đề",ex:"What is the biggest problem with it?"},
 {t:"goal",ipa:"ɡoʊl",p:"n",vn:"mục tiêu",ex:"Our goal is fifteen new leads."},
 {t:"result",ipa:"rɪˈzʌlt",p:"n",vn:"kết quả",ex:"The results were better than last month."},
 {t:"commission",ipa:"kəˈmɪʃn̩",p:"n",vn:"tiền hoa hồng",ex:"The team earns a commission on each deal."},
 {t:"profit",ipa:"ˈprɑːfɪt",p:"n",vn:"lợi nhuận",ex:"Small savings become real profit."},
 {t:"margin",ipa:"ˈmɑːrdʒɪn",p:"n",vn:"biên lợi nhuận",ex:"F&B margins are usually thin."},
 {t:"competitor",ipa:"kəmˈpetɪtər",p:"n",vn:"đối thủ",ex:"I know that competitor well."},
 {t:"market",ipa:"ˈmɑːrkɪt",p:"n",vn:"thị trường",ex:"The F&B market is growing fast."},
 {t:"brand",ipa:"brænd",p:"n",vn:"thương hiệu",ex:"They want to grow the brand."},
 {t:"product",ipa:"ˈprɑːdʌkt",p:"n",vn:"sản phẩm",ex:"You can't sell a product you can't name."},
 {t:"service",ipa:"ˈsɜːrvɪs",p:"n",vn:"dịch vụ",ex:"The monthly fee includes support and service."},
 {t:"quality",ipa:"ˈkwɑːləti",p:"n",vn:"chất lượng",ex:"Quality matters more than price here."},
 {t:"guarantee",ipa:"ˌɡærənˈtiː",p:"n",vn:"sự bảo đảm",ex:"We guarantee support within 24 hours."},
 {t:"warranty",ipa:"ˈwɔːrənti",p:"n",vn:"bảo hành",ex:"The hardware has a one-year warranty."},
 {t:"refund",ipa:"ˈriːfʌnd",p:"n",vn:"hoàn tiền",ex:"We offer a refund in the first week."},
 {t:"invoice",ipa:"ˈɪnvɔɪs",p:"n",vn:"hóa đơn (thanh toán)",ex:"I'll send the invoice by email."},
 {t:"installment",ipa:"ɪnˈstɔːlmənt",p:"n",vn:"trả góp",ex:"You can pay in monthly installments."},
 {t:"negotiation",ipa:"nɪˌɡoʊʃiˈeɪʃn̩",p:"n",vn:"cuộc đàm phán",ex:"The negotiation went well."},
 {t:"objection",ipa:"əbˈdʒekʃn̩",p:"n",vn:"lời phản đối",ex:"The most common objection is price."},
 {t:"agreement",ipa:"əˈɡriːmənt",p:"n",vn:"thỏa thuận",ex:"Let me confirm our agreement."},
 {t:"term",ipa:"tɜːrm",p:"n",vn:"điều khoản; kỳ hạn",ex:"We agree on the payment terms."},
 {t:"condition",ipa:"kənˈdɪʃn̩",p:"n",vn:"điều kiện",ex:"There is one condition for the discount."},
 {t:"opportunity",ipa:"ˌɑːpərˈtuːnəti",p:"n",vn:"cơ hội",ex:"This is a good opportunity for both of us."},
 {t:"decision",ipa:"dɪˈsɪʒn̩",p:"n",vn:"quyết định",ex:"When will you make a decision?"},
 {t:"approve",ipa:"əˈpruːv",p:"v",vn:"phê duyệt",ex:"My manager has to approve the discount."},
 {t:"reject",ipa:"rɪˈdʒekt",p:"v",vn:"từ chối, bác",ex:"They rejected the first price."},
 {t:"commitment",ipa:"kəˈmɪtmənt",p:"n",vn:"cam kết",ex:"A two-year commitment lowers the price."},
 {t:"partner",ipa:"ˈpɑːrtnər",p:"n",vn:"đối tác",ex:"We see you as a long-term partner."},
 {t:"relationship",ipa:"rɪˈleɪʃnʃɪp",p:"n",vn:"mối quan hệ",ex:"Sales is about building a relationship."},
 {t:"trust",ipa:"trʌst",p:"n",vn:"sự tin tưởng",ex:"Trust comes before any big deal."},
 {t:"loyal",ipa:"ˈlɔɪəl",p:"adj",vn:"trung thành",ex:"Loyal customers get a discount."},
 {t:"referral",ipa:"rɪˈfɜːrəl",p:"n",vn:"lời giới thiệu (khách)",ex:"Most new clients come from referrals."},
 {t:"upsell",ipa:"ˈʌpsel",p:"v",vn:"bán thêm gói cao hơn",ex:"We upsell the inventory module later."},
 {t:"advantage",ipa:"ədˈvæntɪdʒ",p:"n",vn:"lợi thế",ex:"Working offline is a big advantage."},
 {t:"risk",ipa:"rɪsk",p:"n",vn:"rủi ro",ex:"There's no risk in a free trial."},
 {t:"win",ipa:"wɪn",p:"v",vn:"thắng, giành được",ex:"We want a win-win deal."},
 {t:"convince",ipa:"kənˈvɪns",p:"v",vn:"thuyết phục",ex:"The demo convinced the owner."},
 {t:"persuade",ipa:"pərˈsweɪd",p:"v",vn:"thuyết phục",ex:"Don't push; persuade with numbers."},
 {t:"pitch",ipa:"pɪtʃ",p:"n",vn:"bài chào hàng",ex:"My pitch takes about 60 seconds."},
 {t:"prospect",ipa:"ˈprɑːspekt",p:"n",vn:"khách hàng tiềm năng",ex:"I have three hot prospects this week."},
 {t:"offer",ipa:"ˈɔːfər",p:"n",vn:"lời đề nghị/chào giá",ex:"That's my best offer."},
 {t:"bargain",ipa:"ˈbɑːrɡɪn",p:"n",vn:"món hời; mặc cả",ex:"At this price, it's a bargain."},
 {t:"incentive",ipa:"ɪnˈsentɪv",p:"n",vn:"động lực, ưu đãi",ex:"We give an incentive for signing early."},
 {t:"reference",ipa:"ˈrefrəns",p:"n",vn:"khách tham chiếu",ex:"I can give you a reference to call."},
 {t:"turnover",ipa:"ˈtɜːrnoʊvər",p:"n",vn:"doanh thu; tỉ lệ nghỉ việc",ex:"High staff turnover is a real cost."}
]},
{id:"money-time",title:"Tiền, số & thời gian",icon:"i-cal",c:"viet",words:[
 {t:"money",ipa:"ˈmʌni",p:"n",vn:"tiền",ex:"How much money do you lose each month?"},
 {t:"cash",ipa:"kæʃ",p:"n",vn:"tiền mặt",ex:"Some guests still pay in cash."},
 {t:"card",ipa:"kɑːrd",p:"n",vn:"thẻ (ngân hàng)",ex:"Can I pay by card?"},
 {t:"coin",ipa:"kɔɪn",p:"n",vn:"tiền xu",ex:"Keep some coins for change."},
 {t:"amount",ipa:"əˈmaʊnt",p:"n",vn:"số tiền, số lượng",ex:"The total amount is on the bill."},
 {t:"total",ipa:"ˈtoʊtl̩",p:"n",vn:"tổng cộng",ex:"The total comes to two million."},
 {t:"percent",ipa:"pərˈsent",p:"n",vn:"phần trăm",ex:"Most restaurants lose three to five percent."},
 {t:"number",ipa:"ˈnʌmbər",p:"n",vn:"con số",ex:"Let me show you the numbers."},
 {t:"expensive",ipa:"ɪkˈspensɪv",p:"adj",vn:"đắt",ex:"Expensive compared to what?"},
 {t:"cheap",ipa:"tʃiːp",p:"adj",vn:"rẻ",ex:"Their price is cheaper, but slower."},
 {t:"free",ipa:"friː",p:"adj",vn:"miễn phí",ex:"You can try it free for 14 days."},
 {t:"salary",ipa:"ˈsæləri",p:"n",vn:"lương (tháng)",ex:"We pay a fair salary plus commission."},
 {t:"income",ipa:"ˈɪnkʌm",p:"n",vn:"thu nhập",ex:"The app grows their income."},
 {t:"tax",ipa:"tæks",p:"n",vn:"thuế",ex:"The system prints a VAT invoice with tax."},
 {t:"bank",ipa:"bæŋk",p:"n",vn:"ngân hàng",ex:"The money goes straight to the bank."},
 {t:"loan",ipa:"loʊn",p:"n",vn:"khoản vay",ex:"They took a loan to open a new branch."},
 {t:"afford",ipa:"əˈfɔːrd",p:"v",vn:"đủ khả năng chi trả",ex:"Small shops can afford our basic plan."},
 {t:"million",ipa:"ˈmɪljən",p:"n",vn:"triệu",ex:"They make about ten million a day."},
 {t:"thousand",ipa:"ˈθaʊzn̩d",p:"n",vn:"nghìn",ex:"The setup fee is a few thousand."},
 {t:"hundred",ipa:"ˈhʌndrəd",p:"n",vn:"trăm",ex:"We serve a few hundred guests a day."},
 {t:"dozen",ipa:"ˈdʌzn̩",p:"n",vn:"tá (12)",ex:"They order a dozen boxes a week."},
 {t:"half",ipa:"hæf",p:"n",vn:"một nửa",ex:"Another company offers half the price.",tip:"L câm: đọc HAEF."},
 {t:"quarter",ipa:"ˈkwɔːrtər",p:"n",vn:"một phần tư; quý",ex:"Sales went up this quarter."},
 {t:"double",ipa:"ˈdʌbl̩",p:"v",vn:"gấp đôi",ex:"They doubled their outlets in a year."},
 {t:"time",ipa:"taɪm",p:"n",vn:"thời gian",ex:"The system saves you time."},
 {t:"hour",ipa:"ˈaʊər",p:"n",vn:"giờ (đồng hồ)",ex:"It saves two hours every day.",tip:"H câm: đọc AU-ờ."},
 {t:"minute",ipa:"ˈmɪnɪt",p:"n",vn:"phút",ex:"The demo takes ten minutes."},
 {t:"second",ipa:"ˈsekənd",p:"n",vn:"giây; thứ hai",ex:"The kitchen sees the order in seconds."},
 {t:"day",ipa:"deɪ",p:"n",vn:"ngày",ex:"At the end of the day, check the revenue."},
 {t:"week",ipa:"wiːk",p:"n",vn:"tuần",ex:"We go live in three weeks."},
 {t:"month",ipa:"mʌnθ",p:"n",vn:"tháng",ex:"The fee is per outlet per month."},
 {t:"year",ipa:"jɪr",p:"n",vn:"năm",ex:"Sign for one year and the fee is lower."},
 {t:"today",ipa:"təˈdeɪ",p:"adv",vn:"hôm nay",ex:"How can I help you today?"},
 {t:"tomorrow",ipa:"təˈmɑːroʊ",p:"adv",vn:"ngày mai",ex:"I'll send the contract tomorrow."},
 {t:"yesterday",ipa:"ˈjestərdeɪ",p:"adv",vn:"hôm qua",ex:"We closed the deal yesterday."},
 {t:"morning",ipa:"ˈmɔːrnɪŋ",p:"n",vn:"buổi sáng",ex:"Good morning, everyone."},
 {t:"afternoon",ipa:"ˌæftərˈnuːn",p:"n",vn:"buổi chiều",ex:"I'll call you back this afternoon."},
 {t:"evening",ipa:"ˈiːvnɪŋ",p:"n",vn:"buổi tối",ex:"The dinner rush starts in the evening."},
 {t:"night",ipa:"naɪt",p:"n",vn:"ban đêm",ex:"We make a backup every night."},
 {t:"early",ipa:"ˈɜːrli",p:"adj",vn:"sớm",ex:"Sign early to get the discount."},
 {t:"late",ipa:"leɪt",p:"adj",vn:"muộn",ex:"Sorry I'm late for the meeting."},
 {t:"soon",ipa:"suːn",p:"adv",vn:"sớm (nay mai)",ex:"I'll get back to you soon."},
 {t:"now",ipa:"naʊ",p:"adv",vn:"bây giờ",ex:"How many outlets do you have now?"},
 {t:"weekly",ipa:"ˈwiːkli",p:"adj",vn:"hàng tuần",ex:"She sends a weekly report."},
 {t:"monthly",ipa:"ˈmʌnθli",p:"adj",vn:"hàng tháng",ex:"There's a small monthly fee."},
 {t:"yearly",ipa:"ˈjɪrli",p:"adj",vn:"hàng năm",ex:"The yearly plan is cheaper."},
 {t:"date",ipa:"deɪt",p:"n",vn:"ngày (tháng)",ex:"What's the go-live date?"},
 {t:"o'clock",ipa:"əˈklɑːk",p:"adv",vn:"giờ đúng",ex:"Let's start at nine o'clock."},
 {t:"period",ipa:"ˈpɪriəd",p:"n",vn:"khoảng thời gian; giai đoạn",ex:"The trial period is two weeks."},
 {t:"wage",ipa:"weɪdʒ",p:"n",vn:"lương (theo giờ/ngày)",ex:"Part-time staff get an hourly wage."}
]},
{id:"feelings",title:"Cảm xúc & tính cách",icon:"i-star",c:"nghe",words:[
 {t:"happy",ipa:"ˈhæpi",p:"adj",vn:"vui, hạnh phúc",ex:"I'm happy with the result."},
 {t:"sad",ipa:"sæd",p:"adj",vn:"buồn",ex:"He looked sad after losing the deal."},
 {t:"angry",ipa:"ˈæŋɡri",p:"adj",vn:"tức giận",ex:"I'm not angry, I want you to succeed."},
 {t:"tired",ipa:"ˈtaɪərd",p:"adj",vn:"mệt",ex:"The staff are tired after peak hours."},
 {t:"busy",ipa:"ˈbɪzi",p:"adj",vn:"bận",ex:"Sorry, I'm a bit busy this week."},
 {t:"excited",ipa:"ɪkˈsaɪtɪd",p:"adj",vn:"hào hứng",ex:"I'm excited about the new feature."},
 {t:"bored",ipa:"bɔːrd",p:"adj",vn:"chán",ex:"Customers get bored waiting for the bill."},
 {t:"worried",ipa:"ˈwɜːrid",p:"adj",vn:"lo lắng",ex:"I understand you're worried about the budget."},
 {t:"nervous",ipa:"ˈnɜːrvəs",p:"adj",vn:"hồi hộp, lo",ex:"I was nervous before my first pitch."},
 {t:"stressed",ipa:"strest",p:"adj",vn:"căng thẳng",ex:"Is your job stressful?"},
 {t:"relaxed",ipa:"rɪˈlækst",p:"adj",vn:"thư giãn",ex:"The café has a relaxed atmosphere."},
 {t:"surprised",ipa:"sərˈpraɪzd",p:"adj",vn:"ngạc nhiên",ex:"I was surprised by the low price."},
 {t:"scared",ipa:"skerd",p:"adj",vn:"sợ",ex:"Don't be scared to speak English."},
 {t:"proud",ipa:"praʊd",p:"adj",vn:"tự hào",ex:"I'm proud of my team."},
 {t:"disappointed",ipa:"ˌdɪsəˈpɔɪntɪd",p:"adj",vn:"thất vọng",ex:"The client was disappointed with support."},
 {t:"comfortable",ipa:"ˈkʌmftəbl̩",p:"adj",vn:"thoải mái",ex:"Are you comfortable with these terms?"},
 {t:"interested",ipa:"ˈɪntrəstɪd",p:"adj",vn:"quan tâm, thích",ex:"The owner seems interested."},
 {t:"curious",ipa:"ˈkjʊriəs",p:"adj",vn:"tò mò",ex:"I'm curious about your current system."},
 {t:"grateful",ipa:"ˈɡreɪtfl̩",p:"adj",vn:"biết ơn",ex:"I'm grateful for your time today."},
 {t:"lonely",ipa:"ˈloʊnli",p:"adj",vn:"cô đơn",ex:"Working from home can feel lonely."},
 {t:"annoyed",ipa:"əˈnɔɪd",p:"adj",vn:"khó chịu, bực",ex:"Guests get annoyed by slow service."},
 {t:"upset",ipa:"ʌpˈset",p:"adj",vn:"buồn bực",ex:"She was upset about the mistake."},
 {t:"glad",ipa:"ɡlæd",p:"adj",vn:"mừng, vui",ex:"I'm glad we could meet today."},
 {t:"hopeful",ipa:"ˈhoʊpfl̩",p:"adj",vn:"đầy hy vọng",ex:"I'm hopeful about this quarter."},
 {t:"motivated",ipa:"ˈmoʊtɪveɪtɪd",p:"adj",vn:"có động lực",ex:"A good bonus keeps the team motivated."},
 {t:"serious",ipa:"ˈsɪriəs",p:"adj",vn:"nghiêm túc",ex:"Are you serious about signing this month?"},
 {t:"strict",ipa:"strɪkt",p:"adj",vn:"nghiêm khắc",ex:"Our security rules are strict."},
 {t:"lazy",ipa:"ˈleɪzi",p:"adj",vn:"lười",ex:"He's not lazy, he needs training."},
 {t:"brave",ipa:"breɪv",p:"adj",vn:"dũng cảm",ex:"Be brave and make the call."},
 {t:"careful",ipa:"ˈkerfl̩",p:"adj",vn:"cẩn thận",ex:"Be careful with the price promise."},
 {t:"careless",ipa:"ˈkerləs",p:"adj",vn:"cẩu thả",ex:"One careless mistake can lose a client."},
 {t:"creative",ipa:"kriˈeɪtɪv",p:"adj",vn:"sáng tạo",ex:"She has creative ideas for the menu."},
 {t:"ambitious",ipa:"æmˈbɪʃəs",p:"adj",vn:"tham vọng",ex:"They have an ambitious growth plan."},
 {t:"reliable",ipa:"rɪˈlaɪəbl̩",p:"adj",vn:"đáng tin cậy",ex:"Our support is reliable and fast."},
 {t:"flexible",ipa:"ˈfleksəbl̩",p:"adj",vn:"linh hoạt",ex:"Our plans are flexible for small shops."},
 {t:"positive",ipa:"ˈpɑːzətɪv",p:"adj",vn:"tích cực",ex:"Keep a positive tone on the call."},
 {t:"negative",ipa:"ˈneɡətɪv",p:"adj",vn:"tiêu cực",ex:"Don't focus on the negative points."},
 {t:"quiet",ipa:"ˈkwaɪət",p:"adj",vn:"yên tĩnh; ít nói",ex:"Mornings are quiet in the café."},
 {t:"loud",ipa:"laʊd",p:"adj",vn:"ồn ào; to (tiếng)",ex:"Speak loud and clear in the demo."},
 {t:"gentle",ipa:"ˈdʒentl̩",p:"adj",vn:"nhẹ nhàng",ex:"Be gentle when you correct staff."},
 {t:"rude",ipa:"ruːd",p:"adj",vn:"thô lỗ",ex:"Never be rude to a customer."},
 {t:"fair",ipa:"fer",p:"adj",vn:"công bằng, hợp lý",ex:"I think the price is fair."},
 {t:"strong",ipa:"strɔːŋ",p:"adj",vn:"mạnh",ex:"We have a strong support team."},
 {t:"weak",ipa:"wiːk",p:"adj",vn:"yếu",ex:"My grammar is still weak."},
 {t:"helpful",ipa:"ˈhelpfl̩",p:"adj",vn:"hữu ích, hay giúp",ex:"The staff were very helpful."},
 {t:"mood",ipa:"muːd",p:"n",vn:"tâm trạng",ex:"The boss is in a good mood today."},
 {t:"feeling",ipa:"ˈfiːlɪŋ",p:"n",vn:"cảm giác",ex:"Don't let a guilty feeling stop you."},
 {t:"attitude",ipa:"ˈætɪtuːd",p:"n",vn:"thái độ",ex:"A good attitude sells more than words."},
 {t:"afraid",ipa:"əˈfreɪd",p:"adj",vn:"sợ, e ngại",ex:"I'm afraid the price is a bit high."},
 {t:"embarrassed",ipa:"ɪmˈbærəst",p:"adj",vn:"xấu hổ, ngượng",ex:"Don't be embarrassed to say it again."}
]},
{id:"connectors",title:"Nối câu & trạng từ",icon:"i-quote",c:"tonghop",words:[
 {t:"because",ipa:"bɪˈkɔːz",p:"prep",vn:"bởi vì",ex:"I like it because I meet many people."},
 {t:"but",ipa:"bʌt",p:"prep",vn:"nhưng",ex:"It's cheaper, but much slower."},
 {t:"so",ipa:"soʊ",p:"prep",vn:"vì vậy, nên",ex:"No paper, so no mistakes."},
 {t:"however",ipa:"haʊˈevər",p:"adv",vn:"tuy nhiên",ex:"However, the price is a bit high."},
 {t:"although",ipa:"ɔːlˈðoʊ",p:"prep",vn:"mặc dù",ex:"Although it's new, it's stable."},
 {t:"though",ipa:"ðoʊ",p:"prep",vn:"mặc dù (thân mật)",ex:"It works well, though it costs more."},
 {t:"actually",ipa:"ˈæktʃuəli",p:"adv",vn:"thật ra",ex:"Actually, sales is about listening."},
 {t:"honestly",ipa:"ˈɑːnəstli",p:"adv",vn:"thành thật mà nói",ex:"Honestly, I've never thought about that."},
 {t:"basically",ipa:"ˈbeɪsɪkli",p:"adv",vn:"về cơ bản",ex:"Basically, it has three parts."},
 {t:"usually",ipa:"ˈjuːʒuəli",p:"adv",vn:"thường thường",ex:"I usually start work at eight."},
 {t:"often",ipa:"ˈɔːfn̩",p:"adv",vn:"thường xuyên",ex:"Do you often eat at restaurants?"},
 {t:"sometimes",ipa:"ˈsʌmtaɪmz",p:"adv",vn:"thỉnh thoảng",ex:"Sometimes the problem is me."},
 {t:"always",ipa:"ˈɔːlweɪz",p:"adv",vn:"luôn luôn",ex:"The customer is always in a hurry."},
 {t:"never",ipa:"ˈnevər",p:"adv",vn:"không bao giờ",ex:"I never push a client too hard."},
 {t:"really",ipa:"ˈriːəli",p:"adv",vn:"thật sự",ex:"I really enjoy my job."},
 {t:"maybe",ipa:"ˈmeɪbi",p:"adv",vn:"có lẽ",ex:"Maybe we can start with two outlets."},
 {t:"probably",ipa:"ˈprɑːbəbli",p:"adv",vn:"có lẽ (khả năng cao)",ex:"They'll probably decide next week."},
 {t:"definitely",ipa:"ˈdefɪnətli",p:"adv",vn:"chắc chắn",ex:"We can definitely do that for you."},
 {t:"especially",ipa:"ɪˈspeʃəli",p:"adv",vn:"đặc biệt là",ex:"It helps, especially during peak hours."},
 {t:"finally",ipa:"ˈfaɪnəli",p:"adv",vn:"cuối cùng",ex:"Finally, let me confirm the terms."},
 {t:"suddenly",ipa:"ˈsʌdənli",p:"adv",vn:"đột nhiên",ex:"Suddenly the internet went down."},
 {t:"quickly",ipa:"ˈkwɪkli",p:"adv",vn:"nhanh chóng",ex:"The kitchen sees the order quickly."},
 {t:"slowly",ipa:"ˈsloʊli",p:"adv",vn:"chậm rãi",ex:"Please speak slowly, my English is basic."},
 {t:"carefully",ipa:"ˈkerfəli",p:"adv",vn:"cẩn thận",ex:"Read the contract carefully."},
 {t:"already",ipa:"ɔːlˈredi",p:"adv",vn:"đã (rồi)",ex:"We've already fixed the bug."},
 {t:"still",ipa:"stɪl",p:"adv",vn:"vẫn còn",ex:"If the internet is down, you can still sell."},
 {t:"yet",ipa:"jet",p:"adv",vn:"chưa (đến giờ)",ex:"They haven't decided yet."},
 {t:"also",ipa:"ˈɔːlsoʊ",p:"adv",vn:"cũng",ex:"It also works offline."},
 {t:"either",ipa:"ˈiːðər",p:"adv",vn:"cũng (câu phủ định)",ex:"I don't have the KDS either."},
 {t:"instead",ipa:"ɪnˈsted",p:"adv",vn:"thay vào đó",ex:"Use a tablet instead of paper."},
 {t:"therefore",ipa:"ˈðerfɔːr",p:"adv",vn:"do đó",ex:"It saves time; therefore it saves money."},
 {t:"otherwise",ipa:"ˈʌðərwaɪz",p:"adv",vn:"nếu không thì",ex:"Sign this week; otherwise the price changes."},
 {t:"besides",ipa:"bɪˈsaɪdz",p:"adv",vn:"hơn nữa",ex:"Besides, you get free training."},
 {t:"anyway",ipa:"ˈeniweɪ",p:"adv",vn:"dù sao thì",ex:"Anyway, let's continue after lunch."},
 {t:"even",ipa:"ˈiːvn̩",p:"adv",vn:"thậm chí",ex:"It's fast even in peak hours."},
 {t:"almost",ipa:"ˈɔːlmoʊst",p:"adv",vn:"gần như",ex:"We work with almost every big chain."},
 {t:"enough",ipa:"ɪˈnʌf",p:"adv",vn:"đủ",ex:"My English is good enough to sell."},
 {t:"quite",ipa:"kwaɪt",p:"adv",vn:"khá",ex:"The setup is quite simple."},
 {t:"nearly",ipa:"ˈnɪrli",p:"adv",vn:"gần, sắp",ex:"We're nearly ready to go live."},
 {t:"recently",ipa:"ˈriːsntli",p:"adv",vn:"gần đây",ex:"We recently launched a new feature."},
 {t:"currently",ipa:"ˈkɜːrəntli",p:"adv",vn:"hiện tại",ex:"What system are you currently using?"},
 {t:"for example",ipa:"fər ɪɡˈzæmpl̩",p:"phr",vn:"ví dụ",ex:"For example, last month I closed a chain."},
 {t:"in fact",ipa:"ɪn ˈfækt",p:"phr",vn:"thực ra",ex:"In fact, it pays for itself."},
 {t:"of course",ipa:"əv ˈkɔːrs",p:"phr",vn:"tất nhiên",ex:"Of course, training is included."},
 {t:"at least",ipa:"ət ˈliːst",p:"phr",vn:"ít nhất",ex:"Speak English at least five minutes a day."},
 {t:"by the way",ipa:"ˌbaɪ ðə ˈweɪ",p:"phr",vn:"nhân tiện",ex:"By the way, do you need the KDS?"},
 {t:"as well",ipa:"əz ˈwel",p:"phr",vn:"cũng vậy",ex:"We support e-wallets as well."},
 {t:"to be honest",ipa:"tə bi ˈɑːnɪst",p:"phr",vn:"nói thật là",ex:"To be honest, I'm not sure."},
 {t:"more or less",ipa:"ˌmɔːr ɔːr ˈles",p:"phr",vn:"nhiều hay ít, đại khái",ex:"It's more or less the same price."},
 {t:"in general",ipa:"ɪn ˈdʒenrəl",p:"phr",vn:"nói chung",ex:"In general, restaurants love it."}
]},
{id:"comms",title:"Điện thoại, email & họp",icon:"i-bell",c:"noi",words:[
 {t:"hello",ipa:"həˈloʊ",p:"phr",vn:"xin chào",ex:"Hello, this is Thuy from the software team."},
 {t:"goodbye",ipa:"ˌɡʊdˈbaɪ",p:"phr",vn:"tạm biệt",ex:"Goodbye, and thanks for your time."},
 {t:"please",ipa:"pliːz",p:"adv",vn:"làm ơn, xin",ex:"Please tell me if you have a problem."},
 {t:"thanks",ipa:"θæŋks",p:"phr",vn:"cảm ơn",ex:"Thanks for coming today."},
 {t:"sorry",ipa:"ˈsɑːri",p:"phr",vn:"xin lỗi",ex:"Sorry, I didn't catch that."},
 {t:"welcome",ipa:"ˈwelkəm",p:"phr",vn:"hoan nghênh; không có gì",ex:"Welcome, please have a seat."},
 {t:"introduce",ipa:"ˌɪntrəˈduːs",p:"v",vn:"giới thiệu",ex:"Let me introduce our product."},
 {t:"appointment",ipa:"əˈpɔɪntmənt",p:"n",vn:"cuộc hẹn",ex:"I'd like to make an appointment."},
 {t:"agenda",ipa:"əˈdʒendə",p:"n",vn:"chương trình họp",ex:"There are three points on the agenda."},
 {t:"invite",ipa:"ɪnˈvaɪt",p:"v",vn:"mời",ex:"I'll invite you to the online demo."},
 {t:"attend",ipa:"əˈtend",p:"v",vn:"tham dự",ex:"Who will attend the meeting?"},
 {t:"present",ipa:"ˈpreznt",p:"adj",vn:"có mặt",ex:"Everyone on the team is present."},
 {t:"absent",ipa:"ˈæbsənt",p:"adj",vn:"vắng mặt",ex:"Two staff are absent today."},
 {t:"reply",ipa:"rɪˈplaɪ",p:"v",vn:"trả lời (thư)",ex:"Please reply before Friday."},
 {t:"forward",ipa:"ˈfɔːrwərd",p:"v",vn:"chuyển tiếp (thư)",ex:"I'll forward you the quote."},
 {t:"attach",ipa:"əˈtætʃ",p:"v",vn:"đính kèm",ex:"I've attached the contract."},
 {t:"subject",ipa:"ˈsʌbdʒekt",p:"n",vn:"chủ đề (email)",ex:"Put 'Quote' in the subject line."},
 {t:"regards",ipa:"rɪˈɡɑːrdz",p:"n",vn:"lời chào cuối thư",ex:"Best regards, Thuy."},
 {t:"sincerely",ipa:"sɪnˈsɪrli",p:"adv",vn:"trân trọng (cuối thư)",ex:"Yours sincerely, Thuy."},
 {t:"dear",ipa:"dɪr",p:"adj",vn:"kính gửi (mở thư)",ex:"Dear Mr. Nam, thank you for your email."},
 {t:"hold",ipa:"hoʊld",p:"v",vn:"giữ máy; giữ",ex:"Please hold, I'll check for you."},
 {t:"connect",ipa:"kəˈnekt",p:"v",vn:"kết nối; nối máy",ex:"Let me connect you to support."},
 {t:"voicemail",ipa:"ˈvɔɪsmeɪl",p:"n",vn:"hộp thư thoại",ex:"Leave a voicemail and I'll call back."},
 {t:"extension",ipa:"ɪkˈstenʃn̩",p:"n",vn:"số máy nhánh",ex:"My extension is 105."},
 {t:"available",ipa:"əˈveɪləbl̩",p:"adj",vn:"rảnh, sẵn có",ex:"Are you available on Monday?"},
 {t:"convenient",ipa:"kənˈviːniənt",p:"adj",vn:"thuận tiện",ex:"What time is convenient for you?"},
 {t:"postpone",ipa:"poʊstˈpoʊn",p:"v",vn:"hoãn lại",ex:"Can we postpone to next week?"},
 {t:"reschedule",ipa:"ˌriːˈskedʒuːl",p:"v",vn:"đổi lịch",ex:"Let's reschedule the demo."},
 {t:"summary",ipa:"ˈsʌməri",p:"n",vn:"bản tóm tắt",ex:"I'll send a short summary after the call."},
 {t:"note",ipa:"noʊt",p:"n",vn:"ghi chú",ex:"Let me make a note of that."},
 {t:"question",ipa:"ˈkwestʃən",p:"n",vn:"câu hỏi",ex:"Can I ask you a few questions?"},
 {t:"answer",ipa:"ˈænsər",p:"n",vn:"câu trả lời",ex:"I don't have the answer right now."},
 {t:"clear",ipa:"klɪr",p:"adj",vn:"rõ ràng",ex:"Is that clear, or should I repeat?"},
 {t:"understand",ipa:"ˌʌndərˈstænd",p:"v",vn:"hiểu",ex:"I understand your budget."},
 {t:"repeat",ipa:"rɪˈpiːt",p:"v",vn:"nhắc lại",ex:"Could you repeat that, please?"},
 {t:"speak",ipa:"spiːk",p:"v",vn:"nói",ex:"Can I speak to the owner?"},
 {t:"listen",ipa:"ˈlɪsn̩",p:"v",vn:"lắng nghe",ex:"Good sellers listen more than they talk."},
 {t:"conversation",ipa:"ˌkɑːnvərˈseɪʃn̩",p:"n",vn:"cuộc trò chuyện",ex:"It was a good conversation, thank you."},
 {t:"follow-up",ipa:"ˈfɑːloʊʌp",p:"n",vn:"việc theo dõi tiếp",ex:"I'll book a follow-up for next week."},
 {t:"wrap up",ipa:"ˌræp ˈʌp",p:"phr",vn:"kết thúc, chốt lại",ex:"Let's wrap up the meeting."},
 {t:"speak up",ipa:"ˌspiːk ˈʌp",p:"phr",vn:"nói to lên",ex:"Could you speak up, please?"},
 {t:"hold on",ipa:"ˌhoʊld ˈɑːn",p:"phr",vn:"chờ chút",ex:"Hold on, I'll check the price."},
 {t:"go ahead",ipa:"ˌɡoʊ əˈhed",p:"phr",vn:"cứ tiếp tục đi",ex:"Go ahead, I'm listening."},
 {t:"I didn't catch that",ipa:"aɪ ˈdɪdnt ˈkætʃ ðæt",p:"phr",vn:"tôi chưa nghe rõ",ex:"Sorry, I didn't catch that."},
 {t:"get back to you",ipa:"ˌɡet ˈbæk tə ju",p:"phr",vn:"trả lời lại bạn sau",ex:"Let me check and get back to you."},
 {t:"on the phone",ipa:"ˌɑːn ðə ˈfoʊn",p:"phr",vn:"đang nói điện thoại",ex:"She's on the phone with a client."},
 {t:"keep in touch",ipa:"ˌkiːp ɪn ˈtʌtʃ",p:"phr",vn:"giữ liên lạc",ex:"Let's keep in touch after the trial."},
 {t:"look forward",ipa:"ˌlʊk ˈfɔːrwərd",p:"phr",vn:"mong chờ (thư)",ex:"I look forward to your reply."},
 {t:"urgent",ipa:"ˈɜːrdʒənt",p:"adj",vn:"khẩn, gấp",ex:"This is urgent — can we talk today?"},
 {t:"hang up",ipa:"ˌhæŋ ˈʌp",p:"phr",vn:"cúp máy",ex:"Don't hang up, I have one more thing."}
]},
{id:"outside",title:"Đi lại, ăn uống & mua sắm",icon:"i-flag",c:"italki",words:[
 {t:"travel",ipa:"ˈtrævl̩",p:"v",vn:"đi lại, du lịch",ex:"I travel to clients across the city."},
 {t:"trip",ipa:"trɪp",p:"n",vn:"chuyến đi",ex:"It was a short business trip."},
 {t:"airport",ipa:"ˈerpɔːrt",p:"n",vn:"sân bay",ex:"I'll meet the partner at the airport."},
 {t:"flight",ipa:"flaɪt",p:"n",vn:"chuyến bay",ex:"My flight is at seven tomorrow."},
 {t:"ticket",ipa:"ˈtɪkɪt",p:"n",vn:"vé",ex:"I booked the ticket online."},
 {t:"hotel",ipa:"hoʊˈtel",p:"n",vn:"khách sạn",ex:"We also sell to hotel restaurants."},
 {t:"taxi",ipa:"ˈtæksi",p:"n",vn:"taxi",ex:"Let's take a taxi to the demo."},
 {t:"bus",ipa:"bʌs",p:"n",vn:"xe buýt",ex:"Some staff come by bus."},
 {t:"station",ipa:"ˈsteɪʃn̩",p:"n",vn:"nhà ga, trạm",ex:"The café is near the bus station."},
 {t:"map",ipa:"mæp",p:"n",vn:"bản đồ",ex:"I'll send you the location on a map."},
 {t:"direction",ipa:"dɪˈrekʃn̩",p:"n",vn:"phương hướng, chỉ đường",ex:"Can you give me directions to your shop?"},
 {t:"left",ipa:"left",p:"n",vn:"bên trái",ex:"The kitchen is on the left."},
 {t:"right",ipa:"raɪt",p:"n",vn:"bên phải; đúng",ex:"The counter is on your right."},
 {t:"straight",ipa:"streɪt",p:"adv",vn:"thẳng",ex:"Go straight and you'll see the café."},
 {t:"near",ipa:"nɪr",p:"prep",vn:"gần",ex:"Is there a restaurant near here?"},
 {t:"far",ipa:"fɑːr",p:"adj",vn:"xa",ex:"The outlet isn't far from my office."},
 {t:"corner",ipa:"ˈkɔːrnər",p:"n",vn:"góc",ex:"The shop is on the corner."},
 {t:"traffic",ipa:"ˈtræfɪk",p:"n",vn:"giao thông",ex:"Sorry, the traffic was heavy."},
 {t:"parking",ipa:"ˈpɑːrkɪŋ",p:"n",vn:"chỗ đỗ xe",ex:"The restaurant has easy parking."},
 {t:"shop",ipa:"ʃɑːp",p:"n",vn:"cửa hàng",ex:"She runs a small coffee shop."},
 {t:"store",ipa:"stɔːr",p:"n",vn:"cửa hàng (lớn)",ex:"The chain has stores in three cities."},
 {t:"mall",ipa:"mɔːl",p:"n",vn:"trung tâm thương mại",ex:"Their new outlet is in the mall."},
 {t:"supermarket",ipa:"ˈsuːpərmɑːrkɪt",p:"n",vn:"siêu thị",ex:"Even the supermarket café uses our POS."},
 {t:"size",ipa:"saɪz",p:"n",vn:"kích cỡ",ex:"We fit shops of every size."},
 {t:"color",ipa:"ˈkʌlər",p:"n",vn:"màu sắc",ex:"You can change the color of the menu."},
 {t:"cart",ipa:"kɑːrt",p:"n",vn:"giỏ hàng, xe đẩy",ex:"The online cart connects to the POS."},
 {t:"queue",ipa:"kjuː",p:"n",vn:"hàng chờ",ex:"A fast POS shortens the queue.",tip:"Đọc như 'kiu'."},
 {t:"luggage",ipa:"ˈlʌɡɪdʒ",p:"n",vn:"hành lý",ex:"I keep a demo tablet in my luggage."},
 {t:"passport",ipa:"ˈpæspɔːrt",p:"n",vn:"hộ chiếu",ex:"Bring your passport for the trip."},
 {t:"visa",ipa:"ˈviːzə",p:"n",vn:"thị thực",ex:"He's applying for a business visa."},
 {t:"abroad",ipa:"əˈbrɔːd",p:"adv",vn:"ở nước ngoài",ex:"Some owners studied abroad."},
 {t:"vacation",ipa:"veɪˈkeɪʃn̩",p:"n",vn:"kỳ nghỉ",ex:"Sales drop when owners are on vacation."},
 {t:"holiday",ipa:"ˈhɑːlədeɪ",p:"n",vn:"ngày lễ, kỳ nghỉ",ex:"Restaurants are busy on holidays."},
 {t:"weather",ipa:"ˈweðər",p:"n",vn:"thời tiết",ex:"Bad weather brings more delivery orders."},
 {t:"rain",ipa:"reɪn",p:"n",vn:"mưa",ex:"When it rains, delivery goes up."},
 {t:"sunny",ipa:"ˈsʌni",p:"adj",vn:"nắng",ex:"On sunny days the terrace is full."},
 {t:"hot",ipa:"hɑːt",p:"adj",vn:"nóng",ex:"Cold drinks sell well when it's hot."},
 {t:"cold",ipa:"koʊld",p:"adj",vn:"lạnh",ex:"Hot coffee sells more when it's cold."},
 {t:"hungry",ipa:"ˈhʌŋɡri",p:"adj",vn:"đói",ex:"Guests are hungry and want fast service."},
 {t:"thirsty",ipa:"ˈθɜːrsti",p:"adj",vn:"khát",ex:"After a walk I'm always thirsty."},
 {t:"distance",ipa:"ˈdɪstəns",p:"n",vn:"khoảng cách",ex:"We support outlets at any distance."},
 {t:"road",ipa:"roʊd",p:"n",vn:"con đường",ex:"There's a new café down the road."},
 {t:"walk",ipa:"wɔːk",p:"v",vn:"đi bộ",ex:"I walk to the café near my office."},
 {t:"drive",ipa:"draɪv",p:"v",vn:"lái xe",ex:"I drive to far clients."},
 {t:"ride",ipa:"raɪd",p:"v",vn:"đi (xe máy, xe đạp)",ex:"I ride my motorbike to work."},
 {t:"arrive",ipa:"əˈraɪv",p:"v",vn:"đến nơi",ex:"I'll arrive ten minutes early."},
 {t:"depart",ipa:"dɪˈpɑːrt",p:"v",vn:"khởi hành",ex:"We depart right after the demo."},
 {t:"delay",ipa:"dɪˈleɪ",p:"n",vn:"sự chậm trễ",ex:"I apologize for the delay."},
 {t:"reserve",ipa:"rɪˈzɜːrv",p:"v",vn:"đặt trước",ex:"I'd like to reserve a table for four."},
 {t:"try on",ipa:"ˌtraɪ ˈɑːn",p:"phr",vn:"mặc thử",ex:"You can try the demo on your own tablet."}
]}
];
