# -*- coding: utf-8 -*-
"""ex2 cho nhom describe-adj va movement."""
EX2 = {
# --- describe-adj ---
"important": "Family is the most important thing to me.",
"different": "Life in the countryside is completely different.",
"similar": "My brother and I have similar taste in music.",
"same": "We went to the same school as children.",
"possible": "Is it possible to get there by bus?",
"impossible": "It is impossible to park here on Sunday.",
"necessary": "Take a jacket, it may be necessary tonight.",
"useful": "This little knife is very useful when camping.",
"popular": "That beach is popular with young families.",
"famous": "The town is famous for its noodles.",
"common": "Rain is common in this season.",
"normal": "It is normal for a puppy to sleep a lot.",
"special": "My mother cooks something special on my birthday.",
"main": "The main road is closed today.",
"basic": "He only knows basic Japanese.",
"simple": "I like simple food, nothing fancy.",
"easy": "This game is easy enough for a child.",
"difficult": "The exam was more difficult than I expected.",
"hard": "The bed in the hotel was very hard.",
"correct": "Only one answer is correct.",
"wrong": "I took the wrong bus and got lost.",
"true": "Is it true that you are moving to Hanoi?",
"real": "Those flowers are not real.",
"rich": "They are not rich, but they are happy.",
"poor": "The soil here is too poor for rice.",
"heavy": "This bag is too heavy for me to carry.",
"quick": "Let me take a quick shower first.",
"fast": "He drives too fast on the highway.",
"slow": "The traffic is very slow this morning.",
"clean": "Put on a clean shirt before we go.",
"dirty": "The children came home with dirty shoes.",
"safe": "It is not safe to cycle here at night.",
"ready": "Dinner is ready, come to the table.",
"complete": "I have the complete set of his books.",
"empty": "The bottle is empty already.",
"full": "The bus was full, so I walked.",
"whole": "He ate the whole cake by himself.",
"perfect": "The weather was perfect for a picnic.",
"terrible": "I had a terrible night, the dog kept barking.",
"lucky": "You are lucky it did not rain.",
"modern": "They live in a modern flat near the river.",
"traditional": "My mother still cooks the traditional way.",
"local": "We buy vegetables at the local market.",
"national": "Today is a national holiday.",
"public": "There is a public park behind our house.",
"private": "This is a private garden, not a park.",
"official": "The official language here is Vietnamese.",
"regular": "He is a regular visitor to my parents' house.",
"recent": "In recent years the village has grown a lot.",
"further": "The shop is a little further down this street.",
"various": "We saw various birds at the lake.",
"certain": "I am certain I locked the door.",
"sure": "Are you sure you don't want coffee?",
"likely": "It is likely to rain this afternoon.",
"unlikely": "He is unlikely to come, he hates parties.",
"obvious": "It was obvious that the child was tired.",
"particular": "Do you have a particular restaurant in mind?",
"general": "In general, I sleep badly in hotels.",
"specific": "Be specific about the time you will arrive.",
"standard": "This is the standard size for a single bed.",
"typical": "A typical Sunday for me is cooking and reading.",
"actual": "The actual journey took five hours.",
"current": "What is your current address?",
"previous": "We met at a previous wedding.",
"effective": "Hot tea with honey is effective for a sore throat.",
"valuable": "This old watch is very valuable to me.",
"suitable": "That film is not suitable for small children.",
"reasonable": "The hotel was clean and the price was reasonable.",
"acceptable": "Coming ten minutes late is acceptable here.",

# --- movement ---
"lie": "The cat likes to lie in the sun.",
"jump": "The children jumped into the pool.",
"climb": "We climbed the hill to watch the sunset.",
"fall": "Be careful, you might fall on the wet floor.",
"rise": "The sun rises at half past five.",
"push": "I had to push the door hard to open it.",
"pull": "Pull the rope slowly.",
"lift": "Can you lift this suitcase for me?",
"carry": "She carried her shopping bags home.",
"drop": "I dropped my phone in the street.",
"catch": "He ran to catch the last bus.",
"throw": "Don't throw stones at the birds.",
"enter": "Please take off your shoes before you enter.",
"return": "We return from holiday on Sunday.",
"follow": "The dog follows me everywhere.",
"pass": "We passed a beautiful lake on the way.",
"cross": "Look both ways before you cross.",
"reach": "I can't reach the top shelf.",
"escape": "The bird escaped from its cage.",
"hurry": "Hurry up, the film starts in ten minutes.",
"wait": "I waited an hour for my friend.",
"stay": "We stayed at my aunt's house.",
"here": "It is very quiet here in the evening.",
"there": "There are three cats in our street.",
"above": "The birds were flying above the trees.",
"below": "The temperature fell below zero last night.",
"under": "The cat is sleeping under the bed.",
"over": "The bridge goes over the river.",
"between": "The shop is between the bank and the post office.",
"among": "I found my old photos among some books.",
"beside": "Come and sit beside me.",
"behind": "The garden behind the house is small.",
"in front of": "A tall man sat in front of me at the cinema.",
"visit": "We visit my grandparents every Sunday.",
"inside": "Let's eat inside, it is too cold outside.",
"outside": "The children are playing outside.",
"around": "We walked around the lake.",
"through": "The train goes through a long tunnel.",
"across": "She swam across the river.",
"along": "We walked along the beach at sunset.",
"toward": "The dog ran toward its owner.",
"backward": "He took one step backward in surprise.",
"up": "The cat ran up the tree.",
"down": "Sit down and rest for a minute.",
"top": "There is snow on the top of the mountain.",
"bottom": "My keys were at the bottom of my bag.",
"middle": "The dog slept in the middle of the room.",
"remove": "Please remove your shoes at the door.",
"replace": "I need to replace the light bulb.",
"transport": "Public transport here is cheap.",
"journey": "It was a long journey by train.",
"route": "This is the fastest route to the beach.",
"position": "He changed position because his leg hurt.",
"location": "The house has a quiet location near the park.",
"spread": "The children spread a blanket on the grass.",
"shake": "Shake the bottle before you open it.",
"roll": "The ball rolled under the car.",
"slide": "The children love to slide on the ice.",
"hang": "Hang your coat behind the door.",
"separate": "We separate paper and plastic for recycling.",
"divide": "Let's divide the cake into six pieces.",
"gather": "The family gathers here every New Year.",
"collect": "My son collects football cards.",
"step": "Watch that first step, it is high.",
"side": "There is a small garden on the side of the house.",
}
