# -*- coding: utf-8 -*-
"""Cau vi du THU HAI (ex2) - nguu canh doi thuong, khac han ex (cong viec)."""
EX2 = {
# --- body-health ---
"body": "Cold water is a shock to the body.",
"head": "He hit his head on the door.",
"face": "Wash your face with cold water.",
"eye": "She has beautiful brown eyes.",
"ear": "The baby has very small ears.",
"nose": "My nose is blocked because of the cold.",
"mouth": "Don't talk with your mouth full.",
"tooth": "My little boy lost his first tooth.",
"hair": "I want to cut my hair short.",
"neck": "I wear a scarf around my neck in winter.",
"shoulder": "My son sat on my shoulders at the park.",
"arm": "She held the baby in her arms.",
"hand": "Give me your hand, the road is busy.",
"finger": "I cut my finger while cooking.",
"leg": "The dog has short legs.",
"foot": "My left foot is bigger than my right one.",
"knee": "He sat down and put the child on his knee.",
"back": "I sleep on my back.",
"stomach": "I can't swim right after eating, my stomach hurts.",
"heart": "My heart was beating fast after the run.",
"blood": "I don't like the sight of blood.",
"skin": "Her skin is very dry in winter.",
"bone": "The dog buried a bone in the garden.",
"brain": "Reading is good exercise for the brain.",
"healthy": "My grandmother is eighty and still healthy.",
"ill": "My daughter was ill all weekend.",
"illness": "He recovered from a long illness.",
"sick": "The cat was sick on the carpet.",
"disease": "The doctors are studying this rare disease.",
"pain": "I felt a sharp pain in my leg.",
"painful": "The first day at the gym was painful.",
"hurt": "My feet hurt after the long walk.",
"injury": "He got an injury while playing football.",
"injured": "The injured bird could not fly.",
"wound": "The wound on his hand healed slowly.",
"cure": "There is still no cure for the common cold.",
"treatment": "She is having treatment at the local clinic.",
"medicine": "This medicine tastes terrible.",
"drug": "The doctor gave her a strong drug for the pain.",
"doctor": "My sister wants to be a doctor.",
"nurse": "The nurse was very kind to my mother.",
"hospital": "My son was born in this hospital.",
"operation": "She had an operation on her eyes last year.",
"exercise": "Walking is the easiest exercise.",
"fit": "He runs every morning to stay fit.",
"rest": "You look tired, you need some rest.",
"sleep": "The baby sleeps for twelve hours.",
"asleep": "The children are already asleep.",
"wake": "The noise woke me at three in the morning.",
"breathe": "It is hard to breathe in this hot room.",
"weight": "The doctor asked me about my weight.",
"blind": "Their dog helps a blind man cross the street.",
"deaf": "My grandfather is going deaf.",
"dead": "The plant is dead, I forgot to water it.",
"death": "The whole village came after his death.",
"alive": "The fish is still alive in the bucket.",
"dangerous": "Swimming in this river is dangerous.",
"medical": "He is studying at a medical school.",
"fever": "The child had a fever all night.",
"mental": "Walking outside is good for mental health.",
}
