# -*- coding: utf-8 -*-
"""Gan moi tu Oxford 3000 vao MOT chu de, de hoc theo chu de thay vi A-Z.

   TOPICS  = thu tu hien thi + ten tieng Viet + icon + mau ky nang.
   MAP     = tu -> ma chu de. Viet theo THU TU A-Z giong file nguon
             de de soat, khong sot tu.
   Chay ox_build.py se bao: tu chua gan / ma chu de la, tu gan nhung khong ton tai.
"""

# ma, tieu de, icon, mau (theo bang mau ky nang trong index.html)
TOPICS = [
    ("work",    "Công việc, công ty & nghề nghiệp",         "i-users",      "noi"),
    ("biz",     "Kinh doanh, bán hàng & đàm phán",          "i-scale",      "damphan"),
    ("money",   "Tiền bạc, giá cả & ngân hàng",             "i-table",      "damphan"),
    ("food",    "Ăn uống & ngành F&B",                      "i-star",       "noi"),
    ("people",  "Con người, gia đình & quan hệ",            "i-users",      "noi"),
    ("body",    "Cơ thể, sức khoẻ & tai nạn",               "i-alert",      "nghe"),
    ("feel",    "Cảm xúc & thái độ",                        "i-flame",      "noi"),
    ("mind",    "Suy nghĩ, ý kiến & khái niệm",             "i-quote",      "doc"),
    ("home",    "Nhà cửa & đồ đạc",                         "i-layers",     "nghe"),
    ("clothes", "Quần áo & ngoại hình",                     "i-star",       "nghe"),
    ("travel",  "Đi lại, du lịch & phương tiện",            "i-flag",       "nghe"),
    ("place",   "Địa điểm, thành phố & phương hướng",       "i-flag",       "nghe"),
    ("nature",  "Thiên nhiên, động vật & thời tiết",        "i-sun",        "nghe"),
    ("time",    "Thời gian & lịch",                         "i-cal",        "doc"),
    ("number",  "Số lượng, đo lường & kích thước",          "i-table",      "doc"),
    ("edu",     "Học hành, ngôn ngữ & khoa học",            "i-book",       "doc"),
    ("tech",    "Công nghệ, máy móc & vật liệu",            "i-file",       "doc"),
    ("media",   "Truyền thông, âm thanh & giải trí",        "i-headphones", "nghe"),
    ("sport",   "Thể thao & sở thích",                      "i-trophy",     "nghe"),
    ("law",     "Luật pháp, tội phạm & chính trị",          "i-scale",      "damphan"),
    ("society", "Xã hội, tôn giáo & lịch sử",               "i-flag",       "doc"),
    ("action",  "Động từ hành động & chuyển động",          "i-play",       "noi"),
    ("change",  "Động từ thay đổi, tăng giảm & kết quả",    "i-arrow",      "noi"),
    ("adj",     "Tính từ mô tả & đánh giá",                 "i-pen",        "viet"),
    ("adv",     "Trạng từ & mức độ",                        "i-pen",        "viet"),
    ("gram",    "Từ nối, giới từ & từ ngữ pháp",            "i-file",       "viet"),
]

MAP = {}

# ═══════════════════════════════════════════════════════════════════════
# 794 TU CO SAN VI DU (data-vocab.js 600 + data-vocab-plus.js 194)
# Gop chung vao 26 chu de tren, khong con khoi "co san vi du" rieng.
# Khong tu nao trung voi kho Oxford (da kiem: giao = 0).
# ═══════════════════════════════════════════════════════════════════════

# -- daily-verbs: Dong tu doi song --
MAP.update({
"go":"action","come":"action","get":"action","make":"action","take":"action","do":"action",
"have":"action","see":"action","know":"mind","think":"mind","want":"feel","need":"mind",
"use":"action","find":"action","give":"action","tell":"mind","work":"work","call":"work",
"try":"action","ask":"mind","feel":"feel","become":"change","leave":"action","put":"action",
"mean":"mind","keep":"action","let":"mind","begin":"change","seem":"mind","help":"action",
"talk":"mind","turn":"action","start":"change","show":"mind","hear":"action","play":"sport",
"run":"action","move":"action","live":"people","believe":"mind","bring":"action",
"happen":"change","write":"edu","sit":"action","stand":"action","lose":"change","pay":"money",
"meet":"work","include":"mind","continue":"change",
})

# -- work-verbs: Dong tu cong viec & hanh dong --
MAP.update({
"send":"work","receive":"work","manage":"work","lead":"work","sell":"biz","buy":"biz",
"deliver":"biz","install":"tech","fix":"tech","check":"work","confirm":"work","agree":"mind",
"arrange":"work","explain":"mind","discuss":"mind","decide":"mind","plan":"work",
"prepare":"work","report":"work","contact":"work","train":"work","hire":"work",
"promote":"work","join":"work","close":"biz","increase":"change","reduce":"change",
"save":"money","spend":"money","earn":"money","charge":"money","book":"biz","cancel":"biz",
"change":"change","improve":"change","solve":"mind","handle":"work","provide":"biz",
"suggest":"mind","recommend":"mind","compare":"mind","choose":"mind","accept":"mind",
"refuse":"mind","complain":"biz","apologize":"mind","remind":"mind","schedule":"work",
"negotiate":"biz","cooperate":"work",
})

# -- self-family: Ban than & gia dinh --
MAP.update({
"name":"people","age":"people","job":"work","hometown":"place","family":"people",
"parents":"people","mother":"people","father":"people","brother":"people","sister":"people",
"siblings":"people","son":"people","daughter":"people","child":"people","kids":"people",
"wife":"people","husband":"people","married":"people","single":"people","cousin":"people",
"uncle":"people","aunt":"people","grandparents":"people","grandmother":"people",
"grandfather":"people","friend":"people","neighbor":"people","boss":"work","colleague":"work",
"team":"work","hobby":"sport","weekend":"time","birthday":"time","health":"body","tall":"adj",
"short":"adj","young":"adj","old":"adj","kind":"feel","friendly":"feel","honest":"feel",
"patient":"feel","confident":"feel","shy":"feel","funny":"feel","smart":"feel",
"hard-working":"feel","generous":"feel","polite":"feel","calm":"feel",
})

# -- home-things: Nha o & do vat hang ngay --
MAP.update({
"house":"home","apartment":"home","room":"home","kitchen":"home","bedroom":"home",
"bathroom":"home","door":"home","window":"home","table":"home","chair":"home","bed":"home",
"desk":"home","phone":"tech","laptop":"tech","computer":"tech","key":"home","bag":"clothes",
"wallet":"clothes","clock":"time","light":"home","water":"food","food":"food","coffee":"food",
"tea":"food","car":"travel","motorbike":"travel","street":"place","city":"place",
"district":"place","building":"place","floor":"home","wall":"home","clothes":"clothes",
"shoes":"clothes","watch":"clothes","glasses":"clothes","umbrella":"clothes","fridge":"home",
"fan":"home","air conditioner":"home","television":"media","remote":"home","charger":"tech",
"internet":"tech","wifi":"tech","battery":"tech","screen":"tech","button":"tech",
"drawer":"home","shelf":"home",
})

# -- office-tech: Van phong & phan mem --
MAP.update({
"client":"biz","customer":"biz","meeting":"work","deadline":"work","project":"work",
"task":"work","email":"work","file":"work","folder":"work","document":"work","data":"tech",
"app":"tech","software":"tech","hardware":"tech","system":"tech","account":"tech",
"password":"tech","login":"tech","dashboard":"tech","feature":"tech","version":"tech",
"bug":"tech","issue":"work","error":"tech","cloud":"tech","server":"tech","database":"tech",
"backup":"tech","device":"tech","tablet":"tech","user":"tech","setting":"tech","sync":"tech",
"deploy":"tech","notification":"tech","message":"work","link":"tech","download":"tech",
"upload":"tech","printer":"tech","network":"tech","security":"tech","access":"tech",
"permission":"tech","spreadsheet":"work","chart":"work","presentation":"work",
"reminder":"work","workflow":"work","attachment":"work",
})

# -- fnb: Nganh F&B (giu tron ven trong chu de An uong & F&B) --
MAP.update({
"restaurant":"food","café":"food","waiter":"food","waitress":"food","chef":"food",
"cook":"food","guest":"food","bill":"food","tip":"food","dish":"food","drink":"food",
"meal":"food","breakfast":"food","lunch":"food","dinner":"food","espresso":"food",
"latte":"food","cappuccino":"food","juice":"food","smoothie":"food","ice":"food",
"sugar":"food","milk":"food","bread":"food","cake":"food","rice":"food","noodle":"food",
"soup":"food","sauce":"food","spicy":"food","sweet":"food","fresh":"food","delicious":"food",
"serve":"food","portion":"food","reservation":"food","booking":"food","takeaway":"food",
"delivery":"food","counter":"food","cashier":"food","shift":"food","recipe":"food",
"ingredient":"food","napkin":"food","tray":"food","menu":"food","snack":"food",
"dessert":"food","peak hours":"food",
})

# -- sales: Ban hang & dam phan --
MAP.update({
"sale":"biz","proposal":"biz","benefit":"biz","value":"biz","solution":"biz","problem":"mind",
"goal":"work","result":"change","commission":"money","profit":"money","margin":"money",
"competitor":"biz","market":"biz","brand":"biz","product":"biz","service":"biz",
"quality":"biz","guarantee":"biz","warranty":"biz","refund":"money","invoice":"money",
"installment":"money","negotiation":"biz","objection":"biz","agreement":"biz","term":"biz",
"condition":"biz","opportunity":"biz","decision":"mind","approve":"mind","reject":"mind",
"commitment":"biz","partner":"biz","relationship":"people","trust":"feel","loyal":"feel",
"referral":"biz","upsell":"biz","advantage":"mind","risk":"biz","win":"biz",
"convince":"mind","persuade":"mind","pitch":"biz","prospect":"biz","offer":"biz",
"bargain":"biz","incentive":"biz","reference":"biz","turnover":"money",
})

# -- money-time: Tien, so & thoi gian --
MAP.update({
"money":"money","cash":"money","card":"money","coin":"money","amount":"number",
"total":"number","percent":"number","number":"number","expensive":"adj","cheap":"adj",
"free":"adj","salary":"money","income":"money","tax":"money","bank":"money","loan":"money",
"afford":"money","million":"number","thousand":"number","hundred":"number","dozen":"number",
"half":"number","quarter":"number","double":"number","time":"time","hour":"time",
"minute":"time","second":"time","day":"time","week":"time","month":"time","year":"time",
"today":"time","tomorrow":"time","yesterday":"time","morning":"time","afternoon":"time",
"evening":"time","night":"time","early":"time","late":"time","soon":"time","now":"time",
"weekly":"time","monthly":"time","yearly":"time","date":"time","o'clock":"time",
"period":"time","wage":"money",
})

# -- feelings: Cam xuc & tinh cach --
MAP.update({
"happy":"feel","sad":"feel","angry":"feel","tired":"feel","busy":"feel","excited":"feel",
"bored":"feel","worried":"feel","nervous":"feel","stressed":"feel","relaxed":"feel",
"surprised":"feel","scared":"feel","proud":"feel","disappointed":"feel","comfortable":"feel",
"interested":"feel","curious":"feel","grateful":"feel","lonely":"feel","annoyed":"feel",
"upset":"feel","glad":"feel","hopeful":"feel","motivated":"feel","serious":"feel",
"strict":"feel","lazy":"feel","brave":"feel","careful":"feel","careless":"feel",
"creative":"feel","ambitious":"feel","reliable":"feel","flexible":"feel","positive":"feel",
"negative":"feel","quiet":"feel","loud":"feel","gentle":"feel","rude":"feel","fair":"feel",
"strong":"feel","weak":"feel","helpful":"feel","mood":"feel","feeling":"feel",
"attitude":"feel","afraid":"feel","embarrassed":"feel",
})

# -- connectors: Noi cau & trang tu --
MAP.update({
"because":"gram","but":"gram","so":"gram","however":"gram","although":"gram","though":"gram",
"actually":"adv","honestly":"adv","basically":"adv","usually":"adv","often":"adv",
"sometimes":"adv","always":"adv","never":"adv","really":"adv","maybe":"adv","probably":"adv",
"definitely":"adv","especially":"adv","finally":"adv","suddenly":"adv","quickly":"adv",
"slowly":"adv","carefully":"adv","already":"adv","still":"adv","yet":"adv","also":"adv",
"either":"gram","instead":"adv","therefore":"gram","otherwise":"gram","besides":"gram",
"anyway":"adv","even":"adv","almost":"adv","enough":"adv","quite":"adv","nearly":"adv",
"recently":"adv","currently":"adv","for example":"gram","in fact":"gram","of course":"gram",
"at least":"gram","by the way":"gram","as well":"gram","to be honest":"gram",
"more or less":"gram","in general":"gram",
})

# -- comms: Dien thoai, email & hop --
MAP.update({
"hello":"mind","goodbye":"mind","please":"mind","thanks":"mind","sorry":"mind",
"welcome":"mind","introduce":"mind","appointment":"work","agenda":"work","invite":"work",
"attend":"work","present":"work","absent":"work","reply":"work","forward":"work",
"attach":"work","subject":"work","regards":"work","sincerely":"work","dear":"work",
"hold":"work","connect":"work","voicemail":"work","extension":"work","available":"work",
"convenient":"adj","postpone":"work","reschedule":"work","summary":"work","note":"work",
"question":"mind","answer":"mind","clear":"adj","understand":"mind","repeat":"mind",
"speak":"mind","listen":"mind","conversation":"mind","follow-up":"work","wrap up":"work",
"speak up":"mind","hold on":"work","go ahead":"mind","I didn't catch that":"mind",
"get back to you":"work","on the phone":"work","keep in touch":"work",
"look forward":"work","urgent":"adj","hang up":"work",
})

# -- outside: Di lai, an uong & mua sam --
MAP.update({
"travel":"travel","trip":"travel","airport":"travel","flight":"travel","ticket":"travel",
"hotel":"travel","taxi":"travel","bus":"travel","station":"travel","map":"travel",
"direction":"place","left":"place","right":"place","straight":"place","near":"place",
"far":"place","corner":"place","traffic":"travel","parking":"travel","shop":"biz",
"store":"biz","mall":"place","supermarket":"biz","size":"number","color":"adj","cart":"biz",
"queue":"biz","luggage":"travel","passport":"travel","visa":"travel","abroad":"travel",
"vacation":"travel","holiday":"time","weather":"nature","rain":"nature","sunny":"adj",
"hot":"adj","cold":"adj","hungry":"body","thirsty":"body","distance":"number",
"road":"travel","walk":"action","drive":"travel","ride":"travel","arrive":"travel",
"depart":"travel","delay":"travel","reserve":"biz","try on":"clothes",
})

# -- body-health: giu TRON VEN trong chu de Co the & suc khoe --
MAP.update({
"body":"body","head":"body","face":"body","eye":"body","ear":"body","nose":"body",
"mouth":"body","tooth":"body","hair":"body","neck":"body","shoulder":"body","arm":"body",
"hand":"body","finger":"body","leg":"body","foot":"body","knee":"body","back":"body",
"stomach":"body","heart":"body","blood":"body","skin":"body","bone":"body","brain":"body",
"healthy":"body","ill":"body","illness":"body","sick":"body","disease":"body","pain":"body",
"painful":"body","hurt":"body","injury":"body","injured":"body","wound":"body","cure":"body",
"treatment":"body","medicine":"body","drug":"body","doctor":"body","nurse":"body",
"hospital":"body","operation":"body","exercise":"body","fit":"body","rest":"body",
"sleep":"body","asleep":"body","wake":"body","breathe":"body","weight":"body","blind":"body",
"deaf":"body","dead":"body","death":"body","alive":"body","dangerous":"body",
"medical":"body","fever":"body","mental":"body",
})

# -- describe-adj: tinh tu mo ta hay dung nhat --
MAP.update({
"important":"adj","different":"adj","similar":"adj","same":"adj","possible":"adj",
"impossible":"adj","necessary":"adj","useful":"adj","popular":"adj","famous":"adj",
"common":"adj","normal":"adj","special":"adj","main":"adj","basic":"adj","simple":"adj",
"easy":"adj","difficult":"adj","hard":"adj","correct":"adj","wrong":"adj","true":"adj",
"real":"adj","rich":"adj","poor":"adj","heavy":"adj","quick":"adj","fast":"adj","slow":"adj",
"clean":"adj","dirty":"adj","safe":"adj","ready":"adj","complete":"adj","empty":"adj",
"full":"adj","whole":"adj","perfect":"adj","terrible":"adj","lucky":"adj","modern":"adj",
"traditional":"adj","local":"adj","national":"adj","public":"adj","private":"adj",
"official":"adj","regular":"adj","recent":"adj","further":"adj","various":"adj",
"certain":"adj","sure":"adj","likely":"adj","unlikely":"adj","obvious":"adj",
"particular":"adj","general":"adj","specific":"adj","standard":"adj","typical":"adj",
"actual":"adj","current":"adj","previous":"adj","effective":"adj","valuable":"adj",
"suitable":"adj","reasonable":"adj","acceptable":"adj",
})

# -- movement: Dong tu chuyen dong & vi tri --
MAP.update({
"lie":"action","jump":"action","climb":"action","fall":"action","rise":"change",
"push":"action","pull":"action","lift":"action","carry":"action","drop":"action",
"catch":"action","throw":"action","enter":"action","return":"action","follow":"action",
"pass":"action","cross":"action","reach":"action","visit":"travel","escape":"action",
"hurry":"action","wait":"action","stay":"action","here":"place","there":"place",
"above":"place","below":"place","under":"place","over":"place","between":"place",
"among":"place","beside":"place","behind":"place","in front of":"place","inside":"place",
"outside":"place","around":"place","through":"place","across":"place","along":"place",
"toward":"place","backward":"place","up":"place","down":"place","top":"place",
"bottom":"place","middle":"place","remove":"change","replace":"change","transport":"travel",
"journey":"travel","route":"travel","position":"place","location":"place","spread":"action",
"shake":"action","roll":"action","slide":"action","hang":"action","separate":"action",
"divide":"number","gather":"action","collect":"action","step":"action","side":"place",
})

# ═══════════════════════════════════════════════════════════════════════
# 2649 TU KHO OXFORD (chua co vi du)
# ═══════════════════════════════════════════════════════════════════════

# ── A ────────────────────────────────────────────────────────────────
MAP.update({
"a":"gram","abandon":"action","abandoned":"adj","ability":"mind","able":"adj",
"about":"gram","absence":"mind","absolute":"adj","absolutely":"adv","absorb":"action",
"abuse":"law","academic":"edu","accent":"edu","accident":"body","accidental":"adj",
"accidentally":"adv","accommodation":"travel","accompany":"action","according to":"gram",
"accurate":"adj","accurately":"adv","accuse":"law","achieve":"change","achievement":"work",
"acid":"tech","acknowledge":"mind","acquire":"change","act":"action","action":"action",
"active":"adj","actively":"adv","activity":"action","actor":"media","actress":"media",
"adapt":"change","add":"number","addition":"number","additional":"adj","address":"place",
"adequate":"adj","adequately":"adv","adjust":"change","admiration":"feel","admire":"feel",
"admit":"mind","adopt":"change","adult":"people","advance":"change","advanced":"adj",
"adventure":"travel","advertise":"biz","advertisement":"biz","advertising":"biz",
"advice":"mind","advise":"mind","affair":"society","affect":"change","affection":"feel",
"after":"gram","afterwards":"time","again":"adv","against":"gram","aged":"adj",
"agency":"biz","agent":"biz","aggressive":"feel","ago":"time","ahead":"place","aid":"society",
"aim":"work","air":"nature","aircraft":"travel","alarm":"tech","alarmed":"feel",
"alarming":"adj","alcohol":"food","alcoholic":"food","all":"gram","all right":"gram",
"allied":"society","allow":"mind","ally":"society","alone":"adj","alongside":"gram",
"aloud":"adv","alphabet":"edu","alphabetical":"edu","alphabetically":"edu","alter":"change",
"alternative":"mind","alternatively":"adv","altogether":"adv","amaze":"feel","amazed":"feel",
"amazing":"adj","ambition":"work","ambulance":"body","amuse":"feel","amused":"feel",
"amusing":"adj","analysis":"mind","ancient":"time","and":"gram","anger":"feel","angle":"number",
"angrily":"adv","animal":"nature","ankle":"body","anniversary":"time","announce":"mind",
"annoy":"feel","annoying":"adj","annual":"time","annually":"adv","another":"gram","anti":"gram",
"anticipate":"mind","anxiety":"feel","anxious":"feel","anxiously":"adv","anyone":"gram",
"anything":"gram","anywhere":"gram","apart":"adv","apart from":"gram","apparent":"adj",
"apparently":"adv","appeal":"mind","appear":"change","appearance":"clothes","apple":"food",
"application":"work","apply":"work","appoint":"work","appreciate":"feel","approach":"action",
"appropriate":"adj","approval":"mind","approve of":"mind","approving":"adj",
"approximate":"number","approximately":"number","April":"time","area":"place","argue":"mind",
"argument":"mind","arise":"change","armed":"law","arms":"law","army":"law",
"arrangement":"work","arrest":"law","arrival":"travel","arrow":"tech","art":"media",
"article":"media","artificial":"adj","artificially":"adv","artist":"media","artistic":"adj",
"as":"gram","ashamed":"feel","aside":"adv","aspect":"mind","assist":"work",
"assistance":"work","assistant":"work","associate":"mind","association":"society",
"assume":"mind","assure":"mind","atmosphere":"nature","atom":"tech","attached":"adj",
"attack":"law","attempt":"action","attempted":"adj","attention":"mind","attorney":"law",
"attract":"feel","attraction":"feel","attractive":"adj","audience":"media","August":"time",
"author":"media","authority":"law","automatic":"tech","automatically":"adv","autumn":"time",
"average":"number","avoid":"action","awake":"body","award":"work","aware":"mind","away":"adv",
"awful":"adj","awfully":"adv","awkward":"adj","awkwardly":"adv",
})

# ── B ────────────────────────────────────────────────────────────────
MAP.update({
"background":"mind","backwards":"place","bacteria":"body","bad":"adj","badly":"adv",
"bad-tempered":"feel","baggage":"travel","bake":"food","balance":"number","ball":"sport",
"ban":"law","band":"media","bandage":"body","bar":"food","barrier":"place","base":"place",
"basis":"mind","bath":"home","battle":"law","bay":"nature","be":"gram","beach":"nature",
"beak":"nature","bear":"feel","beard":"body","beat":"action","beautiful":"adj",
"beautifully":"adv","beauty":"clothes","beef":"food","beer":"food","before":"gram",
"beginning":"time","behalf":"gram","behave":"people","belief":"mind","bell":"tech",
"belong":"mind","belt":"clothes","bend":"action","beneath":"gram","bent":"adj","bet":"sport",
"betting":"sport","beyond":"gram","bicycle":"travel","bid":"biz","big":"adj","bin":"home",
"biology":"edu","bird":"nature","birth":"people","biscuit":"food","bit":"number",
"bite":"action","bitter":"food","bitterly":"adv","black":"adj","blade":"tech","blame":"mind",
"blank":"adj","blankly":"adv","block":"place","blonde":"clothes","blow":"action","blue":"adj",
"board":"work","boat":"travel","boil":"food","bomb":"law","boot":"clothes","border":"place",
"bore":"feel","boring":"adj","born":"people","borrow":"money","both":"gram","bother":"feel",
"bottle":"food","bound":"adj","bowl":"home","box":"home","boy":"people","boyfriend":"people",
"branch":"biz","break":"action","breast":"body","breath":"body","breathing":"body",
"breed":"nature","brick":"tech","bridge":"place","brief":"adj","briefly":"adv","bright":"adj",
"brightly":"adv","brilliant":"adj","broad":"adj","broadcast":"media","broadly":"adv",
"broken":"adj","brown":"adj","brush":"home","bubble":"nature","budget":"money","build":"action",
"bullet":"law","bunch":"number","burn":"action","burnt":"adj","burst":"action","bury":"action",
"bush":"nature","business":"biz","butter":"food","buyer":"biz","by":"gram","bye":"gram",
})

# ── C ────────────────────────────────────────────────────────────────
MAP.update({
"cabinet":"home","cable":"tech","calculate":"number","calculation":"number","calmly":"adv",
"camera":"tech","camp":"travel","campaign":"biz","camping":"travel","cancer":"body",
"candidate":"work","candy":"food","cap":"clothes","capable of":"adj","capacity":"number",
"capital":"money","captain":"sport","capture":"action","cardboard":"tech","care":"feel",
"career":"work","carelessly":"adv","carpet":"home","carrot":"food","case":"mind","cast":"media",
"castle":"place","cat":"nature","category":"mind","cause":"mind","CD":"tech","cease":"change",
"ceiling":"home","celebrate":"society","celebration":"society","cell":"body","cent":"money",
"centimetre":"number","central":"place","centre":"place","century":"time","ceremony":"society",
"certainly":"adv","certificate":"edu","chain":"biz","challenge":"work","chamber":"place",
"chance":"mind","channel":"media","chapter":"edu","character":"people","characteristic":"mind",
"charity":"society","chase":"action","chat":"mind","cheaply":"adv","cheat":"law","cheek":"body",
"cheerful":"feel","cheerfully":"adv","cheese":"food","chemical":"tech","chemist":"edu",
"chemistry":"edu","cheque":"money","chest":"body","chew":"food","chicken":"food","chief":"work",
"chin":"body","chip":"food","chocolate":"food","choice":"mind","chop":"food","church":"society",
"cigarette":"body","cinema":"media","circle":"number","circumstance":"mind","citizen":"society",
"civil":"society","claim":"mind","clap":"action","class":"edu","classic":"adj",
"classroom":"edu","clearly":"adv","clerk":"work","clever":"adj","click":"tech","climate":"nature",
"climbing":"sport","closed":"adj","closely":"adv","closet":"home","cloth":"clothes",
"clothing":"clothes","club":"sport","coach":"sport","coal":"tech","coast":"nature",
"coat":"clothes","code":"tech","coldly":"adv","collapse":"change","collection":"mind",
"college":"edu","coloured":"adj","column":"media","combination":"mind","combine":"change",
"comedy":"media","comfort":"feel","comfortably":"adv","command":"work","comment":"mind",
"commercial":"biz","commit":"action","committee":"work","commonly":"adv","communicate":"mind",
"communication":"mind","community":"society","company":"biz","comparison":"mind","compete":"biz",
"competition":"biz","competitive":"adj","complaint":"biz","completely":"adv","complex":"adj",
"complicate":"change","complicated":"adj","concentrate":"mind","concentration":"mind",
"concept":"mind","concern":"feel","concerned":"adj","concerning":"gram","concert":"media",
"conclude":"mind","conclusion":"mind","concrete":"tech","conduct":"action","conference":"work",
"confidence":"feel","confidently":"adv","confine":"action","confined":"adj","conflict":"society",
"confront":"action","confuse":"mind","confused":"feel","confusing":"adj","confusion":"mind",
"congratulations":"society","congress":"law","connection":"mind","conscious":"mind",
"consequence":"mind","conservative":"law","consider":"mind","considerable":"adj",
"considerably":"adv","consideration":"mind","consist of":"mind","constant":"adj",
"constantly":"adv","construct":"tech","construction":"tech","consult":"work","consumer":"biz",
"contain":"mind","container":"home","contemporary":"time","content":"mind","contest":"sport",
"context":"mind","continent":"place","continuous":"adj","continuously":"adv","contract":"biz",
"contrast":"mind","contrasting":"adj","contribute":"society","contribution":"society",
"control":"work","controlled":"adj","convention":"work","conventional":"adj","convert":"change",
"cooker":"home","cookie":"food","cooking":"food","cool":"adj","cope":"feel","copy":"action",
"core":"mind","correctly":"adv","cost":"money","cottage":"home","cotton":"clothes",
"cough":"body","coughing":"body","council":"law","count":"number","country":"place",
"countryside":"nature","county":"place","couple":"people","courage":"feel","course":"edu",
"court":"law","cover":"action","covered":"adj","covering":"tech","cow":"nature","crack":"tech",
"cracked":"adj","craft":"media","crash":"travel","crazy":"adj","cream":"food","create":"change",
"creature":"nature","credit":"money","credit card":"money","crime":"law","criminal":"law",
"crisis":"society","crisp":"adj","criterion":"mind","critical":"adj","criticism":"mind",
"criticize":"mind","crop":"nature","crowd":"people","crowded":"adj","crown":"society",
"crucial":"adj","cruel":"feel","crush":"action","cry":"feel","cultural":"adj","culture":"society",
"cup":"home","cupboard":"home","curb":"place","curiously":"adv","curl":"clothes","curly":"adj",
"curtain":"home","curve":"number","curved":"adj","custom":"society","customs":"travel",
"cut":"action","cycle":"number","cycling":"sport",
})

# ── D ────────────────────────────────────────────────────────────────
MAP.update({
"dad":"people","daily":"time","damage":"change","damp":"adj","dance":"media","dancer":"media",
"dancing":"media","danger":"body","dare":"feel","dark":"adj","deal":"biz","debate":"mind",
"debt":"money","decade":"time","decay":"change","December":"time","declare":"mind",
"decline":"change","decorate":"home","decoration":"home","decorative":"adj","decrease":"change",
"deep":"adj","deeply":"adv","defeat":"sport","defence":"law","defend":"law","define":"mind",
"definite":"adj","definition":"mind","degree":"edu","deliberate":"adj","deliberately":"adv",
"delicate":"adj","delight":"feel","delighted":"feel","demand":"biz","demonstrate":"mind",
"dentist":"body","deny":"mind","department":"work","departure":"travel","depend on":"mind",
"deposit":"money","depress":"feel","depressed":"feel","depressing":"adj","depth":"number",
"derive":"mind","describe":"mind","description":"mind","desert":"nature","deserted":"adj",
"deserve":"mind","design":"work","desire":"feel","desperate":"feel","desperately":"adv",
"despite":"gram","destroy":"change","destruction":"change","detail":"mind","detailed":"adj",
"determination":"feel","determine":"mind","determined":"feel","develop":"change",
"development":"change","devote":"feel","devoted":"adj","diagram":"edu","diamond":"clothes",
"diary":"edu","dictionary":"edu","die":"body","diet":"food","difference":"mind",
"differently":"adv","difficulty":"mind","dig":"action","direct":"action","directly":"adv",
"director":"work","dirt":"home","disabled":"body","disadvantage":"mind","disagree":"mind",
"disagreement":"mind","disappear":"change","disappoint":"feel","disappointing":"adj",
"disappointment":"feel","disapproval":"mind","disapprove of":"mind","disapproving":"adj",
"disaster":"society","discipline":"edu","discount":"money","discover":"mind","discovery":"mind",
"discussion":"mind","disgust":"feel","disgusted":"feel","disgusting":"adj","dishonest":"feel",
"dishonestly":"adv","disk":"tech","dislike":"feel","dismiss":"work","display":"biz",
"dissolve":"change","distinguish":"mind","distribute":"biz","distribution":"biz",
"disturb":"action","disturbing":"adj","division":"number","divorce":"people","divorced":"adj",
"dog":"nature","dollar":"money","domestic":"adj","dominate":"change","dot":"number",
"doubt":"mind","downstairs":"home","downward":"place","downwards":"place","draft":"work",
"drag":"action","drama":"media","dramatic":"adj","dramatically":"adv","draw":"media",
"drawing":"media","dream":"mind","dress":"clothes","dressed":"adj","driver":"travel",
"driving":"travel","drugstore":"body","drum":"media","drunk":"adj","dry":"adj","due":"adj",
"dull":"adj","dump":"action","during":"gram","dust":"home","duty":"work","DVD":"tech",
"dying":"adj",
})

# ── E ────────────────────────────────────────────────────────────────
MAP.update({
"each":"gram","each other":"gram","earth":"nature","ease":"mind","easily":"adv","east":"place",
"eastern":"place","eat":"food","economic":"money","economy":"money","edge":"place",
"edition":"media","editor":"media","educate":"edu","educated":"adj","education":"edu",
"effect":"mind","effectively":"adv","efficient":"adj","efficiently":"adv","effort":"work",
"egg":"food","elbow":"body","elderly":"people","elect":"law","election":"law","electric":"tech",
"electrical":"tech","electricity":"tech","electronic":"tech","elegant":"adj","element":"mind",
"elevator":"home","else":"gram","elsewhere":"gram","embarrass":"feel","embarrassing":"adj",
"embarrassment":"feel","emerge":"change","emergency":"body","emotion":"feel","emotional":"feel",
"emotionally":"adv","emphasis":"mind","emphasize":"mind","empire":"society","employ":"work",
"employee":"work","employer":"work","employment":"work","enable":"change","encounter":"action",
"encourage":"feel","encouragement":"feel","end":"time","ending":"time","enemy":"society",
"energy":"tech","engage":"work","engaged":"people","engine":"tech","engineer":"work",
"engineering":"tech","enjoy":"feel","enjoyable":"adj","enjoyment":"feel","enormous":"adj",
"enquiry":"mind","ensure":"mind","entertain":"media","entertainer":"media","entertaining":"adj",
"entertainment":"media","enthusiasm":"feel","enthusiastic":"feel","entire":"adj",
"entirely":"adv","entitle":"mind","entrance":"place","entry":"place","envelope":"work",
"environment":"nature","environmental":"adj","equal":"number","equally":"adv",
"equipment":"tech","equivalent":"number","essay":"edu","essential":"adj","essentially":"adv",
"establish":"biz","estate":"place","estimate":"number","euro":"money","event":"society",
"eventually":"adv","ever":"adv","every":"gram","everything":"gram","everywhere":"gram",
"evidence":"law","evil":"feel","ex-":"gram","exact":"adj","exactly":"adv","exaggerate":"mind",
"exaggerated":"adj","exam":"edu","examination":"edu","examine":"mind","example":"mind",
"excellent":"adj","except":"gram","exception":"mind","exchange":"biz","excite":"feel",
"excitement":"feel","exciting":"adj","exclude":"mind","excluding":"gram","excuse":"mind",
"executive":"work","exhibit":"media","exhibition":"media","exist":"mind","existence":"mind",
"exit":"place","expand":"change","expect":"mind","expectation":"mind","expected":"adj",
"expense":"money","experience":"work","experienced":"adj","experiment":"edu","expert":"work",
"explanation":"mind","explode":"change","explore":"travel","explosion":"change","export":"biz",
"expose":"action","express":"mind","expression":"mind","extend":"change","extensive":"adj",
"extent":"number","extra":"adj","extraordinary":"adj","extreme":"adj","extremely":"adv",
})

# ── F ────────────────────────────────────────────────────────────────
MAP.update({
"facility":"place","fact":"mind","factor":"mind","factory":"work","fail":"change",
"failure":"change","faint":"adj","faintly":"adv","fairly":"adv","faith":"society",
"faithful":"feel","faithfully":"adv","FALSE":"adj","fame":"media","familiar":"adj",
"fancy":"feel","farm":"nature","farmer":"work","farming":"nature","fashion":"clothes",
"fashionable":"adj","fasten":"action","fat":"adj","faucet":"home","fault":"mind","favour":"feel",
"favourite":"adj","fear":"feel","feather":"nature","February":"time","federal":"law","fee":"money",
"feed":"food","fellow":"people","female":"people","fence":"home","festival":"society",
"fetch":"action","few":"number","field":"nature","fight":"law","fighting":"law","figure":"number",
"fill":"action","film":"media","final":"adj","finance":"money","financial":"adj","fine":"adj",
"finely":"adv","finish":"change","finished":"adj","fire":"body","firm":"biz","firmly":"adv",
"first":"number","fish":"food","fishing":"sport","fixed":"adj","flag":"society","flame":"nature",
"flash":"tech","flat":"home","flavour":"food","flesh":"body","float":"action","flood":"nature",
"flour":"food","flow":"action","flower":"nature","flu":"body","fly":"action","flying":"travel",
"focus":"mind","fold":"action","folding":"adj","following":"adj","football":"sport","for":"gram",
"force":"change","forecast":"nature","foreign":"travel","forest":"nature","forever":"time",
"forget":"mind","forgive":"feel","fork":"home","form":"work","formal":"adj","formally":"adv",
"former":"time","formerly":"adv","formula":"edu","fortune":"money","found":"biz",
"foundation":"biz","frame":"tech","freedom":"society","freely":"adv","freeze":"food",
"frequent":"adj","frequently":"adv","freshly":"adv","Friday":"time","friendship":"people",
"frighten":"feel","frightened":"feel","frightening":"adj","from":"gram","front":"place",
"frozen":"adj","fruit":"food","fry":"food","fuel":"tech","fully":"adv","fun":"feel",
"function":"tech","fund":"money","fundamental":"adj","funeral":"society","fur":"nature",
"furniture":"home","future":"time",
})

# ── G ────────────────────────────────────────────────────────────────
MAP.update({
"gain":"change","gallon":"number","gamble":"sport","gambling":"sport","game":"sport",
"gap":"place","garage":"home","garbage":"home","garden":"home","gas":"tech",
"gasoline":"travel","gate":"home","gear":"travel","generally":"adv","generate":"change",
"generation":"people","generously":"adv","gentleman":"people","gently":"adv","genuine":"adj",
"genuinely":"adv","geography":"edu","giant":"adj","gift":"society","girl":"people",
"girlfriend":"people","glass":"home","global":"adj","glove":"clothes","glue":"tech",
"god":"society","gold":"money","good":"adj","goods":"biz","govern":"law","government":"law",
"governor":"law","grab":"action","grade":"edu","gradual":"adj","gradually":"adv","grain":"food",
"gram":"number","grammar":"edu","grand":"adj","grandchild":"people","granddaughter":"people",
"grandparent":"people","grandson":"people","grant":"money","grass":"nature","grave":"society",
"gray":"adj","great":"adj","greatly":"adv","green":"adj","grey":"adj","groceries":"food",
"grocery":"food","ground":"place","group":"people","grow":"change","growth":"change",
"guard":"law","guess":"mind","guide":"travel","guilty":"law","gun":"law","guy":"people",
})

# ── H ────────────────────────────────────────────────────────────────
MAP.update({
"habit":"people","hairdresser":"clothes","hall":"home","hammer":"tech","happily":"adv",
"happiness":"feel","hardly":"adv","harm":"body","harmful":"adj","harmless":"adj","hat":"clothes",
"hate":"feel","hatred":"feel","he":"gram","headache":"body","heal":"body","hearing":"body",
"heat":"nature","heating":"home","heaven":"society","heavily":"adv","heel":"body",
"height":"number","hell":"society","hence":"gram","her":"gram","hero":"society","hers":"gram",
"herself":"gram","hesitate":"mind","hi":"gram","hide":"action","high":"adj","highlight":"mind",
"highly":"adv","highway":"travel","hill":"nature","him":"gram","himself":"gram",
"hip":"body","his":"gram","historical":"adj","history":"society","hit":"action","hole":"place",
"hollow":"adj","holy":"society","home":"home","homework":"edu","honour":"society","hook":"tech",
"hope":"feel","horizontal":"number","horn":"travel","horror":"feel","horse":"nature",
"host":"media","household":"home","housing":"home","how":"gram","huge":"adj","human":"people",
"humorous":"adj","humour":"feel","hunt":"sport","hunting":"sport",
})

# ── I ────────────────────────────────────────────────────────────────
MAP.update({
"ice cream":"food","idea":"mind","ideal":"adj","ideally":"adv","identify":"mind",
"identity":"people","if":"gram","ignore":"mind","illegal":"law","illegally":"adv",
"illustrate":"mind","image":"media","imaginary":"adj","imagination":"mind","imagine":"mind",
"immediate":"adj","immediately":"adv","immoral":"feel","impact":"change","impatient":"feel",
"impatiently":"adv","implication":"mind","imply":"mind","import":"biz","importance":"mind",
"importantly":"adv","impose":"law","impress":"feel","impressed":"feel","impression":"mind",
"impressive":"adj","improvement":"change","in":"gram","in case of":"gram","inability":"mind",
"inch":"number","incident":"society","including":"gram","increasingly":"adv","indeed":"adv",
"independence":"society","independent":"adj","independently":"adv","index":"edu",
"indicate":"mind","indication":"mind","indirect":"adj","indirectly":"adv","individual":"people",
"indoor":"adj","indoors":"place","industrial":"adj","industry":"biz","inevitable":"adj",
"inevitably":"adv","infect":"body","infected":"adj","infection":"body","infectious":"adj",
"influence":"change","inform":"mind","informal":"adj","information":"mind","initial":"adj",
"initially":"adv","initiative":"work","injure":"body","ink":"work","inner":"adj",
"innocent":"law","insect":"nature","insert":"action","insist on":"mind","instance":"mind",
"institute":"edu","institution":"society","instruction":"mind","instrument":"media",
"insult":"feel","insulting":"adj","insurance":"money","intelligence":"mind","intelligent":"adj",
"intend":"mind","intended":"adj","intention":"mind","interest":"mind","interesting":"adj",
"interior":"home","internal":"adj","international":"adj","interpret":"mind",
"interpretation":"mind","interrupt":"mind","interruption":"mind","interval":"time",
"interview":"work","into":"gram","introduction":"mind","invent":"tech","invention":"tech",
"invest":"money","investigate":"law","investigation":"law","investment":"money",
"invitation":"society","involve":"mind","involvement":"mind","iron":"clothes","irritate":"feel",
"irritated":"feel","irritating":"adj","island":"nature","it":"gram","item":"biz","its":"gram",
"itself":"gram",
})

# ── J / K / L ────────────────────────────────────────────────────────
MAP.update({
"jacket":"clothes","jam":"food","January":"time","jealous":"feel","jeans":"clothes",
"jelly":"food","jewellery":"clothes","joint":"adj","jointly":"adv","joke":"feel",
"journalist":"media","joy":"feel","judge":"law","judgement":"mind","July":"time","June":"time",
"junior":"work","just":"adv","justice":"law","justified":"adj","justify":"mind",
"keen":"feel","keyboard":"tech","kick":"action","kid":"people","kill":"law","killing":"law",
"kilometre":"number","kindly":"adv","kindness":"feel","king":"society","kiss":"people",
"knife":"home","knit":"clothes","knitted":"adj","knitting":"clothes","knock":"action",
"knot":"tech","knowledge":"mind",
"label":"biz","labour":"work","lack of":"number","lacking":"adj","lady":"people","lake":"nature",
"lamp":"home","land":"place","landscape":"nature","lane":"travel","language":"edu","large":"adj",
"largely":"adv","last":"time","later":"time","latest":"adj","latter":"gram","laugh":"feel",
"launch":"biz","law":"law","lawyer":"law","lay":"action","layer":"number","leader":"work",
"leading":"adj","leaf":"nature","league":"sport","lean":"action","learn":"edu",
"least":"number","leather":"clothes","lecture":"edu","legal":"law","legally":"adv",
"lemon":"food","lend":"money","length":"number","less":"number","lesson":"edu","letter":"work",
"level":"number","library":"edu","licence":"law","license":"law","lid":"home","life":"people",
"lightly":"adv","like":"gram","limit":"number","limited":"adj","line":"place","lip":"body",
"liquid":"tech","list":"work","listen to":"action","literature":"edu","litre":"number",
"little":"number","lively":"adj","living":"people","load":"action","locally":"adv",
"locate":"place","located":"adj","lock":"home","logic":"mind","logical":"adj","long":"adj",
"look":"action","loose":"adj","loosely":"adv","lord":"society","lorry":"travel","loss":"money",
"lost":"adj","loudly":"adv","love":"feel","lovely":"adj","lover":"people","low":"adj",
"luck":"mind","lump":"number","lung":"body",
})

# ── M (den 'marriage') ───────────────────────────────────────────────
MAP.update({
"machine":"tech","machinery":"tech","mad":"feel","magazine":"media","magic":"media",
"mail":"work","mainly":"adv","maintain":"change","major":"adj","majority":"number",
"make-up":"clothes","male":"people","man":"people","management":"work","manager":"work",
"manner":"people","manufacture":"biz","manufacturer":"biz","manufacturing":"biz",
"many":"number","March":"time","mark":"edu","marketing":"biz","marriage":"people",
"marry":"people","mass":"number","massive":"adj","master":"edu","match":"sport",
"matching":"adj","mate":"people","material":"tech","matter":"mind","maximum":"number",
"may":"gram","mayor":"law","me":"gram","meaning":"mind","means":"mind","meanwhile":"time",
"measure":"number","measurement":"number","meat":"food","media":"media","medium":"adj",
"melt":"change","member":"society","membership":"society","memory":"mind","mentally":"adv",
"mention":"mind","mere":"adj","merely":"adv","mess":"home","metal":"tech","method":"mind",
"metre":"number","midday":"time","midnight":"time","mild":"adj","mile":"number","military":"law",
"mind":"mind","mine":"gram","mineral":"tech","minimum":"number","minister":"law",
"ministry":"law","minor":"adj","minority":"number","mirror":"home","miss":"feel",
"missing":"adj","mistake":"mind","mistaken":"adj","mix":"change","mixed":"adj",
"mixture":"number","mobile":"adj","mobile phone":"tech","model":"biz","moment":"time",
"Monday":"time","monitor":"tech","moon":"nature","moral":"feel","morally":"adv","more":"number",
"moreover":"gram","most":"number","mostly":"adv","motion":"action","motor":"tech",
"motorcycle":"travel","mount":"action","mountain":"nature","mouse":"nature","movement":"action",
"movie":"media","movie theater":"media","moving":"adj","Mr":"people","Mrs":"people","Ms":"people",
"much":"number","mud":"nature","multiply":"number","mum":"people","murder":"law","muscle":"body",
"museum":"media","music":"media","musical":"adj","musician":"media","must":"gram","my":"gram",
"myself":"gram","mysterious":"adj","mystery":"mind",
})

# ── N / O ────────────────────────────────────────────────────────────
MAP.update({
"nail":"body","naked":"adj","narrow":"adj","nation":"society","natural":"adj","naturally":"adv",
"nature":"nature","navy":"law","nearby":"place","neat":"adj","neatly":"adv","necessarily":"adv",
"needle":"clothes","neighbour":"people","neighbourhood":"place","neither":"gram",
"nephew":"people","nerve":"body","nervously":"adv","nest":"nature","net":"sport",
"nevertheless":"gram","new":"adj","newly":"adv","news":"media","newspaper":"media","next":"gram",
"nice":"adj","nicely":"adv","niece":"people","nobody":"gram","noise":"media","noisily":"adv",
"noisy":"adj","non-":"gram","none":"gram","nonsense":"mind","nor":"gram","normally":"adv",
"north":"place","northern":"place","not":"gram","nothing":"gram","notice":"mind",
"noticeable":"adj","novel":"media","November":"time","nowhere":"gram","nuclear":"tech","nut":"food",
"o clock":"time","obey":"law","object":"mind","objective":"work","observation":"mind",
"observe":"mind","obtain":"change","obviously":"adv","occasion":"society","occasionally":"adv",
"occupied":"adj","occupy":"place","occur":"change","ocean":"nature","October":"time","odd":"adj",
"oddly":"adv","of":"gram","off":"gram","offence":"law","offend":"feel","offensive":"adj",
"office":"work","officer":"law","officially":"adv","oh":"gram","oil":"food",
"old-fashioned":"adj","on":"gram","once":"time","one":"number","onion":"food","only":"adv",
"onto":"gram","open":"action","opening":"place","openly":"adv","operate":"tech","opinion":"mind",
"opponent":"sport","oppose":"mind","opposed":"adj","opposing":"adj","opposite":"place",
"opposition":"law","option":"mind","orange":"food","order":"biz","ordinary":"adj","organ":"body",
"organization":"work","organize":"work","organized":"adj","origin":"mind","original":"adj",
"originally":"adv","other":"gram","ought to":"gram","our":"gram","ours":"gram",
"ourselves":"gram","out of":"gram","outdoor":"adj","outdoors":"place","outer":"adj",
"outline":"mind","output":"biz","outstanding":"adj","oven":"home","overall":"adj",
"overcome":"change","owe":"money","own":"money","owner":"money",
})

# ── P / Q ────────────────────────────────────────────────────────────
MAP.update({
"pace":"number","pack":"action","package":"biz","packaging":"biz","packet":"biz","page":"media",
"paint":"media","painter":"media","painting":"media","pair":"number","palace":"place",
"pale":"adj","pan":"home","panel":"tech","pants":"clothes","paper":"work","parallel":"number",
"parent":"people","park":"place","parliament":"law","part":"number","particularly":"adv",
"partly":"adv","partnership":"biz","party":"society","passage":"media","passenger":"travel",
"passing":"adj","past":"time","path":"place","patience":"feel","pattern":"mind","pause":"time",
"payment":"money","peace":"society","peaceful":"adj","peak":"number","pen":"work","pence":"money",
"pencil":"work","penny":"money","pension":"money","people":"people","pepper":"food","per":"number",
"perfectly":"adv","perform":"media","performance":"work","performer":"media","perhaps":"adv",
"permanent":"adj","permanently":"adv","permit":"law","person":"people","personal":"adj",
"personality":"people","personally":"adv","pet":"nature","petrol":"travel","phase":"time",
"philosophy":"edu","photocopy":"work","photograph":"media","photographer":"media",
"photography":"media","phrase":"edu","physical":"adj","physically":"adv","physics":"edu",
"piano":"media","pick":"action","picture":"media","piece":"number","pig":"nature","pile":"number",
"pill":"body","pilot":"travel","pin":"clothes","pink":"adj","pint":"number","pipe":"tech",
"pity":"feel","place":"place","plain":"adj","plane":"travel","planet":"nature","planning":"work",
"plant":"nature","plastic":"tech","plate":"home","platform":"travel","player":"sport",
"pleasant":"adj","pleasantly":"adv","pleased":"feel","pleasing":"adj","pleasure":"feel",
"plenty":"number","plot":"media","plug":"tech","plus":"number","pocket":"clothes","poem":"media",
"poetry":"media","point":"mind","pointed":"adj","poison":"body","poisonous":"adj","pole":"tech",
"police":"law","policy":"work","polish":"home","politely":"adv","political":"adj","politically":"adv",
"politician":"law","politics":"law","pollution":"nature","pool":"sport","pop":"media",
"population":"society","port":"travel","pose":"action","possess":"money","possession":"money",
"possibility":"mind","possibly":"adv","post":"work","post office":"work","pot":"home",
"potato":"food","potential":"mind","potentially":"adv","pound":"money","pour":"food",
"powder":"food","power":"change","powerful":"adj","practical":"adj","practically":"adv",
"practice":"edu","practise":"edu","praise":"feel","prayer":"society","precise":"adj",
"precisely":"adv","predict":"mind","prefer":"mind","preference":"mind","pregnant":"body",
"premises":"place","preparation":"work","prepared":"adj","presence":"place","preserve":"change",
"president":"law","press":"media","pressure":"feel","presumably":"adv","pretend":"mind",
"pretty":"adj","prevent":"change","previously":"adv","price":"money","pride":"feel",
"priest":"society","primarily":"adv","primary":"adj","prime minister":"law","prince":"society",
"princess":"society","principle":"mind","print":"work","printing":"work","prior":"adj",
"priority":"work","prison":"law","prisoner":"law","privately":"adv","prize":"sport",
"probable":"adj","procedure":"work","proceed":"action","process":"work","produce":"biz",
"producer":"biz","production":"biz","profession":"work","professional":"work","professor":"edu",
"program":"tech","programme":"media","progress":"change","promise":"mind","promotion":"work",
"prompt":"adj","promptly":"adv","pronounce":"edu","pronunciation":"edu","proof":"mind",
"proper":"adj","properly":"adv","property":"money","proportion":"number","propose":"mind",
"protect":"change","protection":"change","protest":"law","proudly":"adv","prove":"mind",
"publication":"media","publicity":"media","publicly":"adv","publish":"media","publishing":"media",
"punch":"action","punish":"law","punishment":"law","pupil":"edu","purchase":"biz","pure":"adj",
"purely":"adv","purple":"adj","purpose":"mind","pursue":"action",
"qualification":"work","qualified":"adj","qualify":"work","quantity":"number","queen":"society",
"quietly":"adv","quit":"work","quote":"biz",
})

# ── R ────────────────────────────────────────────────────────────────
MAP.update({
"race":"sport","racing":"sport","radio":"media","rail":"travel","railway":"travel",
"raise":"change","range":"number","rank":"number","rapid":"adj","rapidly":"adv","rare":"adj",
"rarely":"adv","rate":"number","rather":"adv","raw":"adj","react":"change","reaction":"change",
"read":"edu","reader":"edu","reading":"edu","realistic":"adj","reality":"mind","realize":"mind",
"rear":"place","reason":"mind","reasonably":"adv","recall":"mind","receipt":"money",
"reception":"work","reckon":"mind","recognition":"mind","recognize":"mind","record":"media",
"recording":"media","recover":"body","red":"adj","reduction":"change","refer to":"mind",
"reflect":"mind","reform":"law","refrigerator":"home","refusal":"mind","regard":"mind",
"regarding":"gram","region":"place","regional":"adj","register":"work","regret":"feel",
"regularly":"adv","regulation":"law","relate":"mind","related to":"mind","relation":"people",
"relative":"people","relatively":"adv","relax":"feel","relaxing":"adj","release":"change",
"relevant":"adj","relief":"feel","religion":"society","religious":"adj","rely on":"mind",
"remain":"change","remaining":"adj","remains":"number","remark":"mind","remarkable":"adj",
"remarkably":"adv","remember":"mind","removal":"change","rent":"money","rented":"adj",
"repair":"tech","repeated":"adj","repeatedly":"adv","represent":"mind","representative":"work",
"reproduce":"change","reputation":"biz","request":"mind","require":"mind","requirement":"work",
"rescue":"body","research":"edu","resident":"place","resist":"change","resistance":"change",
"resolve":"mind","resort":"travel","resource":"biz","respect":"feel","respond":"mind",
"response":"mind","responsibility":"work","responsible":"work","restore":"change",
"restrict":"law","restricted":"adj","restriction":"law","retain":"change","retire":"work",
"retired":"adj","retirement":"work","reveal":"mind","reverse":"change","review":"mind",
"revise":"edu","revision":"edu","revolution":"society","reward":"work","rhythm":"media",
"rid":"change","rider":"sport","ridiculous":"adj","riding":"sport","rightly":"adv",
"ring":"action","rival":"biz","river":"nature","rob":"law","rock":"nature","role":"work",
"romantic":"adj","roof":"home","root":"nature","rope":"tech","rough":"adj","roughly":"adv",
"round":"adj","rounded":"adj","routine":"work","row":"number","royal":"society","rub":"action",
"rubber":"tech","rubbish":"home","rudely":"adv","ruin":"change","ruined":"adj","rule":"law",
"ruler":"law","rumour":"mind","runner":"sport","running":"sport","rural":"adj","rush":"action",
})

# ── S (den 'shoot') ──────────────────────────────────────────────────
MAP.update({
"sack":"work","sadly":"adv","sadness":"feel","safely":"adv","safety":"body","sail":"travel",
"sailing":"sport","sailor":"travel","salad":"food","salt":"food","salty":"adj","sample":"biz",
"sand":"nature","satisfaction":"feel","satisfied":"feel","satisfy":"feel","satisfying":"adj",
"Saturday":"time","saving":"money","say":"mind","scale":"number","scare":"feel","scene":"media",
"scheme":"work","school":"edu","science":"edu","scientific":"adj","scientist":"edu",
"scissors":"home","score":"sport","scratch":"action","scream":"feel","screw":"tech","sea":"nature",
"seal":"action","search":"action","season":"time","seat":"travel","secondary":"adj",
"secret":"mind","secretary":"work","secretly":"adv","section":"number","sector":"biz",
"secure":"adj","seed":"nature","seek":"action","select":"mind","selection":"mind","self":"people",
"self-":"gram","senate":"law","senator":"law","senior":"work","sense":"mind","sensible":"adj",
"sensitive":"feel","sentence":"edu","separated":"adj","separately":"adv","separation":"people",
"September":"time","series":"media","seriously":"adv","servant":"work","session":"work",
"set":"number","settle":"change","several":"number","severe":"adj","severely":"adv",
"sew":"clothes","sewing":"clothes","sex":"people","sexual":"adj","sexually":"adv","shade":"nature",
"shadow":"nature","shall":"gram","shallow":"adj","shame":"feel","shape":"number","shaped":"adj",
"share":"biz","sharp":"adj","sharply":"adv","shave":"body","she":"gram","sheep":"nature",
"sheet":"home","shell":"nature","shelter":"place","shine":"nature","shiny":"adj","ship":"travel",
"shirt":"clothes","shock":"feel","shocked":"feel","shocking":"adj","shoe":"clothes","shoot":"action",
"shooting":"sport","shopping":"biz","shortly":"adv","shot":"sport","should":"gram","shout":"mind",
"shower":"home","shut":"action","sideways":"place","sight":"body","sign":"mind","signal":"tech",
"signature":"work","significant":"adj","significantly":"adv","silence":"media","silent":"adj",
"silk":"clothes","silly":"adj","silver":"money","similarly":"adv","simply":"adv","since":"gram",
"sincere":"feel","sing":"media","singer":"media","singing":"media","sink":"home","sir":"people",
"situation":"mind","skilful":"adj","skilfully":"adv","skill":"work","skilled":"adj",
"skirt":"clothes","sky":"nature","sleeve":"clothes","slice":"food","slight":"adj",
"slightly":"adv","slip":"action","slope":"place","small":"adj","smash":"action","smell":"body",
"smile":"feel","smoke":"body","smoking":"body","smooth":"adj","smoothly":"adv","snake":"nature",
"snow":"nature","soap":"home","social":"adj","socially":"adv","society":"society","sock":"clothes",
"soft":"adj","softly":"adv","soil":"nature","soldier":"law","solid":"adj","some":"gram",
"somehow":"adv","something":"gram","somewhat":"adv","somewhere":"gram","song":"media","sore":"body",
"sort":"mind","soul":"society","sound":"media","sour":"food","source":"mind","south":"place",
"southern":"place","space":"place","spare":"adj","speaker":"media","specialist":"work",
"specially":"adv","specifically":"adv","speech":"mind","speed":"number","spell":"edu",
"spelling":"edu","spice":"food","spider":"nature","spin":"action","spirit":"society",
"spiritual":"adj","spite":"feel","split":"change","spoil":"change","spoken":"adj","spoon":"home",
"sport":"sport","spot":"place","spray":"action","spring":"time","square":"number",
"squeeze":"action","stable":"adj","staff":"work","stage":"media","stair":"home","stamp":"work",
"star":"media","stare":"action","state":"law","statement":"mind","statue":"media",
"status":"society","steadily":"adv","steady":"adj","steal":"law","steam":"nature","steel":"tech",
"steep":"adj","steeply":"adv","steer":"travel","stick":"action","sticky":"adj","stiff":"adj",
"stiffly":"adv","sting":"body","stir":"food","stock":"biz","stone":"tech","stop":"action",
"storm":"nature","story":"media","stove":"home","strain":"body","strange":"adj",
"strangely":"adv","stranger":"people","strategy":"work","stream":"nature","strength":"body",
"stress":"feel","stretch":"action","strictly":"adv","strike":"work","striking":"adj",
"string":"tech","strip":"number","stripe":"clothes","striped":"adj","stroke":"body",
"strongly":"adv","structure":"tech","struggle":"change","student":"edu","studio":"media",
"study":"edu","stuff":"mind","stupid":"adj","style":"clothes","substance":"tech",
"substantial":"adj","substantially":"adv","substitute":"change","succeed":"change",
"success":"change","successful":"adj","successfully":"adv","such":"gram","suck":"action",
"sudden":"adj","suffer":"feel","suffering":"feel","sufficient":"adj","sufficiently":"adv",
"suggestion":"mind","suit":"clothes","suitcase":"travel","suited":"adj","sum":"number",
"summer":"time","sun":"nature","Sunday":"time","superior":"adj","supply":"biz","support":"work",
"supporter":"sport","suppose":"mind","surely":"adv","surface":"place","surname":"people",
"surprise":"feel","surprising":"adj","surprisingly":"adv","surround":"place",
"surrounding":"adj","surroundings":"place","survey":"biz","survive":"change","suspect":"law",
"suspicion":"law","suspicious":"feel","swallow":"food","swear":"mind","swearing":"mind",
"sweat":"body","sweater":"clothes","sweep":"home","swell":"body","swelling":"body","swim":"sport",
"swimming":"sport","swimming pool":"sport","swing":"action","switch":"tech","swollen":"adj",
"symbol":"mind","sympathetic":"feel","sympathy":"feel",
})

# ── T ────────────────────────────────────────────────────────────────
MAP.update({
"tackle":"action","tail":"nature","tank":"tech","tap":"home","tape":"tech","target":"work",
"taste":"food","teach":"edu","teacher":"edu","teaching":"edu","tear":"action","technical":"adj",
"technique":"work","technology":"tech","telephone":"tech","temperature":"number",
"temporarily":"adv","temporary":"adj","tend":"mind","tendency":"mind","tension":"feel",
"tent":"travel","terribly":"adv","test":"edu","text":"media","than":"gram","thank":"mind",
"that":"gram","the":"gram","theatre":"media","their":"gram","theirs":"gram","them":"gram",
"theme":"mind","themselves":"gram","then":"gram","theory":"mind","they":"gram","thick":"adj",
"thickly":"adv","thickness":"number","thief":"law","thin":"adj","thing":"mind","thinking":"mind",
"this":"gram","thorough":"adj","thoroughly":"adv","thought":"mind","thread":"clothes",
"threat":"law","threaten":"law","threatening":"adj","throat":"body","throughout":"gram",
"thumb":"body","Thursday":"time","thus":"gram","tidy":"adj","tie":"clothes","tight":"adj",
"tightly":"adv","till":"gram","timetable":"time","tin":"home","tiny":"adj","tire":"body",
"tiring":"adj","title":"media","to":"gram","toe":"body","together":"adv","toilet":"home",
"tomato":"food","ton":"number","tone":"media","tongue":"body","tonight":"time","tonne":"number",
"too":"adv","tool":"tech","topic":"mind","totally":"adv","touch":"action","tough":"adj",
"tour":"travel","tourist":"travel","towards":"gram","towel":"home","tower":"place","town":"place",
"toy":"home","trace":"mind","track":"travel","trade":"biz","trading":"biz","tradition":"society",
"traditionally":"adv","training":"work","transfer":"change","transform":"change",
"translate":"edu","translation":"edu","transparent":"adj","trap":"action","traveller":"travel",
"treat":"feel","tree":"nature","trend":"biz","trial":"law","triangle":"number","trick":"mind",
"tropical":"adj","trouble":"mind","trousers":"clothes","truck":"travel","truly":"adv",
"truth":"mind","tube":"tech","Tuesday":"time","tune":"media","tunnel":"travel","twice":"number",
"twin":"people","twist":"action","twisted":"adj","type":"mind","typically":"adv","tyre":"travel",
})

# ── U / V ────────────────────────────────────────────────────────────
MAP.update({
"ugly":"adj","ultimate":"adj","ultimately":"adv","unable":"adj","unacceptable":"adj",
"uncertain":"adj","uncomfortable":"adj","unconscious":"body","uncontrolled":"adj",
"underground":"travel","underneath":"gram","understanding":"mind","underwater":"place",
"underwear":"clothes","undo":"action","unemployed":"work","unemployment":"work",
"unexpected":"adj","unexpectedly":"adv","unfair":"adj","unfairly":"adv","unfortunate":"adj",
"unfortunately":"adv","unfriendly":"adj","unhappiness":"feel","unhappy":"feel",
"uniform":"clothes","unimportant":"adj","union":"work","unique":"adj","unit":"number",
"unite":"change","united":"adj","universe":"nature","university":"edu","unkind":"adj",
"unknown":"adj","unless":"gram","unlike":"gram","unload":"action","unlucky":"adj",
"unnecessary":"adj","unpleasant":"adj","unreasonable":"adj","unsteady":"adj",
"unsuccessful":"adj","untidy":"adj","Unusual":"adj","unusually":"adv","Unwilling":"feel",
"unwillingly":"adv","upon":"gram","upper":"adj","upsetting":"adj","upside down":"place",
"upstairs":"home","upward":"place","upwards":"place","urban":"adj","urge":"mind","us":"gram",
"used":"adj","useless":"adj","usual":"adj",
"valid":"adj","valley":"nature","van":"travel","variation":"change","varied":"adj",
"variety":"number","vary":"change","vast":"adj","vegetable":"food","vehicle":"travel",
"venture":"biz","vertical":"number","very":"adv","via":"gram","victim":"law","victory":"sport",
"video":"media","view":"mind","village":"place","violence":"law","violent":"adj",
"violently":"adv","virtually":"adv","virus":"body","visible":"adj","vision":"mind",
"visitor":"people","vital":"adj","vocabulary":"edu","voice":"media","volume":"number","vote":"law",
})

# ── W / Y / Z ────────────────────────────────────────────────────────
MAP.update({
"waist":"body","wake up":"body","walking":"sport","wander":"action","war":"law","warm":"adj",
"warmth":"nature","warn":"mind","warning":"mind","wash":"home","washing":"home","waste":"change",
"wave":"nature","way":"mind","we":"gram","weakness":"body","wealth":"money","weapon":"law",
"wear":"clothes","web":"tech","website":"tech","wedding":"society","Wednesday":"time",
"weigh":"number","well":"adv","well known":"adj","west":"place","western":"place","wet":"adj",
"what":"gram","whatever":"gram","wheel":"travel","when":"gram","whenever":"gram","where":"gram",
"whereas":"gram","wherever":"gram","whether":"gram","which":"gram","while":"gram","whilst":"gram",
"whisper":"mind","whistle":"media","white":"adj","who":"gram","whoever":"gram","whom":"gram",
"whose":"gram","why":"gram","wide":"adj","widely":"adv","width":"number","wild":"adj",
"wildly":"adv","will":"gram","willing":"feel","willingly":"adv","willingness":"feel",
"wind":"nature","wine":"food","wing":"nature","winner":"sport","winning":"adj","winter":"time",
"wire":"tech","wise":"adj","wish":"feel","with":"gram","withdraw":"money","within":"gram",
"without":"gram","witness":"law","woman":"people","wonder":"mind","wonderful":"adj",
"wood":"tech","wooden":"adj","wool":"clothes","worker":"work","working":"adj","world":"place",
"worry":"feel","worrying":"adj","worse":"adj","worship":"society","worth":"money","would":"gram",
"wounded":"body","wrap":"action","wrapping":"biz","wrist":"body","writer":"media","writing":"edu",
"written":"adj","wrongly":"adv",
"yard":"number","yawn":"body","yellow":"adj","yes":"gram","you":"gram","your":"gram",
"yours":"gram","yourself":"gram","youth":"people","zero":"number","zone":"place",
})
