# -*- coding: utf-8 -*-
"""Ban dich tieng Viet cho 600 cau vi du bo core (data-vocab.js).
   Key = cau tieng Anh Y HET trong ex. Value = nghia tieng Viet."""
VN = {
"I go to the office every morning.": "Tôi đến văn phòng mỗi sáng.",
"Can you come to the meeting at 9?": "Bạn đến họp lúc 9 giờ được không?",
"I get a lot of emails every day.": "Tôi nhận rất nhiều email mỗi ngày.",
"Let's make a plan for next week.": "Mình lên kế hoạch cho tuần sau nhé.",
"The waiter takes the order on a tablet.": "Nhân viên phục vụ ghi món trên máy tính bảng.",
"What do you do for a living?": "Bạn làm nghề gì?",
"We have five outlets in the city.": "Chúng tôi có năm chi nhánh trong thành phố.",
"I see what you mean.": "Tôi hiểu ý bạn.",
"I know that company well.": "Tôi biết rõ công ty đó.",
"I think the price is fair.": "Tôi thấy giá đó hợp lý.",
"Do they want the POS or the KDS?": "Họ muốn máy tính tiền hay màn hình bếp?",
"You need a stable internet connection.": "Bạn cần đường mạng ổn định.",
"How many staff will use the system?": "Bao nhiêu nhân viên sẽ dùng hệ thống?",
"I can't find the receipt.": "Tôi không tìm thấy hóa đơn.",
"Let me give you a quick demo.": "Để tôi demo nhanh cho bạn xem.",
"Please tell me if you have a problem.": "Có vấn đề gì cứ nói tôi nhé.",
"It also works offline.": "Nó chạy được cả khi không có mạng.",
"I'll call you back this afternoon.": "Chiều nay tôi sẽ gọi lại cho bạn.",
"You can try it free for 14 days.": "Bạn dùng thử miễn phí 14 ngày.",
"Can I ask you a few questions?": "Tôi hỏi bạn vài câu được không?",
"I feel confident about this deal.": "Tôi tự tin về thương vụ này.",
"He became our biggest client.": "Anh ấy trở thành khách hàng lớn nhất của chúng tôi.",
"Don't leave before we sign.": "Đừng về trước khi mình ký nhé.",
"Put the tablet near the counter.": "Đặt máy tính bảng gần quầy.",
"What do you mean by that?": "Ý bạn là sao?",
"Keep the receipt for your records.": "Giữ hóa đơn lại để đối chiếu.",
"Let me check and get back to you.": "Để tôi kiểm tra rồi báo lại bạn.",
"We begin the installation next month.": "Tháng sau chúng tôi bắt đầu lắp đặt.",
"The client seems interested.": "Khách hàng có vẻ quan tâm.",
"How can I help you today?": "Hôm nay tôi giúp gì được cho bạn?",
"Can we talk about the price?": "Mình bàn về giá được không?",
"Turn on the tablet before the shift.": "Bật máy tính bảng trước ca làm.",
"Let's start the meeting.": "Mình bắt đầu họp nhé.",
"Let me show you the dashboard.": "Để tôi cho bạn xem bảng điều khiển.",
"Sorry, I didn't hear that.": "Xin lỗi, tôi nghe không rõ.",
"We play soft music in the café.": "Chúng tôi mở nhạc nhẹ trong quán.",
"She runs three coffee shops.": "Cô ấy điều hành ba quán cà phê.",
"Let's move to the next point.": "Mình chuyển sang ý tiếp theo.",
"I live in Ho Chi Minh City.": "Tôi sống ở Thành phố Hồ Chí Minh.",
"I believe this will help your business.": "Tôi tin điều này sẽ giúp ích cho việc kinh doanh của bạn.",
"Bring your laptop to the demo.": "Mang laptop đến buổi demo nhé.",
"What happened last month?": "Tháng trước đã xảy ra chuyện gì?",
"I'll write you a full quote.": "Tôi sẽ viết cho bạn một bảng báo giá đầy đủ.",
"Please sit, I'll be right with you.": "Mời ngồi, tôi sẽ ra ngay.",
"The waiter stands near the door.": "Nhân viên phục vụ đứng gần cửa.",
"You lose money from inventory mistakes.": "Bạn mất tiền vì sai sót trong kho.",
"Customers can pay by e-wallet.": "Khách có thể thanh toán bằng ví điện tử.",
"Nice to meet you.": "Rất vui được gặp bạn.",
"The fee includes training and support.": "Phí đã bao gồm đào tạo và hỗ trợ.",
"Let's continue after lunch.": "Mình tiếp tục sau bữa trưa nhé.",
"I'll send you the contract tomorrow.": "Mai tôi sẽ gửi hợp đồng cho bạn.",
"Did you receive my email?": "Bạn nhận được email của tôi chưa?",
"I manage a small sales team.": "Tôi quản lý một nhóm bán hàng nhỏ.",
"I lead the sales team in the south.": "Tôi phụ trách nhóm bán hàng ở miền Nam.",
"We sell software to restaurants.": "Chúng tôi bán phần mềm cho nhà hàng.",
"Most owners buy the yearly plan.": "Phần lớn chủ quán mua gói theo năm.",
"We deliver the setup in three weeks.": "Chúng tôi lắp đặt xong trong ba tuần.",
"We install the POS on site.": "Chúng tôi lắp máy tính tiền tại chỗ.",
"Our team can fix the issue remotely.": "Nhóm chúng tôi có thể xử lý sự cố từ xa.",
"Let me check with my manager.": "Để tôi hỏi lại quản lý của tôi.",
"Let me confirm what we agreed.": "Để tôi xác nhận lại những gì mình đã thống nhất.",
"We agree on the payment terms.": "Chúng ta thống nhất về điều khoản thanh toán.",
"I'll arrange a demo for your team.": "Tôi sẽ sắp xếp một buổi demo cho nhóm của bạn.",
"Let me explain the price structure.": "Để tôi giải thích cơ cấu giá.",
"Can we discuss this next week?": "Mình bàn chuyện này vào tuần sau được không?",
"When can you decide?": "Khi nào bạn quyết định được?",
"We plan to open two new branches.": "Chúng tôi định mở thêm hai chi nhánh mới.",
"I'll prepare a demo for Friday.": "Tôi sẽ chuẩn bị buổi demo vào thứ Sáu.",
"She reports to me every Monday.": "Cô ấy báo cáo cho tôi mỗi thứ Hai.",
"Please contact me if you have questions.": "Có thắc mắc gì cứ liên hệ tôi nhé.",
"We train your staff in two sessions.": "Chúng tôi đào tạo nhân viên của bạn trong hai buổi.",
"We need to hire two more people.": "Chúng ta cần tuyển thêm hai người.",
"I want to promote her to team lead.": "Tôi muốn thăng chức cho cô ấy lên trưởng nhóm.",
"I'll join your demo with the client.": "Tôi sẽ tham gia buổi demo với khách cùng bạn.",
"He closed two deals this month.": "Tháng này anh ấy chốt được hai hợp đồng.",
"We want to increase revenue by 20%.": "Chúng tôi muốn tăng doanh thu thêm 20%.",
"This reduces your inventory costs.": "Điều này giúp giảm chi phí kho của bạn.",
"It saves you two hours a day.": "Nó giúp bạn tiết kiệm hai tiếng mỗi ngày.",
"How much do you spend on software now?": "Hiện giờ bạn chi bao nhiêu cho phần mềm?",
"The shop earns more during peak hours.": "Quán kiếm được nhiều hơn vào giờ cao điểm.",
"We charge a monthly fee per outlet.": "Chúng tôi thu phí theo tháng cho mỗi chi nhánh.",
"I'd like to book a demo for Monday.": "Tôi muốn đặt lịch demo vào thứ Hai.",
"You can cancel anytime in the first month.": "Bạn có thể hủy bất cứ lúc nào trong tháng đầu.",
"Has your job changed since you started?": "Công việc của bạn có thay đổi so với lúc mới bắt đầu không?",
"I want to improve my English.": "Tôi muốn cải thiện tiếng Anh.",
"Our system solves the paper problem.": "Hệ thống của chúng tôi giải quyết chuyện giấy tờ.",
"Can your staff handle the tablet?": "Nhân viên của bạn dùng được máy tính bảng không?",
"We provide software for cafés.": "Chúng tôi cung cấp phần mềm cho quán cà phê.",
"I suggest we start with two outlets.": "Tôi đề xuất mình bắt đầu với hai chi nhánh.",
"I recommend the yearly plan.": "Tôi khuyên nên chọn gói theo năm.",
"Expensive compared to what?": "Đắt so với cái gì?",
"You can choose the modules you need.": "Bạn có thể chọn những tính năng mình cần.",
"Do you accept these terms?": "Bạn đồng ý với các điều khoản này chứ?",
"He refused the first offer.": "Anh ấy từ chối lời đề nghị đầu tiên.",
"Customers complain about slow service.": "Khách phàn nàn về việc phục vụ chậm.",
"I apologize for the delay.": "Tôi xin lỗi vì sự chậm trễ.",
"Please remind me before Friday.": "Nhắc tôi trước thứ Sáu nhé.",
"Let's schedule the go-live.": "Mình lên lịch ngày chạy chính thức nhé.",
"We can negotiate the price.": "Chúng ta có thể thương lượng về giá.",
"Both teams cooperate on the setup.": "Cả hai nhóm phối hợp trong việc lắp đặt.",
"My name is Thuy.": "Tôi tên là Thúy.",
"People of all ages use our app.": "Mọi lứa tuổi đều dùng ứng dụng của chúng tôi.",
"I really enjoy my job.": "Tôi rất thích công việc của mình.",
"My hometown is a small town in the north.": "Quê tôi là một thị trấn nhỏ ở miền Bắc.",
"I have a small family.": "Tôi có một gia đình nhỏ.",
"My parents live in the countryside.": "Bố mẹ tôi sống ở quê.",
"My mother is a teacher.": "Mẹ tôi là giáo viên.",
"My father ran a small shop.": "Bố tôi từng mở một cửa hàng nhỏ.",
"My brother works in marketing.": "Anh trai tôi làm trong ngành marketing.",
"I have one older sister.": "Tôi có một chị gái.",
"I have two siblings.": "Tôi có hai anh chị em.",
"They have a son and a daughter.": "Họ có một con trai và một con gái.",
"My daughter is five years old.": "Con gái tôi năm tuổi.",
"Every child in the family speaks English.": "Mọi đứa trẻ trong nhà đều nói được tiếng Anh.",
"The café is popular with families and kids.": "Quán được các gia đình và trẻ nhỏ ưa thích.",
"My wife also works in sales.": "Vợ tôi cũng làm nghề bán hàng.",
"Her husband owns two restaurants.": "Chồng cô ấy sở hữu hai nhà hàng.",
"I'm married with one child.": "Tôi đã kết hôn và có một con.",
"He is single and lives alone.": "Anh ấy độc thân và sống một mình.",
"My cousin helped me start the business.": "Anh họ tôi đã giúp tôi khởi nghiệp.",
"My uncle owns a coffee farm.": "Chú tôi có một nông trại cà phê.",
"My aunt lives near my office.": "Cô tôi sống gần văn phòng tôi.",
"My grandparents live in Hue.": "Ông bà tôi sống ở Huế.",
"My grandmother cooks very well.": "Bà tôi nấu ăn rất ngon.",
"My grandfather taught me to work hard.": "Ông tôi dạy tôi phải chăm chỉ.",
"A friend introduced me to this client.": "Một người bạn đã giới thiệu tôi với khách hàng này.",
"My neighbor runs a small bakery.": "Hàng xóm của tôi mở một tiệm bánh nhỏ.",
"Let me check with my boss.": "Để tôi hỏi lại sếp của tôi.",
"My colleague will join the call.": "Đồng nghiệp của tôi sẽ tham gia cuộc gọi.",
"I lead a team of five.": "Tôi phụ trách một nhóm năm người.",
"My hobby is cycling on weekends.": "Sở thích của tôi là đạp xe vào cuối tuần.",
"I take an English class every weekend.": "Tôi học một lớp tiếng Anh mỗi cuối tuần.",
"We give customers a gift on their birthday.": "Chúng tôi tặng quà cho khách vào ngày sinh nhật.",
"Good sleep is important for your health.": "Ngủ đủ giấc rất quan trọng cho sức khỏe.",
"He is tall and easy to notice.": "Anh ấy cao và dễ nhận ra.",
"Let's keep the meeting short.": "Mình họp ngắn gọn thôi nhé.",
"Most of my team are young.": "Phần lớn nhóm tôi đều trẻ.",
"Their old system is very slow.": "Hệ thống cũ của họ rất chậm.",
"She is kind to every customer.": "Cô ấy tử tế với mọi khách hàng.",
"Our staff are friendly and helpful.": "Nhân viên của chúng tôi thân thiện và nhiệt tình.",
"To be honest, I'm not sure.": "Thành thật mà nói, tôi không chắc.",
"You must be patient with new staff.": "Bạn phải kiên nhẫn với nhân viên mới.",
"I was shy when I started selling.": "Tôi từng rụt rè khi mới bắt đầu bán hàng.",
"He is funny and easy to talk to.": "Anh ấy vui tính và dễ nói chuyện.",
"She is smart and learns fast.": "Cô ấy thông minh và học nhanh.",
"My team is young but hard-working.": "Nhóm tôi trẻ nhưng chăm chỉ.",
"He is generous with tips.": "Anh ấy hào phóng tiền boa.",
"Always be polite on the phone.": "Luôn lịch sự khi nói chuyện điện thoại.",
"Stay calm when a customer complains.": "Giữ bình tĩnh khi khách phàn nàn.",
"I live in a house with my family.": "Tôi sống trong một ngôi nhà cùng gia đình.",
"I live in a small apartment downtown.": "Tôi sống trong một căn hộ nhỏ ở trung tâm.",
"The meeting room is on the third floor.": "Phòng họp ở tầng ba.",
"The kitchen sees the order immediately.": "Bếp thấy đơn hàng ngay lập tức.",
"My bedroom is also my home office.": "Phòng ngủ của tôi cũng là nơi làm việc tại nhà.",
"The restaurant has a clean bathroom.": "Nhà hàng có nhà vệ sinh sạch sẽ.",
"I like a table by the window.": "Tôi thích bàn cạnh cửa sổ.",
"We manage every table from one screen.": "Chúng tôi quản lý mọi bàn từ một màn hình.",
"Please have a chair.": "Mời bạn ngồi ghế.",
"Get out of bed and speak English.": "Ra khỏi giường và nói tiếng Anh đi.",
"My desk is always full of papers.": "Bàn làm việc của tôi lúc nào cũng đầy giấy tờ.",
"The owner checks revenue on his phone.": "Chủ quán xem doanh thu trên điện thoại.",
"People or computers — which is better?": "Con người hay máy móc — cái nào tốt hơn?",
"Listening is the key skill in sales.": "Lắng nghe là kỹ năng then chốt trong bán hàng.",
"I keep a tablet in my bag.": "Tôi để một máy tính bảng trong túi.",
"Now people pay without a wallet.": "Bây giờ người ta thanh toán mà không cần ví.",
"There's a clock above the counter.": "Có một chiếc đồng hồ phía trên quầy.",
"Turn off the lights after closing.": "Tắt đèn sau khi đóng cửa.",
"Can I get you some water?": "Tôi lấy nước cho bạn nhé?",
"The food comes out faster with the KDS.": "Món ăn ra nhanh hơn nhờ màn hình bếp.",
"We sell software to coffee chains.": "Chúng tôi bán phần mềm cho các chuỗi cà phê.",
"Would you like tea or coffee?": "Bạn dùng trà hay cà phê?",
"I go to clients by car.": "Tôi đi gặp khách bằng ô tô.",
"Most staff come to work by motorbike.": "Phần lớn nhân viên đi làm bằng xe máy.",
"There are many cafés on this street.": "Trên con phố này có nhiều quán cà phê.",
"We work in every big city in Vietnam.": "Chúng tôi hoạt động ở mọi thành phố lớn tại Việt Nam.",
"The coffee chain is in District 3.": "Chuỗi cà phê đó ở Quận 3.",
"Our office is in that building.": "Văn phòng chúng tôi ở trong tòa nhà đó.",
"The demo is on the fifth floor.": "Buổi demo ở tầng năm.",
"The menu is on the wall.": "Thực đơn treo trên tường.",
"Staff wear clean clothes on shift.": "Nhân viên mặc đồng phục sạch khi vào ca.",
"Wear comfortable shoes for a long shift.": "Mang giày thoải mái cho ca làm dài.",
"He looked at his watch and left.": "Anh ấy nhìn đồng hồ rồi đi.",
"I wear glasses when I read.": "Tôi đeo kính khi đọc.",
"We give umbrellas to loyal customers.": "Chúng tôi tặng ô cho khách hàng thân thiết.",
"The drinks are in the fridge.": "Đồ uống ở trong tủ lạnh.",
"Turn on the fan, it's hot.": "Bật quạt lên, nóng quá.",
"The café has a strong air conditioner.": "Quán có máy lạnh rất mát.",
"There's a television in the waiting area.": "Có một chiếc tivi ở khu vực chờ.",
"We can fix it by remote.": "Chúng tôi có thể xử lý từ xa.",
"Don't forget your charger.": "Đừng quên mang bộ sạc.",
"If the internet is down, you can still sell.": "Nếu mất mạng, bạn vẫn bán hàng được.",
"We offer free wifi for guests.": "Chúng tôi có wifi miễn phí cho khách.",
"The tablet battery lasts all day.": "Pin máy tính bảng dùng được cả ngày.",
"The kitchen sees the order on a screen.": "Bếp thấy đơn hàng trên màn hình.",
"Press this button to print the bill.": "Nhấn nút này để in hóa đơn.",
"The cash is in the drawer.": "Tiền mặt ở trong ngăn kéo.",
"We track every item on the shelf.": "Chúng tôi theo dõi từng mặt hàng trên kệ.",
"The customer is always in a hurry.": "Khách hàng lúc nào cũng vội.",
"Let's set up a meeting for Monday.": "Mình sắp xếp một cuộc họp vào thứ Hai nhé.",
"Please update the pipeline before the deadline.": "Cập nhật danh sách khách tiềm năng trước hạn chót nhé.",
"This project has three phases.": "Dự án này có ba giai đoạn.",
"Each person has a clear task.": "Mỗi người có một nhiệm vụ rõ ràng.",
"I'll send you the details by email.": "Tôi sẽ gửi chi tiết cho bạn qua email.",
"The file is too big to send.": "Tệp quá lớn để gửi đi.",
"Keep the contracts in one folder.": "Để các hợp đồng trong một thư mục.",
"I attached the document to the email.": "Tôi đã đính kèm tài liệu vào email.",
"All your data is safe in the cloud.": "Toàn bộ dữ liệu của bạn được lưu an toàn trên đám mây.",
"The owner opens the app on his phone.": "Chủ quán mở ứng dụng trên điện thoại.",
"We provide software for restaurants.": "Chúng tôi cung cấp phần mềm cho nhà hàng.",
"The hardware includes a tablet and a printer.": "Phần cứng gồm một máy tính bảng và một máy in.",
"What system are you using now?": "Hiện giờ bạn đang dùng hệ thống nào?",
"We create an account for each outlet.": "Chúng tôi tạo một tài khoản cho mỗi chi nhánh.",
"Please change your password every month.": "Đổi mật khẩu mỗi tháng nhé.",
"Each staff has their own login.": "Mỗi nhân viên có tài khoản đăng nhập riêng.",
"The dashboard shows revenue by branch.": "Bảng điều khiển hiển thị doanh thu theo từng chi nhánh.",
"Last month we launched a new feature.": "Tháng trước chúng tôi ra mắt một tính năng mới.",
"The new version is faster.": "Phiên bản mới chạy nhanh hơn.",
"We fixed the bug this morning.": "Chúng tôi đã sửa lỗi sáng nay.",
"If you have any issue, tell me.": "Có vấn đề gì cứ nói tôi.",
"The screen showed an error.": "Màn hình báo lỗi.",
"The data is stored in the cloud.": "Dữ liệu được lưu trên đám mây.",
"The server was down for a minute.": "Máy chủ gặp sự cố trong một phút.",
"All orders go into one database.": "Mọi đơn hàng đều vào chung một cơ sở dữ liệu.",
"We make a backup every night.": "Chúng tôi sao lưu mỗi đêm.",
"It works on any device.": "Nó chạy được trên mọi thiết bị.",
"How many users will you have?": "Bạn sẽ có bao nhiêu người dùng?",
"You can change the tax in the settings.": "Bạn có thể đổi thuế trong phần cài đặt.",
"Orders sync to the cloud in real time.": "Đơn hàng đồng bộ lên đám mây theo thời gian thực.",
"We deploy the update overnight.": "Chúng tôi cập nhật hệ thống qua đêm.",
"The kitchen gets a notification for each order.": "Bếp nhận thông báo cho mỗi đơn hàng.",
"I'll send you a message when it's ready.": "Xong tôi sẽ nhắn tin cho bạn.",
"I'll send you the link to the demo.": "Tôi sẽ gửi bạn đường dẫn tới buổi demo.",
"You can download the report as a PDF.": "Bạn có thể tải báo cáo về dưới dạng PDF.",
"Upload your menu photos here.": "Tải ảnh thực đơn của bạn lên đây.",
"The bill goes straight to the printer.": "Hóa đơn được gửi thẳng tới máy in.",
"A weak network slows everything down.": "Mạng yếu làm mọi thứ chậm lại.",
"Security is very important for payments.": "Bảo mật rất quan trọng đối với thanh toán.",
"The manager has full access.": "Quản lý có toàn quyền truy cập.",
"Staff need permission to give a discount.": "Nhân viên cần được cho phép mới được giảm giá.",
"I used to track sales in a spreadsheet.": "Trước đây tôi theo dõi doanh số bằng bảng tính.",
"The chart shows sales going up.": "Biểu đồ cho thấy doanh số đang tăng.",
"I'll prepare a short presentation.": "Tôi sẽ chuẩn bị một bài trình bày ngắn.",
"Set a reminder for the follow-up call.": "Đặt nhắc nhở cho cuộc gọi theo dõi.",
"Our system fits your daily workflow.": "Hệ thống của chúng tôi phù hợp với quy trình hằng ngày của bạn.",
"The quote is in the attachment.": "Bảng báo giá nằm trong tệp đính kèm.",
"We work with restaurants of all sizes.": "Chúng tôi làm việc với nhà hàng đủ mọi quy mô.",
"This café has twenty branches.": "Quán cà phê này có hai mươi chi nhánh.",
"The waitress brings the bill to the table.": "Nữ phục vụ mang hóa đơn ra bàn.",
"The chef sees the order on the screen.": "Bếp trưởng thấy đơn hàng trên màn hình.",
"The cook prepares the dish quickly.": "Đầu bếp chuẩn bị món ăn nhanh gọn.",
"We seat the guest by the window.": "Chúng tôi xếp khách ngồi cạnh cửa sổ.",
"Can I have the bill, please?": "Cho tôi xin hóa đơn nhé?",
"He left a big tip.": "Anh ấy để lại tiền boa hậu hĩnh.",
"This dish is our best seller.": "Món này là món bán chạy nhất của chúng tôi.",
"Would you like a drink first?": "Bạn dùng đồ uống trước nhé?",
"A full meal takes about thirty minutes.": "Một bữa đầy đủ mất khoảng ba mươi phút.",
"We serve breakfast from seven.": "Chúng tôi phục vụ bữa sáng từ bảy giờ.",
"Lunch is our peak hour.": "Buổi trưa là giờ cao điểm của chúng tôi.",
"Let's continue after dinner.": "Mình tiếp tục sau bữa tối nhé.",
"One espresso, please.": "Cho tôi một ly espresso.",
"A latte is their most popular drink.": "Latte là món được ưa chuộng nhất của họ.",
"She ordered a cappuccino.": "Cô ấy gọi một ly cappuccino.",
"Fresh orange juice is on the menu.": "Nước cam tươi có trong thực đơn.",
"Their mango smoothie sells well.": "Sinh tố xoài của họ bán rất chạy.",
"Would you like ice with that?": "Bạn có muốn thêm đá không?",
"No sugar in my coffee, please.": "Cà phê của tôi không đường nhé.",
"We ran out of milk this morning.": "Sáng nay chúng tôi hết sữa.",
"The bread is baked fresh every day.": "Bánh mì được nướng mới mỗi ngày.",
"A slice of cake goes with the coffee.": "Một miếng bánh ăn kèm với cà phê.",
"Rice comes with every main dish.": "Mỗi món chính đều kèm cơm.",
"Their noodle soup is famous.": "Món phở của họ nổi tiếng.",
"The soup of the day is pumpkin.": "Món súp trong ngày là súp bí đỏ.",
"Each dish has its own sauce.": "Mỗi món có loại nước sốt riêng.",
"Is this dish spicy?": "Món này có cay không?",
"The dessert is very sweet.": "Món tráng miệng rất ngọt.",
"We use fresh ingredients only.": "Chúng tôi chỉ dùng nguyên liệu tươi.",
"The food here is delicious.": "Đồ ăn ở đây rất ngon.",
"We serve about 200 guests a day.": "Chúng tôi phục vụ khoảng 200 khách mỗi ngày.",
"The portion is large for the price.": "Khẩu phần lớn so với giá tiền.",
"Do you have a reservation?": "Bạn đã đặt bàn chưa?",
"The system manages every booking.": "Hệ thống quản lý mọi lượt đặt chỗ.",
"Is this for takeaway or dine-in?": "Cái này mang đi hay dùng tại chỗ?",
"We connect to every delivery app.": "Chúng tôi kết nối với mọi ứng dụng giao hàng.",
"Please pay at the counter.": "Vui lòng thanh toán ở quầy.",
"The cashier uses the POS all day.": "Thu ngân dùng máy tính tiền suốt cả ngày.",
"She works the morning shift.": "Cô ấy làm ca sáng.",
"Every drink has a fixed recipe.": "Mỗi loại đồ uống có công thức cố định.",
"We track every ingredient in stock.": "Chúng tôi theo dõi từng nguyên liệu trong kho.",
"Put a napkin with every order.": "Kèm một chiếc khăn giấy cho mỗi đơn.",
"The waiter carries drinks on a tray.": "Nhân viên phục vụ bưng đồ uống trên khay.",
"Can I see the menu, please?": "Cho tôi xem thực đơn được không?",
"We also sell light snacks.": "Chúng tôi cũng bán đồ ăn nhẹ.",
"Would you like a dessert?": "Bạn dùng món tráng miệng nhé?",
"The system is fast even in peak hours.": "Hệ thống chạy nhanh ngay cả trong giờ cao điểm.",
"We had a good month for sales.": "Chúng tôi có một tháng bán hàng tốt.",
"I'll send you a full proposal.": "Tôi sẽ gửi bạn một bản đề xuất đầy đủ.",
"The main benefit is saving time.": "Lợi ích chính là tiết kiệm thời gian.",
"The software pays for itself in value.": "Phần mềm tự bù lại chi phí bằng giá trị nó mang lại.",
"We offer a complete solution.": "Chúng tôi cung cấp một giải pháp trọn gói.",
"What is the biggest problem with it?": "Vấn đề lớn nhất của nó là gì?",
"Our goal is fifteen new leads.": "Mục tiêu của chúng tôi là mười lăm khách tiềm năng mới.",
"The results were better than last month.": "Kết quả tốt hơn tháng trước.",
"The team earns a commission on each deal.": "Nhóm được hưởng hoa hồng trên mỗi hợp đồng.",
"Small savings become real profit.": "Những khoản tiết kiệm nhỏ trở thành lợi nhuận thật.",
"F&B margins are usually thin.": "Biên lợi nhuận ngành F&B thường rất mỏng.",
"I know that competitor well.": "Tôi biết rõ đối thủ đó.",
"The F&B market is growing fast.": "Thị trường F&B đang tăng trưởng nhanh.",
"They want to grow the brand.": "Họ muốn phát triển thương hiệu.",
"You can't sell a product you can't name.": "Bạn không thể bán một sản phẩm mà bạn không gọi tên được.",
"The monthly fee includes support and service.": "Phí hằng tháng đã bao gồm hỗ trợ và dịch vụ.",
"Quality matters more than price here.": "Ở đây chất lượng quan trọng hơn giá.",
"We guarantee support within 24 hours.": "Chúng tôi cam kết hỗ trợ trong vòng 24 giờ.",
"The hardware has a one-year warranty.": "Phần cứng được bảo hành một năm.",
"We offer a refund in the first week.": "Chúng tôi hoàn tiền trong tuần đầu tiên.",
"I'll send the invoice by email.": "Tôi sẽ gửi hóa đơn qua email.",
"You can pay in monthly installments.": "Bạn có thể trả góp theo tháng.",
"The negotiation went well.": "Cuộc thương lượng diễn ra suôn sẻ.",
"The most common objection is price.": "Phản đối thường gặp nhất là về giá.",
"Let me confirm our agreement.": "Để tôi xác nhận lại thỏa thuận của chúng ta.",
"There is one condition for the discount.": "Có một điều kiện để được giảm giá.",
"This is a good opportunity for both of us.": "Đây là cơ hội tốt cho cả hai bên.",
"When will you make a decision?": "Khi nào bạn sẽ ra quyết định?",
"My manager has to approve the discount.": "Quản lý của tôi phải duyệt mức giảm giá này.",
"They rejected the first price.": "Họ từ chối mức giá đầu tiên.",
"A two-year commitment lowers the price.": "Cam kết hai năm sẽ giảm được giá.",
"We see you as a long-term partner.": "Chúng tôi xem bạn là đối tác lâu dài.",
"Sales is about building a relationship.": "Bán hàng là xây dựng mối quan hệ.",
"Trust comes before any big deal.": "Niềm tin có trước mọi hợp đồng lớn.",
"Loyal customers get a discount.": "Khách hàng thân thiết được giảm giá.",
"Most new clients come from referrals.": "Phần lớn khách mới đến từ giới thiệu.",
"We upsell the inventory module later.": "Chúng tôi bán thêm tính năng quản lý kho sau.",
"Working offline is a big advantage.": "Chạy được khi không có mạng là một lợi thế lớn.",
"There's no risk in a free trial.": "Dùng thử miễn phí thì chẳng có rủi ro gì.",
"We want a win-win deal.": "Chúng tôi muốn một thỏa thuận đôi bên cùng có lợi.",
"The demo convinced the owner.": "Buổi demo đã thuyết phục được chủ quán.",
"Don't push; persuade with numbers.": "Đừng ép; hãy thuyết phục bằng con số.",
"My pitch takes about 60 seconds.": "Bài chào hàng của tôi mất khoảng 60 giây.",
"I have three hot prospects this week.": "Tuần này tôi có ba khách tiềm năng nóng.",
"That's my best offer.": "Đó là mức tốt nhất tôi có thể đưa ra.",
"At this price, it's a bargain.": "Với giá này thì quá hời.",
"We give an incentive for signing early.": "Chúng tôi có ưu đãi cho việc ký sớm.",
"I can give you a reference to call.": "Tôi có thể cho bạn một khách để gọi tham khảo.",
"High staff turnover is a real cost.": "Nhân viên nghỉ việc nhiều là một chi phí thật sự.",
"How much money do you lose each month?": "Mỗi tháng bạn mất bao nhiêu tiền?",
"Some guests still pay in cash.": "Một số khách vẫn trả bằng tiền mặt.",
"Can I pay by card?": "Tôi trả bằng thẻ được không?",
"Keep some coins for change.": "Giữ ít tiền lẻ để thối lại.",
"The total amount is on the bill.": "Tổng số tiền có trên hóa đơn.",
"The total comes to two million.": "Tổng cộng là hai triệu.",
"Most restaurants lose three to five percent.": "Phần lớn nhà hàng thất thoát ba đến năm phần trăm.",
"Let me show you the numbers.": "Để tôi cho bạn xem các con số.",
"Their price is cheaper, but slower.": "Giá của họ rẻ hơn, nhưng chậm hơn.",
"We pay a fair salary plus commission.": "Chúng tôi trả lương hợp lý cộng hoa hồng.",
"The app grows their income.": "Ứng dụng giúp tăng thu nhập của họ.",
"The system prints a VAT invoice with tax.": "Hệ thống in hóa đơn VAT có thuế.",
"The money goes straight to the bank.": "Tiền được chuyển thẳng vào ngân hàng.",
"They took a loan to open a new branch.": "Họ vay tiền để mở chi nhánh mới.",
"Small shops can afford our basic plan.": "Các quán nhỏ đủ khả năng chi trả gói cơ bản của chúng tôi.",
"They make about ten million a day.": "Họ kiếm khoảng mười triệu một ngày.",
"The setup fee is a few thousand.": "Phí lắp đặt là vài nghìn.",
"We serve a few hundred guests a day.": "Chúng tôi phục vụ vài trăm khách mỗi ngày.",
"They order a dozen boxes a week.": "Họ đặt một tá thùng mỗi tuần.",
"Another company offers half the price.": "Một công ty khác chào giá bằng một nửa.",
"Sales went up this quarter.": "Doanh số tăng trong quý này.",
"They doubled their outlets in a year.": "Họ tăng gấp đôi số chi nhánh trong một năm.",
"The system saves you time.": "Hệ thống giúp bạn tiết kiệm thời gian.",
"It saves two hours every day.": "Nó tiết kiệm hai tiếng mỗi ngày.",
"The demo takes ten minutes.": "Buổi demo mất mười phút.",
"The kitchen sees the order in seconds.": "Bếp thấy đơn hàng chỉ trong vài giây.",
"At the end of the day, check the revenue.": "Cuối ngày, hãy kiểm tra doanh thu.",
"We go live in three weeks.": "Chúng tôi chạy chính thức sau ba tuần.",
"The fee is per outlet per month.": "Phí tính theo mỗi chi nhánh mỗi tháng.",
"Sign for one year and the fee is lower.": "Ký một năm thì phí sẽ thấp hơn.",
"I'll send the contract tomorrow.": "Mai tôi sẽ gửi hợp đồng.",
"We closed the deal yesterday.": "Hôm qua chúng tôi đã chốt hợp đồng.",
"Good morning, everyone.": "Chào buổi sáng cả nhà.",
"The dinner rush starts in the evening.": "Giờ cao điểm bữa tối bắt đầu vào buổi chiều tối.",
"Sign early to get the discount.": "Ký sớm để được giảm giá.",
"Sorry I'm late for the meeting.": "Xin lỗi vì tôi đến họp muộn.",
"I'll get back to you soon.": "Tôi sẽ sớm phản hồi bạn.",
"How many outlets do you have now?": "Hiện giờ bạn có bao nhiêu chi nhánh?",
"She sends a weekly report.": "Cô ấy gửi báo cáo hằng tuần.",
"There's a small monthly fee.": "Có một khoản phí nhỏ hằng tháng.",
"The yearly plan is cheaper.": "Gói theo năm rẻ hơn.",
"What's the go-live date?": "Ngày chạy chính thức là khi nào?",
"Let's start at nine o'clock.": "Mình bắt đầu lúc chín giờ nhé.",
"The trial period is two weeks.": "Thời gian dùng thử là hai tuần.",
"Part-time staff get an hourly wage.": "Nhân viên bán thời gian được trả lương theo giờ.",
"I'm happy with the result.": "Tôi hài lòng với kết quả.",
"He looked sad after losing the deal.": "Anh ấy trông buồn sau khi mất hợp đồng.",
"I'm not angry, I want you to succeed.": "Tôi không giận, tôi muốn bạn thành công.",
"The staff are tired after peak hours.": "Nhân viên mệt sau giờ cao điểm.",
"Sorry, I'm a bit busy this week.": "Xin lỗi, tuần này tôi hơi bận.",
"I'm excited about the new feature.": "Tôi rất háo hức với tính năng mới.",
"Customers get bored waiting for the bill.": "Khách thấy chán khi phải chờ tính tiền.",
"I understand you're worried about the budget.": "Tôi hiểu bạn lo lắng về ngân sách.",
"I was nervous before my first pitch.": "Tôi hồi hộp trước bài chào hàng đầu tiên.",
"Is your job stressful?": "Công việc của bạn có căng thẳng không?",
"The café has a relaxed atmosphere.": "Quán có không khí thư giãn.",
"I was surprised by the low price.": "Tôi bất ngờ vì mức giá thấp.",
"Don't be scared to speak English.": "Đừng sợ nói tiếng Anh.",
"I'm proud of my team.": "Tôi tự hào về nhóm của mình.",
"The client was disappointed with support.": "Khách hàng thất vọng về khâu hỗ trợ.",
"Are you comfortable with these terms?": "Bạn thấy thoải mái với các điều khoản này chứ?",
"The owner seems interested.": "Chủ quán có vẻ quan tâm.",
"I'm curious about your current system.": "Tôi tò mò về hệ thống hiện tại của bạn.",
"I'm grateful for your time today.": "Tôi biết ơn vì bạn đã dành thời gian hôm nay.",
"Working from home can feel lonely.": "Làm việc ở nhà đôi khi thấy cô đơn.",
"Guests get annoyed by slow service.": "Khách khó chịu vì phục vụ chậm.",
"She was upset about the mistake.": "Cô ấy buồn bực về sai sót đó.",
"I'm glad we could meet today.": "Tôi vui vì hôm nay mình gặp được nhau.",
"I'm hopeful about this quarter.": "Tôi kỳ vọng vào quý này.",
"A good bonus keeps the team motivated.": "Tiền thưởng tốt giữ cho nhóm có động lực.",
"Are you serious about signing this month?": "Bạn có thật sự muốn ký trong tháng này không?",
"Our security rules are strict.": "Quy định bảo mật của chúng tôi rất chặt.",
"He's not lazy, he needs training.": "Anh ấy không lười, chỉ cần được đào tạo.",
"Be brave and make the call.": "Hãy mạnh dạn gọi điện đi.",
"Be careful with the price promise.": "Cẩn thận với lời hứa về giá.",
"One careless mistake can lose a client.": "Một sai sót bất cẩn có thể làm mất khách.",
"She has creative ideas for the menu.": "Cô ấy có nhiều ý tưởng sáng tạo cho thực đơn.",
"They have an ambitious growth plan.": "Họ có một kế hoạch tăng trưởng đầy tham vọng.",
"Our support is reliable and fast.": "Hỗ trợ của chúng tôi đáng tin và nhanh.",
"Our plans are flexible for small shops.": "Các gói của chúng tôi linh hoạt cho quán nhỏ.",
"Keep a positive tone on the call.": "Giữ giọng điệu tích cực khi gọi điện.",
"Don't focus on the negative points.": "Đừng chăm chăm vào những điểm tiêu cực.",
"Mornings are quiet in the café.": "Buổi sáng quán khá vắng.",
"Speak loud and clear in the demo.": "Nói to và rõ trong buổi demo.",
"Be gentle when you correct staff.": "Nhẹ nhàng khi góp ý cho nhân viên.",
"Never be rude to a customer.": "Đừng bao giờ thô lỗ với khách hàng.",
"We have a strong support team.": "Chúng tôi có một đội hỗ trợ mạnh.",
"My grammar is still weak.": "Ngữ pháp của tôi vẫn còn yếu.",
"The staff were very helpful.": "Nhân viên rất nhiệt tình.",
"The boss is in a good mood today.": "Hôm nay sếp đang vui.",
"Don't let a guilty feeling stop you.": "Đừng để cảm giác áy náy cản bạn lại.",
"A good attitude sells more than words.": "Thái độ tốt bán được hàng hơn cả lời nói.",
"I'm afraid the price is a bit high.": "Tôi e là giá hơi cao.",
"Don't be embarrassed to say it again.": "Đừng ngại nói lại lần nữa.",
"I like it because I meet many people.": "Tôi thích nó vì được gặp nhiều người.",
"It's cheaper, but much slower.": "Nó rẻ hơn, nhưng chậm hơn nhiều.",
"No paper, so no mistakes.": "Không giấy tờ nên không sai sót.",
"However, the price is a bit high.": "Tuy nhiên, giá hơi cao.",
"Although it's new, it's stable.": "Dù còn mới nhưng nó ổn định.",
"It works well, though it costs more.": "Nó chạy tốt, dù giá đắt hơn.",
"Actually, sales is about listening.": "Thật ra, bán hàng là biết lắng nghe.",
"Honestly, I've never thought about that.": "Thành thật mà nói, tôi chưa từng nghĩ đến điều đó.",
"Basically, it has three parts.": "Về cơ bản, nó có ba phần.",
"I usually start work at eight.": "Tôi thường bắt đầu làm việc lúc tám giờ.",
"Do you often eat at restaurants?": "Bạn có hay ăn ở nhà hàng không?",
"Sometimes the problem is me.": "Đôi khi vấn đề nằm ở chính tôi.",
"I never push a client too hard.": "Tôi không bao giờ ép khách quá mức.",
"Maybe we can start with two outlets.": "Có lẽ mình có thể bắt đầu với hai chi nhánh.",
"They'll probably decide next week.": "Chắc tuần sau họ sẽ quyết định.",
"We can definitely do that for you.": "Chúng tôi chắc chắn làm được điều đó cho bạn.",
"It helps, especially during peak hours.": "Nó có ích, nhất là vào giờ cao điểm.",
"Finally, let me confirm the terms.": "Cuối cùng, để tôi xác nhận lại các điều khoản.",
"Suddenly the internet went down.": "Đột nhiên mất mạng.",
"The kitchen sees the order quickly.": "Bếp thấy đơn hàng nhanh chóng.",
"Please speak slowly, my English is basic.": "Xin nói chậm thôi, tiếng Anh của tôi còn cơ bản.",
"Read the contract carefully.": "Đọc kỹ hợp đồng.",
"We've already fixed the bug.": "Chúng tôi đã sửa lỗi rồi.",
"They haven't decided yet.": "Họ vẫn chưa quyết định.",
"I don't have the KDS either.": "Tôi cũng không có màn hình bếp.",
"Use a tablet instead of paper.": "Dùng máy tính bảng thay cho giấy.",
"It saves time; therefore it saves money.": "Nó tiết kiệm thời gian; nhờ vậy tiết kiệm tiền.",
"Sign this week; otherwise the price changes.": "Ký trong tuần này; nếu không giá sẽ thay đổi.",
"Besides, you get free training.": "Ngoài ra, bạn còn được đào tạo miễn phí.",
"Anyway, let's continue after lunch.": "Dù sao thì, mình tiếp tục sau bữa trưa nhé.",
"It's fast even in peak hours.": "Nó nhanh ngay cả trong giờ cao điểm.",
"We work with almost every big chain.": "Chúng tôi hợp tác với gần như mọi chuỗi lớn.",
"My English is good enough to sell.": "Tiếng Anh của tôi đủ tốt để bán hàng.",
"The setup is quite simple.": "Việc lắp đặt khá đơn giản.",
"We're nearly ready to go live.": "Chúng tôi gần như đã sẵn sàng chạy chính thức.",
"We recently launched a new feature.": "Gần đây chúng tôi ra mắt một tính năng mới.",
"What system are you currently using?": "Hiện tại bạn đang dùng hệ thống nào?",
"For example, last month I closed a chain.": "Ví dụ, tháng trước tôi chốt được một chuỗi.",
"In fact, it pays for itself.": "Thực tế, nó tự bù lại chi phí.",
"Of course, training is included.": "Tất nhiên, đã bao gồm đào tạo.",
"Speak English at least five minutes a day.": "Nói tiếng Anh ít nhất năm phút mỗi ngày.",
"By the way, do you need the KDS?": "Nhân tiện, bạn có cần màn hình bếp không?",
"We support e-wallets as well.": "Chúng tôi cũng hỗ trợ ví điện tử.",
"It's more or less the same price.": "Giá gần như nhau.",
"In general, restaurants love it.": "Nhìn chung, các nhà hàng rất thích nó.",
"Hello, this is Thuy from the software team.": "Xin chào, tôi là Thúy từ nhóm phần mềm.",
"Goodbye, and thanks for your time.": "Tạm biệt, và cảm ơn bạn đã dành thời gian.",
"Thanks for coming today.": "Cảm ơn bạn đã đến hôm nay.",
"Sorry, I didn't catch that.": "Xin lỗi, tôi nghe không kịp.",
"Welcome, please have a seat.": "Chào mừng, mời bạn ngồi.",
"Let me introduce our product.": "Để tôi giới thiệu sản phẩm của chúng tôi.",
"I'd like to make an appointment.": "Tôi muốn đặt một cuộc hẹn.",
"There are three points on the agenda.": "Có ba mục trong chương trình họp.",
"I'll invite you to the online demo.": "Tôi sẽ mời bạn vào buổi demo trực tuyến.",
"Who will attend the meeting?": "Ai sẽ tham dự cuộc họp?",
"Everyone on the team is present.": "Cả nhóm đều có mặt.",
"Two staff are absent today.": "Hôm nay có hai nhân viên vắng mặt.",
"Please reply before Friday.": "Vui lòng phản hồi trước thứ Sáu.",
"I'll forward you the quote.": "Tôi sẽ chuyển tiếp bảng báo giá cho bạn.",
"I've attached the contract.": "Tôi đã đính kèm hợp đồng.",
"Put 'Quote' in the subject line.": "Ghi 'Báo giá' ở dòng tiêu đề.",
"Best regards, Thuy.": "Trân trọng, Thúy.",
"Yours sincerely, Thuy.": "Kính thư, Thúy.",
"Dear Mr. Nam, thank you for your email.": "Kính gửi anh Nam, cảm ơn email của anh.",
"Please hold, I'll check for you.": "Vui lòng giữ máy, tôi kiểm tra giúp bạn.",
"Let me connect you to support.": "Để tôi nối máy bạn với bộ phận hỗ trợ.",
"Leave a voicemail and I'll call back.": "Để lại lời nhắn thoại, tôi sẽ gọi lại.",
"My extension is 105.": "Số máy nhánh của tôi là 105.",
"Are you available on Monday?": "Thứ Hai bạn có rảnh không?",
"What time is convenient for you?": "Mấy giờ thì tiện cho bạn?",
"Can we postpone to next week?": "Mình dời sang tuần sau được không?",
"Let's reschedule the demo.": "Mình đổi lịch buổi demo nhé.",
"I'll send a short summary after the call.": "Tôi sẽ gửi một bản tóm tắt ngắn sau cuộc gọi.",
"Let me make a note of that.": "Để tôi ghi chú lại điều đó.",
"I don't have the answer right now.": "Ngay lúc này tôi chưa có câu trả lời.",
"Is that clear, or should I repeat?": "Vậy đã rõ chưa, hay tôi nhắc lại?",
"I understand your budget.": "Tôi hiểu ngân sách của bạn.",
"Could you repeat that, please?": "Bạn nhắc lại giúp tôi được không?",
"Can I speak to the owner?": "Tôi nói chuyện với chủ quán được không?",
"Good sellers listen more than they talk.": "Người bán giỏi lắng nghe nhiều hơn nói.",
"It was a good conversation, thank you.": "Cuộc trò chuyện rất tốt, cảm ơn bạn.",
"I'll book a follow-up for next week.": "Tôi sẽ đặt lịch gặp tiếp cho tuần sau.",
"Let's wrap up the meeting.": "Mình kết thúc cuộc họp nhé.",
"Could you speak up, please?": "Bạn nói to hơn một chút được không?",
"Hold on, I'll check the price.": "Chờ chút, để tôi kiểm tra giá.",
"Go ahead, I'm listening.": "Bạn cứ nói, tôi đang nghe.",
"She's on the phone with a client.": "Cô ấy đang nói chuyện điện thoại với khách.",
"Let's keep in touch after the trial.": "Mình giữ liên lạc sau đợt dùng thử nhé.",
"I look forward to your reply.": "Tôi mong nhận được phản hồi của bạn.",
"This is urgent — can we talk today?": "Việc này gấp — hôm nay mình nói chuyện được không?",
"Don't hang up, I have one more thing.": "Đừng cúp máy, tôi còn một điều nữa.",
"I travel to clients across the city.": "Tôi đi gặp khách khắp thành phố.",
"It was a short business trip.": "Đó là một chuyến công tác ngắn.",
"I'll meet the partner at the airport.": "Tôi sẽ gặp đối tác ở sân bay.",
"My flight is at seven tomorrow.": "Chuyến bay của tôi là bảy giờ ngày mai.",
"I booked the ticket online.": "Tôi đã đặt vé trực tuyến.",
"We also sell to hotel restaurants.": "Chúng tôi cũng bán cho nhà hàng khách sạn.",
"Let's take a taxi to the demo.": "Mình bắt taxi đến buổi demo nhé.",
"Some staff come by bus.": "Một số nhân viên đi bằng xe buýt.",
"The café is near the bus station.": "Quán ở gần bến xe buýt.",
"I'll send you the location on a map.": "Tôi sẽ gửi bạn vị trí trên bản đồ.",
"Can you give me directions to your shop?": "Bạn chỉ đường tới quán của bạn giúp tôi được không?",
"The kitchen is on the left.": "Bếp ở bên trái.",
"The counter is on your right.": "Quầy ở bên phải bạn.",
"Go straight and you'll see the café.": "Đi thẳng là bạn sẽ thấy quán.",
"Is there a restaurant near here?": "Gần đây có nhà hàng nào không?",
"The outlet isn't far from my office.": "Chi nhánh đó không xa văn phòng tôi.",
"The shop is on the corner.": "Cửa hàng nằm ở góc đường.",
"Sorry, the traffic was heavy.": "Xin lỗi, đường kẹt xe quá.",
"The restaurant has easy parking.": "Nhà hàng có chỗ đậu xe thuận tiện.",
"She runs a small coffee shop.": "Cô ấy mở một quán cà phê nhỏ.",
"The chain has stores in three cities.": "Chuỗi có cửa hàng ở ba thành phố.",
"Their new outlet is in the mall.": "Chi nhánh mới của họ nằm trong trung tâm thương mại.",
"Even the supermarket café uses our POS.": "Ngay cả quán cà phê trong siêu thị cũng dùng máy tính tiền của chúng tôi.",
"We fit shops of every size.": "Chúng tôi phù hợp với cửa hàng đủ mọi quy mô.",
"You can change the color of the menu.": "Bạn có thể đổi màu của thực đơn.",
"The online cart connects to the POS.": "Giỏ hàng trực tuyến kết nối với máy tính tiền.",
"A fast POS shortens the queue.": "Máy tính tiền nhanh giúp rút ngắn hàng chờ.",
"I keep a demo tablet in my luggage.": "Tôi để một máy tính bảng demo trong hành lý.",
"Bring your passport for the trip.": "Mang hộ chiếu cho chuyến đi.",
"He's applying for a business visa.": "Anh ấy đang xin visa công tác.",
"Some owners studied abroad.": "Một số chủ quán từng du học.",
"Sales drop when owners are on vacation.": "Doanh số giảm khi chủ quán đi nghỉ.",
"Restaurants are busy on holidays.": "Nhà hàng đông khách vào ngày lễ.",
"Bad weather brings more delivery orders.": "Thời tiết xấu mang lại nhiều đơn giao hàng hơn.",
"When it rains, delivery goes up.": "Khi trời mưa, đơn giao hàng tăng lên.",
"On sunny days the terrace is full.": "Những ngày nắng, khu sân thượng chật kín.",
"Cold drinks sell well when it's hot.": "Đồ uống lạnh bán chạy khi trời nóng.",
"Hot coffee sells more when it's cold.": "Cà phê nóng bán nhiều hơn khi trời lạnh.",
"Guests are hungry and want fast service.": "Khách đói bụng và muốn được phục vụ nhanh.",
"After a walk I'm always thirsty.": "Sau khi đi bộ tôi luôn thấy khát.",
"We support outlets at any distance.": "Chúng tôi hỗ trợ chi nhánh ở bất kỳ khoảng cách nào.",
"There's a new café down the road.": "Có một quán cà phê mới ở cuối đường.",
"I walk to the café near my office.": "Tôi đi bộ tới quán gần văn phòng.",
"I drive to far clients.": "Tôi lái xe tới những khách ở xa.",
"I ride my motorbike to work.": "Tôi đi xe máy đi làm.",
"I'll arrive ten minutes early.": "Tôi sẽ đến sớm mười phút.",
"We depart right after the demo.": "Chúng tôi khởi hành ngay sau buổi demo.",
"I'd like to reserve a table for four.": "Tôi muốn đặt một bàn cho bốn người.",
"You can try the demo on your own tablet.": "Bạn có thể dùng thử bản demo trên máy tính bảng của mình.",
}
