# -*- coding: utf-8 -*-
"""Ban dich cau vi du bo mo rong — phan 1 (co the, suc khoe; tinh tu)."""
VN = {
"Sitting all day is bad for your body.": "Ngồi cả ngày có hại cho cơ thể bạn.",
"Cold water is a shock to the body.": "Nước lạnh gây sốc cho cơ thể.",
"I have a headache after the long meeting.": "Tôi bị đau đầu sau cuộc họp dài.",
"He hit his head on the door.": "Anh ấy đập đầu vào cửa.",
"Her face looked tired this morning.": "Sáng nay mặt cô ấy trông mệt mỏi.",
"Wash your face with cold water.": "Rửa mặt bằng nước lạnh.",
"Keep an eye on the kitchen screen.": "Để mắt tới màn hình bếp.",
"She has beautiful brown eyes.": "Cô ấy có đôi mắt nâu đẹp.",
"The music is too loud for my ears.": "Nhạc to quá đối với tai tôi.",
"The baby has very small ears.": "Em bé có đôi tai rất nhỏ.",
"I can smell the coffee with my nose.": "Tôi ngửi được mùi cà phê bằng mũi.",
"My nose is blocked because of the cold.": "Mũi tôi bị nghẹt vì cảm lạnh.",
"Open your mouth wider when you speak English.": "Mở miệng rộng hơn khi nói tiếng Anh.",
"Don't talk with your mouth full.": "Đừng vừa ăn vừa nói.",
"I brush my teeth twice a day.": "Tôi đánh răng hai lần mỗi ngày.",
"My little boy lost his first tooth.": "Con trai nhỏ của tôi rụng chiếc răng đầu tiên.",
"Staff must tie their hair back in the kitchen.": "Nhân viên phải buộc tóc gọn khi ở trong bếp.",
"I want to cut my hair short.": "Tôi muốn cắt tóc ngắn.",
"My neck hurts from looking at the laptop.": "Cổ tôi đau vì nhìn laptop.",
"I wear a scarf around my neck in winter.": "Mùa đông tôi quàng khăn quanh cổ.",
"He carried the box on his shoulder.": "Anh ấy vác cái thùng trên vai.",
"My son sat on my shoulders at the park.": "Con trai tôi ngồi trên vai tôi ở công viên.",
"She broke her arm last month.": "Tháng trước cô ấy bị gãy tay.",
"She held the baby in her arms.": "Cô ấy bế em bé trong vòng tay.",
"Wash your hands before you start the shift.": "Rửa tay trước khi bắt đầu ca làm.",
"Give me your hand, the road is busy.": "Đưa tay đây, đường đông xe lắm.",
"He pointed at the screen with his finger.": "Anh ấy dùng ngón tay chỉ vào màn hình.",
"I cut my finger while cooking.": "Tôi bị đứt tay khi nấu ăn.",
"My legs hurt after standing all day.": "Chân tôi đau sau khi đứng cả ngày.",
"The dog has short legs.": "Con chó có đôi chân ngắn.",
"Waiters are on their feet for eight hours.": "Nhân viên phục vụ đứng suốt tám tiếng.",
"My left foot is bigger than my right one.": "Bàn chân trái của tôi to hơn chân phải.",
"He hurt his knee playing football.": "Anh ấy bị đau đầu gối khi chơi bóng đá.",
"He sat down and put the child on his knee.": "Anh ấy ngồi xuống và đặt đứa bé lên đầu gối.",
"My back hurts after a long flight.": "Lưng tôi đau sau chuyến bay dài.",
"I sleep on my back.": "Tôi ngủ nằm ngửa.",
"My stomach hurts after that spicy food.": "Bụng tôi đau sau khi ăn món cay đó.",
"I can't swim right after eating, my stomach hurts.": "Tôi không bơi ngay sau khi ăn được, đau bụng lắm.",
"Coffee makes my heart beat faster.": "Cà phê làm tim tôi đập nhanh hơn.",
"My heart was beating fast after the run.": "Tim tôi đập nhanh sau khi chạy.",
"The doctor took a blood test.": "Bác sĩ lấy máu xét nghiệm.",
"I don't like the sight of blood.": "Tôi không thích nhìn thấy máu.",
"The sun is bad for your skin.": "Nắng có hại cho da bạn.",
"Her skin is very dry in winter.": "Da cô ấy rất khô vào mùa đông.",
"He broke a bone in his hand.": "Anh ấy bị gãy một cái xương ở bàn tay.",
"The dog buried a bone in the garden.": "Con chó chôn một khúc xương trong vườn.",
"Sleep helps your brain remember new words.": "Ngủ giúp não bạn nhớ từ mới.",
"Reading is good exercise for the brain.": "Đọc sách là bài tập tốt cho não.",
"We added healthy options to the menu.": "Chúng tôi thêm các món lành mạnh vào thực đơn.",
"My grandmother is eighty and still healthy.": "Bà tôi tám mươi tuổi mà vẫn khỏe mạnh.",
"Two staff are ill today.": "Hôm nay có hai nhân viên bị ốm.",
"My daughter was ill all weekend.": "Con gái tôi ốm suốt cuối tuần.",
"He missed a week because of illness.": "Anh ấy nghỉ một tuần vì bệnh.",
"He recovered from a long illness.": "Anh ấy đã bình phục sau một trận ốm dài.",
"I feel sick, I need to go home.": "Tôi thấy khó chịu, tôi cần về nhà.",
"The cat was sick on the carpet.": "Con mèo nôn ra thảm.",
"Heart disease is common in older people.": "Bệnh tim thường gặp ở người lớn tuổi.",
"The doctors are studying this rare disease.": "Các bác sĩ đang nghiên cứu căn bệnh hiếm này.",
"I have a pain in my back.": "Tôi bị đau ở lưng.",
"I felt a sharp pain in my leg.": "Tôi thấy một cơn đau nhói ở chân.",
"The injection was a bit painful.": "Mũi tiêm hơi đau một chút.",
"The first day at the gym was painful.": "Ngày đầu tập gym thật đau nhức.",
"My eyes hurt after eight hours on the screen.": "Mắt tôi đau sau tám tiếng nhìn màn hình.",
"My feet hurt after the long walk.": "Chân tôi đau sau chặng đi bộ dài.",
"He had a knee injury last season.": "Mùa trước anh ấy bị chấn thương đầu gối.",
"He got an injury while playing football.": "Anh ấy bị chấn thương khi chơi bóng đá.",
"Two people were injured in the accident.": "Hai người bị thương trong vụ tai nạn.",
"The injured bird could not fly.": "Con chim bị thương không bay được.",
"Clean the wound before you cover it.": "Rửa sạch vết thương trước khi băng lại.",
"The wound on his hand healed slowly.": "Vết thương trên tay anh ấy lành chậm.",
"This medicine will cure the infection.": "Loại thuốc này sẽ chữa khỏi nhiễm trùng.",
"There is still no cure for the common cold.": "Vẫn chưa có thuốc chữa khỏi cảm cúm thông thường.",
"The treatment takes about two weeks.": "Quá trình điều trị mất khoảng hai tuần.",
"She is having treatment at the local clinic.": "Cô ấy đang điều trị tại phòng khám địa phương.",
"Take this medicine after meals.": "Uống thuốc này sau bữa ăn.",
"This medicine tastes terrible.": "Thuốc này có vị rất khó uống.",
"The doctor gave me a new drug.": "Bác sĩ cho tôi một loại thuốc mới.",
"The doctor gave her a strong drug for the pain.": "Bác sĩ cho cô ấy một loại thuốc mạnh để giảm đau.",
"You should see a doctor about that cough.": "Bạn nên đi khám bác sĩ về cơn ho đó.",
"My sister wants to be a doctor.": "Em gái tôi muốn làm bác sĩ.",
"The nurse checked my blood pressure.": "Y tá đo huyết áp cho tôi.",
"The nurse was very kind to my mother.": "Y tá rất tử tế với mẹ tôi.",
"She works in a hospital near my house.": "Cô ấy làm việc ở một bệnh viện gần nhà tôi.",
"My son was born in this hospital.": "Con trai tôi sinh ra ở bệnh viện này.",
"He needs an operation on his knee.": "Anh ấy cần phẫu thuật đầu gối.",
"She had an operation on her eyes last year.": "Năm ngoái cô ấy đã phẫu thuật mắt.",
"I do exercise three times a week.": "Tôi tập thể dục ba lần một tuần.",
"Walking is the easiest exercise.": "Đi bộ là bài tập dễ nhất.",
"You need to be fit for this job.": "Bạn cần có thể lực tốt cho công việc này.",
"He runs every morning to stay fit.": "Anh ấy chạy bộ mỗi sáng để giữ dáng.",
"Take a rest before the evening rush.": "Nghỉ ngơi một chút trước giờ cao điểm buổi tối.",
"You look tired, you need some rest.": "Trông bạn mệt đấy, bạn cần nghỉ ngơi.",
"I only slept five hours last night.": "Đêm qua tôi chỉ ngủ năm tiếng.",
"The baby sleeps for twelve hours.": "Em bé ngủ mười hai tiếng.",
"He fell asleep on the bus.": "Anh ấy ngủ thiếp đi trên xe buýt.",
"The children are already asleep.": "Bọn trẻ đã ngủ rồi.",
"I wake up at six thirty every day.": "Tôi thức dậy lúc sáu giờ rưỡi mỗi ngày.",
"The noise woke me at three in the morning.": "Tiếng ồn làm tôi thức giấc lúc ba giờ sáng.",
"Breathe slowly before you start speaking.": "Hít thở chậm trước khi bắt đầu nói.",
"It is hard to breathe in this hot room.": "Khó thở trong căn phòng nóng này.",
"I lost weight after I stopped drinking soda.": "Tôi giảm cân sau khi bỏ nước ngọt.",
"The doctor asked me about my weight.": "Bác sĩ hỏi tôi về cân nặng.",
"The app also works for blind users.": "Ứng dụng cũng dùng được cho người khiếm thị.",
"Their dog helps a blind man cross the street.": "Con chó của họ giúp một người mù qua đường.",
"He is deaf in one ear.": "Anh ấy điếc một bên tai.",
"My grandfather is going deaf.": "Ông tôi đang bị lãng tai dần.",
"The battery is dead.": "Hết pin rồi.",
"The plant is dead, I forgot to water it.": "Cây chết rồi, tôi quên tưới nước.",
"The company closed after the owner's death.": "Công ty đóng cửa sau khi ông chủ qua đời.",
"The whole village came after his death.": "Cả làng đến sau khi ông ấy qua đời.",
"His grandmother is still alive.": "Bà của anh ấy vẫn còn sống.",
"The fish is still alive in the bucket.": "Con cá vẫn còn sống trong xô.",
"A wet kitchen floor is dangerous.": "Sàn bếp ướt rất nguy hiểm.",
"Swimming in this river is dangerous.": "Bơi ở con sông này rất nguy hiểm.",
"The company pays for medical insurance.": "Công ty chi trả bảo hiểm y tế.",
"He is studying at a medical school.": "Anh ấy đang học ở trường y.",
"He has a fever, so he cannot come in today.": "Anh ấy bị sốt nên hôm nay không đi làm được.",
"The child had a fever all night.": "Đứa bé sốt suốt đêm.",
"Long shifts affect mental health too.": "Ca làm dài cũng ảnh hưởng đến sức khỏe tinh thần.",
"Walking outside is good for mental health.": "Đi bộ ngoài trời tốt cho sức khỏe tinh thần.",
"This is the most important client this month.": "Đây là khách hàng quan trọng nhất trong tháng.",
"Family is the most important thing to me.": "Gia đình là điều quan trọng nhất với tôi.",
"Each outlet has a different menu.": "Mỗi chi nhánh có một thực đơn khác nhau.",
"Life in the countryside is completely different.": "Cuộc sống ở quê hoàn toàn khác.",
"Our system is similar to Toast, but cheaper.": "Hệ thống của chúng tôi giống Toast, nhưng rẻ hơn.",
"My brother and I have similar taste in music.": "Anh trai tôi và tôi có gu âm nhạc giống nhau.",
"We use the same POS in all five outlets.": "Chúng tôi dùng cùng một máy tính tiền ở cả năm chi nhánh.",
"We went to the same school as children.": "Hồi nhỏ chúng tôi học cùng một trường.",
"Is it possible to go live next month?": "Có thể chạy chính thức vào tháng sau không?",
"Is it possible to get there by bus?": "Có thể đến đó bằng xe buýt không?",
"That deadline is impossible for our team.": "Hạn chót đó là bất khả thi với nhóm chúng tôi.",
"It is impossible to park here on Sunday.": "Không thể đậu xe ở đây vào Chủ nhật.",
"Training is necessary before go-live.": "Cần đào tạo trước khi chạy chính thức.",
"Take a jacket, it may be necessary tonight.": "Mang theo áo khoác, tối nay có thể cần đấy.",
"That report is very useful for planning.": "Báo cáo đó rất hữu ích cho việc lập kế hoạch.",
"This little knife is very useful when camping.": "Con dao nhỏ này rất hữu ích khi đi cắm trại.",
"Milk tea is popular with young customers.": "Trà sữa được khách trẻ ưa chuộng.",
"That beach is popular with young families.": "Bãi biển đó được các gia đình trẻ ưa thích.",
"They are a famous chain in Hanoi.": "Họ là một chuỗi nổi tiếng ở Hà Nội.",
"The town is famous for its noodles.": "Thị trấn nổi tiếng với món mì.",
"This is a common problem in busy kitchens.": "Đây là vấn đề thường gặp ở những căn bếp bận rộn.",
"Rain is common in this season.": "Mưa là chuyện thường vào mùa này.",
"It is normal to feel nervous at first.": "Lúc đầu thấy hồi hộp là chuyện bình thường.",
"It is normal for a puppy to sleep a lot.": "Chó con ngủ nhiều là bình thường.",
"We have a special price for three outlets.": "Chúng tôi có giá đặc biệt cho ba chi nhánh.",
"My mother cooks something special on my birthday.": "Mẹ tôi nấu món đặc biệt vào ngày sinh nhật tôi.",
"The main problem is staff training.": "Vấn đề chính là đào tạo nhân viên.",
"The main road is closed today.": "Đường chính hôm nay bị đóng.",
"The basic package covers one outlet.": "Gói cơ bản áp dụng cho một chi nhánh.",
"He only knows basic Japanese.": "Anh ấy chỉ biết tiếng Nhật cơ bản.",
"The setup is simple — about two hours.": "Việc lắp đặt đơn giản — khoảng hai tiếng.",
"I like simple food, nothing fancy.": "Tôi thích đồ ăn đơn giản, không cầu kỳ.",
"The app is easy to use for new staff.": "Ứng dụng dễ dùng cho nhân viên mới.",
"This game is easy enough for a child.": "Trò chơi này đủ dễ cho một đứa trẻ.",
"It is difficult to hire good cashiers.": "Khó tuyển được thu ngân giỏi.",
"The exam was more difficult than I expected.": "Bài thi khó hơn tôi tưởng.",
"Speaking English on the phone is hard for me.": "Nói tiếng Anh qua điện thoại khó đối với tôi.",
"The bed in the hotel was very hard.": "Giường ở khách sạn rất cứng.",
"Is this the correct invoice number?": "Đây có phải số hóa đơn đúng không?",
"Only one answer is correct.": "Chỉ có một đáp án đúng.",
"The system sent the wrong order to the kitchen.": "Hệ thống gửi nhầm đơn xuống bếp.",
"I took the wrong bus and got lost.": "Tôi đi nhầm xe buýt và bị lạc.",
"That is true, but there is another side.": "Đúng vậy, nhưng còn một mặt khác.",
"Is it true that you are moving to Hanoi?": "Có đúng là bạn sắp chuyển ra Hà Nội không?",
"Let me show you a real example.": "Để tôi cho bạn xem một ví dụ thực tế.",
"Those flowers are not real.": "Những bông hoa đó không phải hoa thật.",
"His family owns a rich chain of restaurants.": "Gia đình anh ấy sở hữu một chuỗi nhà hàng giàu có.",
"They are not rich, but they are happy.": "Họ không giàu, nhưng họ hạnh phúc.",
"The internet here is poor at peak hours.": "Mạng ở đây kém vào giờ cao điểm.",
"The soil here is too poor for rice.": "Đất ở đây quá cằn để trồng lúa.",
"The box is too heavy for one person.": "Cái thùng quá nặng đối với một người.",
"This bag is too heavy for me to carry.": "Cái túi này quá nặng để tôi xách.",
"Can I ask a quick question?": "Tôi hỏi nhanh một câu được không?",
"Let me take a quick shower first.": "Để tôi tắm nhanh cái đã.",
"Our support response is very fast.": "Phản hồi hỗ trợ của chúng tôi rất nhanh.",
"He drives too fast on the highway.": "Anh ấy lái xe quá nhanh trên cao tốc.",
"The old system was slow at peak hours.": "Hệ thống cũ chạy chậm vào giờ cao điểm.",
"The traffic is very slow this morning.": "Sáng nay giao thông rất chậm.",
"Keep the counter clean during service.": "Giữ quầy sạch sẽ trong lúc phục vụ.",
"Put on a clean shirt before we go.": "Mặc áo sạch vào trước khi mình đi.",
"The tablet screen gets dirty very fast.": "Màn hình máy tính bảng rất mau bẩn.",
"The children came home with dirty shoes.": "Bọn trẻ về nhà với đôi giày bẩn.",
"Your data is safe on our servers.": "Dữ liệu của bạn an toàn trên máy chủ của chúng tôi.",
"It is not safe to cycle here at night.": "Đạp xe ở đây vào ban đêm không an toàn.",
"The system will be ready by Friday.": "Hệ thống sẽ sẵn sàng vào thứ Sáu.",
"Dinner is ready, come to the table.": "Bữa tối xong rồi, vào bàn ăn thôi.",
"Here is the complete quote.": "Đây là bảng báo giá đầy đủ.",
"I have the complete set of his books.": "Tôi có trọn bộ sách của ông ấy.",
"The restaurant was empty at three o'clock.": "Nhà hàng vắng tanh lúc ba giờ.",
"The bottle is empty already.": "Cái chai đã hết sạch.",
"We are full every Saturday night.": "Tối thứ Bảy nào chúng tôi cũng kín chỗ.",
"The bus was full, so I walked.": "Xe buýt chật kín nên tôi đi bộ.",
"The whole team joined the training.": "Cả nhóm tham gia buổi đào tạo.",
"He ate the whole cake by himself.": "Anh ấy ăn hết cả cái bánh một mình.",
"That timing is perfect for us.": "Thời điểm đó hoàn hảo cho chúng tôi.",
"The weather was perfect for a picnic.": "Thời tiết hoàn hảo để đi dã ngoại.",
"The old reports were terrible.": "Những báo cáo cũ tệ kinh khủng.",
"I had a terrible night, the dog kept barking.": "Tôi có một đêm tệ hại, con chó sủa suốt.",
"We were lucky to sign that deal.": "Chúng tôi may mắn ký được hợp đồng đó.",
"You are lucky it did not rain.": "Bạn may là trời không mưa.",
"They want a modern look for the new store.": "Họ muốn một diện mạo hiện đại cho cửa hàng mới.",
"They live in a modern flat near the river.": "Họ sống trong một căn hộ hiện đại gần sông.",
"They still use a traditional cash box.": "Họ vẫn dùng một két tiền kiểu truyền thống.",
"My mother still cooks the traditional way.": "Mẹ tôi vẫn nấu theo cách truyền thống.",
"We work with local suppliers.": "Chúng tôi hợp tác với các nhà cung cấp địa phương.",
"We buy vegetables at the local market.": "Chúng tôi mua rau ở chợ địa phương.",
"They are planning a national rollout.": "Họ đang lên kế hoạch triển khai toàn quốc.",
"Today is a national holiday.": "Hôm nay là ngày lễ toàn quốc.",
"The prices are not public yet.": "Giá vẫn chưa được công bố.",
"There is a public park behind our house.": "Có một công viên công cộng phía sau nhà tôi.",
"Your sales data stays private.": "Dữ liệu bán hàng của bạn được giữ riêng tư.",
"This is a private garden, not a park.": "Đây là vườn riêng, không phải công viên.",
"I will send the official quote tomorrow.": "Mai tôi sẽ gửi bảng báo giá chính thức.",
"The official language here is Vietnamese.": "Ngôn ngữ chính thức ở đây là tiếng Việt.",
"He is a regular customer here.": "Anh ấy là khách quen ở đây.",
"He is a regular visitor to my parents' house.": "Anh ấy hay lui tới nhà bố mẹ tôi.",
"In a recent update we added offline mode.": "Trong một bản cập nhật gần đây, chúng tôi thêm chế độ ngoại tuyến.",
"In recent years the village has grown a lot.": "Những năm gần đây, ngôi làng phát triển rất nhiều.",
"Please contact me for further details.": "Vui lòng liên hệ tôi để biết thêm chi tiết.",
"The shop is a little further down this street.": "Cửa hàng ở xa hơn một chút trên con phố này.",
}
