# -*- coding: utf-8 -*-
"""Ban dich cau vi du bo mo rong — phan 2 (tinh tu con lai; dong tu chuyen dong, vi tri)."""
VN = {
"We support various payment methods.": "Chúng tôi hỗ trợ nhiều phương thức thanh toán.",
"We saw various birds at the lake.": "Chúng tôi thấy nhiều loài chim ở hồ.",
"I am certain the data is correct.": "Tôi chắc chắn dữ liệu là đúng.",
"I am certain I locked the door.": "Tôi chắc chắn đã khóa cửa.",
"Are you sure about that number?": "Bạn có chắc về con số đó không?",
"Are you sure you don't want coffee?": "Bạn chắc là không muốn cà phê chứ?",
"They are likely to sign this week.": "Có khả năng tuần này họ sẽ ký.",
"It is likely to rain this afternoon.": "Chiều nay có khả năng mưa.",
"It is unlikely we can finish by Friday.": "Khó có khả năng mình xong trước thứ Sáu.",
"He is unlikely to come, he hates parties.": "Anh ấy khó mà đến, anh ấy ghét tiệc tùng.",
"The obvious answer is to add one more till.": "Cách rõ ràng nhất là thêm một quầy tính tiền nữa.",
"It was obvious that the child was tired.": "Rõ ràng là đứa bé đã mệt.",
"Is there a particular feature you need?": "Có tính năng cụ thể nào bạn cần không?",
"Do you have a particular restaurant in mind?": "Bạn có nhà hàng cụ thể nào trong đầu không?",
"In general, setup takes two hours.": "Nhìn chung, việc lắp đặt mất hai tiếng.",
"In general, I sleep badly in hotels.": "Nhìn chung, tôi ngủ không ngon ở khách sạn.",
"Can you give me a specific example?": "Bạn cho tôi một ví dụ cụ thể được không?",
"Be specific about the time you will arrive.": "Hãy nói rõ giờ bạn sẽ đến.",
"This is our standard contract.": "Đây là hợp đồng tiêu chuẩn của chúng tôi.",
"This is the standard size for a single bed.": "Đây là kích thước tiêu chuẩn cho giường đơn.",
"A typical cafe needs two tablets.": "Một quán cà phê điển hình cần hai máy tính bảng.",
"A typical Sunday for me is cooking and reading.": "Một ngày Chủ nhật điển hình của tôi là nấu ăn và đọc sách.",
"The actual cost was lower than the quote.": "Chi phí thực tế thấp hơn báo giá.",
"The actual journey took five hours.": "Chuyến đi thực tế mất năm tiếng.",
"What is your current system?": "Hệ thống hiện tại của bạn là gì?",
"What is your current address?": "Địa chỉ hiện tại của bạn là gì?",
"Their previous provider had no support team.": "Nhà cung cấp trước của họ không có đội hỗ trợ.",
"We met at a previous wedding.": "Chúng tôi gặp nhau ở một đám cưới trước đó.",
"Training is the most effective way to reduce errors.": "Đào tạo là cách hiệu quả nhất để giảm sai sót.",
"Hot tea with honey is effective for a sore throat.": "Trà nóng với mật ong hiệu quả cho cổ họng đau.",
"Your feedback is very valuable to us.": "Phản hồi của bạn rất quý giá với chúng tôi.",
"This old watch is very valuable to me.": "Chiếc đồng hồ cũ này rất quý giá với tôi.",
"This package is suitable for a small cafe.": "Gói này phù hợp với một quán cà phê nhỏ.",
"That film is not suitable for small children.": "Bộ phim đó không phù hợp với trẻ nhỏ.",
"That is a reasonable request.": "Đó là một yêu cầu hợp lý.",
"The hotel was clean and the price was reasonable.": "Khách sạn sạch sẽ và giá cả hợp lý.",
"A two-week delay is not acceptable.": "Trễ hai tuần là không chấp nhận được.",
"Coming ten minutes late is acceptable here.": "Đến trễ mười phút thì ở đây chấp nhận được.",
"The receipts lie on the counter.": "Các hóa đơn nằm trên quầy.",
"The cat likes to lie in the sun.": "Con mèo thích nằm phơi nắng.",
"Sales jumped after the promotion.": "Doanh số tăng vọt sau đợt khuyến mãi.",
"The children jumped into the pool.": "Bọn trẻ nhảy xuống hồ bơi.",
"Revenue climbed twenty percent.": "Doanh thu tăng hai mươi phần trăm.",
"We climbed the hill to watch the sunset.": "Chúng tôi leo đồi để ngắm hoàng hôn.",
"Orders fall after nine at night.": "Đơn hàng giảm sau chín giờ tối.",
"Be careful, you might fall on the wet floor.": "Cẩn thận, bạn có thể ngã trên sàn ướt.",
"Costs rise every year.": "Chi phí tăng mỗi năm.",
"The sun rises at half past five.": "Mặt trời mọc lúc năm giờ rưỡi.",
"Push the button to print the bill.": "Nhấn nút để in hóa đơn.",
"I had to push the door hard to open it.": "Tôi phải đẩy mạnh cửa mới mở được.",
"Pull the report from the dashboard.": "Kéo báo cáo ra từ bảng điều khiển.",
"Pull the rope slowly.": "Kéo sợi dây từ từ.",
"Two people should lift that box.": "Hai người nên khiêng cái thùng đó.",
"Can you lift this suitcase for me?": "Bạn nhấc giúp tôi cái vali này được không?",
"The waiter carries four plates at once.": "Nhân viên phục vụ bưng bốn đĩa một lúc.",
"She carried her shopping bags home.": "Cô ấy xách túi đồ mua sắm về nhà.",
"Sales dropped during the rain.": "Doanh số giảm trong lúc trời mưa.",
"I dropped my phone in the street.": "Tôi làm rơi điện thoại ngoài đường.",
"He ran to catch the last bus.": "Anh ấy chạy để kịp chuyến xe buýt cuối.",
"Don't throw away the old receipts yet.": "Đừng vứt các hóa đơn cũ vội.",
"Don't throw stones at the birds.": "Đừng ném đá vào lũ chim.",
"Enter the discount code here.": "Nhập mã giảm giá vào đây.",
"Please take off your shoes before you enter.": "Vui lòng cởi giày trước khi vào.",
"I will return the tablet on Friday.": "Tôi sẽ trả máy tính bảng vào thứ Sáu.",
"We return from holiday on Sunday.": "Chúng tôi đi nghỉ về vào Chủ nhật.",
"Please follow these three steps.": "Vui lòng làm theo ba bước sau.",
"The dog follows me everywhere.": "Con chó đi theo tôi khắp nơi.",
"Can you pass me the menu?": "Bạn đưa giúp tôi thực đơn được không?",
"We passed a beautiful lake on the way.": "Trên đường đi chúng tôi ngang qua một cái hồ đẹp.",
"Cross the street and it is on the left.": "Băng qua đường là nó ở bên trái.",
"Look both ways before you cross.": "Nhìn cả hai phía trước khi qua đường.",
"You can reach me on Zalo any time.": "Bạn có thể liên hệ tôi qua Zalo bất cứ lúc nào.",
"I can't reach the top shelf.": "Tôi với không tới kệ trên cùng.",
"I will visit your store on Monday.": "Tôi sẽ ghé cửa hàng của bạn vào thứ Hai.",
"We visit my grandparents every Sunday.": "Chủ nhật nào chúng tôi cũng về thăm ông bà.",
"Nobody can escape the peak-hour rush.": "Không ai thoát khỏi cảnh tất bật giờ cao điểm.",
"The bird escaped from its cage.": "Con chim sổng khỏi lồng.",
"There is no hurry, take your time.": "Không vội đâu, bạn cứ từ từ.",
"Hurry up, the film starts in ten minutes.": "Nhanh lên, phim bắt đầu sau mười phút nữa.",
"Customers hate to wait for the bill.": "Khách rất ghét phải chờ tính tiền.",
"I waited an hour for my friend.": "Tôi đợi bạn một tiếng đồng hồ.",
"I will stay until the system is stable.": "Tôi sẽ ở lại đến khi hệ thống ổn định.",
"We stayed at my aunt's house.": "Chúng tôi ở nhà dì tôi.",
"It is very quiet here in the evening.": "Ở đây buổi tối rất yên tĩnh.",
"There is a problem with the printer.": "Máy in đang gặp trục trặc.",
"There are three cats in our street.": "Có ba con mèo trong con phố của chúng tôi.",
"The KDS is above the pass.": "Màn hình bếp ở phía trên khu chuyển món.",
"The birds were flying above the trees.": "Đàn chim bay phía trên những ngọn cây.",
"Sales are below target this month.": "Doanh số tháng này dưới mục tiêu.",
"The temperature fell below zero last night.": "Đêm qua nhiệt độ xuống dưới không độ.",
"We can do it under budget.": "Chúng tôi có thể làm trong phạm vi ngân sách.",
"The cat is sleeping under the bed.": "Con mèo đang ngủ dưới gầm giường.",
"We have over fifty outlets now.": "Bây giờ chúng tôi có hơn năm mươi chi nhánh.",
"The bridge goes over the river.": "Cây cầu bắc qua sông.",
"The price is between ten and twelve million.": "Giá nằm trong khoảng mười đến mười hai triệu.",
"The shop is between the bank and the post office.": "Cửa hàng nằm giữa ngân hàng và bưu điện.",
"We are among the top three providers.": "Chúng tôi nằm trong ba nhà cung cấp hàng đầu.",
"I found my old photos among some books.": "Tôi tìm thấy mấy tấm ảnh cũ giữa đống sách.",
"Put the printer beside the register.": "Đặt máy in cạnh máy tính tiền.",
"Come and sit beside me.": "Lại đây ngồi cạnh tôi.",
"We are behind schedule by one week.": "Chúng tôi chậm tiến độ một tuần.",
"The garden behind the house is small.": "Khu vườn phía sau nhà thì nhỏ.",
"The queue is in front of the counter.": "Hàng người chờ ở phía trước quầy.",
"A tall man sat in front of me at the cinema.": "Một người đàn ông cao ngồi phía trước tôi ở rạp phim.",
"The router is inside the cabinet.": "Bộ phát wifi nằm bên trong tủ.",
"Let's eat inside, it is too cold outside.": "Mình ăn ở trong nhà đi, ngoài trời lạnh quá.",
"There are ten tables outside.": "Có mười cái bàn ở bên ngoài.",
"The children are playing outside.": "Bọn trẻ đang chơi ở ngoài.",
"It costs around five million a month.": "Nó tốn khoảng năm triệu một tháng.",
"We walked around the lake.": "Chúng tôi đi bộ quanh hồ.",
"Orders come through the app.": "Đơn hàng đến qua ứng dụng.",
"The train goes through a long tunnel.": "Tàu chạy xuyên qua một đường hầm dài.",
"The same price applies across all outlets.": "Cùng một mức giá áp dụng cho mọi chi nhánh.",
"She swam across the river.": "Cô ấy bơi qua sông.",
"There are five cafes along this street.": "Có năm quán cà phê dọc con phố này.",
"We walked along the beach at sunset.": "Chúng tôi đi dọc bãi biển lúc hoàng hôn.",
"We are moving toward a full rollout.": "Chúng tôi đang tiến tới triển khai toàn diện.",
"The dog ran toward its owner.": "Con chó chạy về phía chủ.",
"Don't step backward in the kitchen.": "Đừng bước lùi trong bếp.",
"He took one step backward in surprise.": "Anh ấy lùi một bước vì bất ngờ.",
"Sales are up fifteen percent.": "Doanh số tăng mười lăm phần trăm.",
"The cat ran up the tree.": "Con mèo chạy tót lên cây.",
"The system is down for maintenance.": "Hệ thống đang tạm ngưng để bảo trì.",
"Sit down and rest for a minute.": "Ngồi xuống nghỉ một phút đi.",
"The total is at the top of the receipt.": "Tổng tiền nằm ở đầu hóa đơn.",
"There is snow on the top of the mountain.": "Có tuyết trên đỉnh núi.",
"Sign at the bottom of the contract.": "Ký ở cuối hợp đồng.",
"My keys were at the bottom of my bag.": "Chìa khóa của tôi ở dưới đáy túi.",
"We are in the middle of the rollout.": "Chúng tôi đang ở giữa quá trình triển khai.",
"The dog slept in the middle of the room.": "Con chó ngủ ở giữa phòng.",
"Please remove that item from the bill.": "Vui lòng bỏ món đó khỏi hóa đơn.",
"Please remove your shoes at the door.": "Vui lòng cởi giày ở cửa.",
"We will replace the broken printer today.": "Hôm nay chúng tôi sẽ thay chiếc máy in hỏng.",
"I need to replace the light bulb.": "Tôi cần thay bóng đèn.",
"Transport costs went up this year.": "Chi phí vận chuyển năm nay tăng lên.",
"Public transport here is cheap.": "Giao thông công cộng ở đây rẻ.",
"The journey to Da Nang takes two hours.": "Chuyến đi tới Đà Nẵng mất hai tiếng.",
"It was a long journey by train.": "Đó là một chặng đường dài bằng tàu.",
"The delivery route covers five districts.": "Tuyến giao hàng bao phủ năm quận.",
"This is the fastest route to the beach.": "Đây là tuyến nhanh nhất ra biển.",
"He applied for the manager position.": "Anh ấy ứng tuyển vị trí quản lý.",
"He changed position because his leg hurt.": "Anh ấy đổi tư thế vì chân bị đau.",
"This location gets the most walk-in customers.": "Địa điểm này có nhiều khách vãng lai nhất.",
"The house has a quiet location near the park.": "Ngôi nhà ở một vị trí yên tĩnh gần công viên.",
"The news spread quickly among the staff.": "Tin tức lan nhanh trong nhân viên.",
"The children spread a blanket on the grass.": "Bọn trẻ trải một tấm chăn trên cỏ.",
"We shake hands after we agree.": "Chúng tôi bắt tay sau khi đồng ý.",
"Shake the bottle before you open it.": "Lắc chai trước khi mở.",
"We will roll out the update next week.": "Chúng tôi sẽ triển khai bản cập nhật vào tuần sau.",
"The ball rolled under the car.": "Quả bóng lăn xuống gầm xe.",
"Slide the drawer closed after each payment.": "Đẩy ngăn kéo đóng lại sau mỗi lần thanh toán.",
"The children love to slide on the ice.": "Bọn trẻ thích trượt trên băng.",
"Hang the menu board near the door.": "Treo bảng thực đơn gần cửa.",
"Hang your coat behind the door.": "Treo áo khoác của bạn sau cánh cửa.",
"Can we separate the bill for this table?": "Mình tách hóa đơn cho bàn này được không?",
"We separate paper and plastic for recycling.": "Chúng tôi tách giấy và nhựa để tái chế.",
"Let's divide the cost into three payments.": "Mình chia chi phí thành ba lần trả nhé.",
"Let's divide the cake into six pieces.": "Mình chia cái bánh thành sáu miếng nhé.",
"I need to gather more data before I answer.": "Tôi cần thu thập thêm dữ liệu trước khi trả lời.",
"The family gathers here every New Year.": "Cả nhà tụ họp ở đây mỗi dịp Tết.",
"We collect feedback from customers every month.": "Chúng tôi thu thập phản hồi từ khách hàng mỗi tháng.",
"My son collects football cards.": "Con trai tôi sưu tầm thẻ bóng đá.",
"The first step is a short demo.": "Bước đầu tiên là một buổi demo ngắn.",
"Watch that first step, it is high.": "Coi chừng bậc thang đầu tiên, nó cao đấy.",
"The printer is on the left side of the counter.": "Máy in ở phía bên trái của quầy.",
"There is a small garden on the side of the house.": "Có một khu vườn nhỏ ở bên hông nhà.",
}
