# -*- coding: utf-8 -*-
"""Ban dich 72 dong kich ban F&B."""
VN = {
"Good morning, everyone. Let's start.": "Chào buổi sáng cả nhà. Mình bắt đầu nhé.",
"This week our target is fifteen new leads.": "Mục tiêu tuần này của chúng ta là mười lăm khách tiềm năng mới.",
"Minh, how many demos do you have this week?": "Minh, tuần này em có bao nhiêu buổi demo?",
"Okay, that's good. Please follow up with the coffee chain in District 3.": "Được, tốt đấy. Nhớ theo sát chuỗi cà phê ở Quận 3 nhé.",
"Lan, the restaurant in Thao Dien — do they need the KDS or only the POS?": "Lan, nhà hàng ở Thảo Điền — họ cần màn hình bếp hay chỉ cần máy tính tiền?",
"If you have any problem, tell me. Don't wait.": "Có vấn đề gì cứ nói anh. Đừng chờ đợi.",
"One more thing: please update the pipeline before Friday. That's all. Thank you.": "Một điều nữa: nhớ cập nhật danh sách khách tiềm năng trước thứ Sáu. Vậy thôi. Cảm ơn cả nhà.",
"Hi Nam, thanks for coming. I want to talk about this month.": "Chào Nam, cảm ơn em đã đến. Anh muốn nói về tháng này.",
"You closed two deals. Your target was five. What happened?": "Em chốt được hai hợp đồng. Mục tiêu là năm. Chuyện gì đã xảy ra?",
"I see. So the problem is the price, not the product?": "Anh hiểu rồi. Vậy vấn đề là giá, chứ không phải sản phẩm à?",
"Okay, I understand. Let me help you.": "Được, anh hiểu. Để anh giúp em.",
"Next week, I will join your demo with the client. We do it together.": "Tuần sau anh sẽ đi demo với khách cùng em. Mình làm cùng nhau.",
"I know you work hard. I'm not angry. I want you to succeed.": "Anh biết em làm việc chăm chỉ. Anh không giận. Anh muốn em thành công.",
"Let's check again in two weeks. Okay?": "Hai tuần nữa mình xem lại nhé. Được chứ?",
"We provide software for restaurants and cafés in Vietnam.": "Chúng tôi cung cấp phần mềm cho nhà hàng và quán cà phê tại Việt Nam.",
"Our system has three main parts: the POS, the kitchen display, and the inventory.": "Hệ thống của chúng tôi có ba phần chính: máy tính tiền, màn hình bếp, và quản lý kho.",
"We work with about [X] restaurants now, from small cafés to chains with twenty outlets.": "Hiện chúng tôi làm việc với khoảng [X] nhà hàng, từ quán nhỏ đến chuỗi hai mươi chi nhánh.",
"It also works offline — so if the internet is down, you can still sell.": "Nó còn chạy được khi không có mạng — nên mất internet bạn vẫn bán hàng được.",
"Would you like to see a demo?": "Bạn có muốn xem demo không?",
"Before I give you a price, can I ask a few questions?": "Trước khi báo giá, tôi hỏi bạn vài câu được không?",
"What system are you using at the moment?": "Hiện giờ bạn đang dùng hệ thống nào?",
"Based on your needs, I will recommend the most suitable package to optimize your costs.": "Dựa trên nhu cầu của bạn, tôi sẽ đề xuất gói phù hợp nhất để tối ưu chi phí.",
"Let me summarize your exact requirements and send you a detailed, itemized quote.": "Để tôi tóm tắt đúng yêu cầu của bạn và gửi bạn một bảng báo giá chi tiết theo từng mục.",
"How many branches or stores do you currently have?": "Hiện bạn có bao nhiêu chi nhánh hay cửa hàng?",
"What is your average daily order volume?": "Lượng đơn trung bình mỗi ngày của bạn là bao nhiêu?",
"What software or hardware are you currently using?": "Bạn đang dùng phần mềm hay phần cứng nào?",
"What are you most dissatisfied with regarding your current system?": "Điều bạn không hài lòng nhất ở hệ thống hiện tại là gì?",
"Do you require offline and online capabilities, or multi-device synchronization?": "Bạn có cần chạy cả ngoại tuyến lẫn trực tuyến, hay đồng bộ nhiều thiết bị không?",
"How many POS terminals or users are you planning to deploy?": "Bạn định triển khai bao nhiêu máy tính tiền hay người dùng?",
"What is your estimated budget for this investment?": "Ngân sách dự kiến của bạn cho khoản đầu tư này là bao nhiêu?",
"Are you looking for a basic setup first, or a comprehensive solution right from the start?": "Bạn muốn lắp cơ bản trước, hay một giải pháp toàn diện ngay từ đầu?",
"Yes, that sounds exactly like what we need.": "Vâng, nghe đúng thứ chúng tôi cần luôn.",
"We have three bubble tea shops. We process about five hundred orders a day per store.": "Chúng tôi có ba quán trà sữa. Mỗi quán xử lý khoảng năm trăm đơn một ngày.",
"That's a great volume. Are you facing any issues with inventory loss or multi-store reporting?": "Lượng đơn tốt đấy. Bạn có gặp vấn đề gì về thất thoát kho hay báo cáo nhiều cửa hàng không?",
"Yes, I need a complete package.": "Vâng, tôi cần một gói trọn vẹn.",
"Our price has two parts.": "Giá của chúng tôi có hai phần.",
"First, a one-time setup fee. This includes installation and training for your staff.": "Thứ nhất, phí lắp đặt một lần. Phí này gồm cài đặt và đào tạo nhân viên.",
"Second, a monthly fee per outlet. It's [X] per month for each restaurant.": "Thứ hai, phí hằng tháng theo chi nhánh. Là [X] mỗi tháng cho mỗi nhà hàng.",
"The monthly fee includes support, updates, and the cloud dashboard.": "Phí hằng tháng gồm hỗ trợ, cập nhật, và bảng điều khiển trên đám mây.",
"If you sign for one year, the monthly fee is lower.": "Nếu bạn ký một năm, phí hằng tháng sẽ thấp hơn.",
"Would you like me to send you a full quote by email?": "Bạn có muốn tôi gửi bảng báo giá đầy đủ qua email không?",
"Let me give you a quote for what your store really needs.": "Để tôi báo giá đúng những gì cửa hàng bạn thật sự cần.",
"Our price has three parts: software, hardware, and deployment.": "Giá của chúng tôi có ba phần: phần mềm, phần cứng, và triển khai.",
"The software fee is for using the system.": "Phí phần mềm là để sử dụng hệ thống.",
"Hardware is only if you need it: the POS machine, the tablet, or the printer.": "Phần cứng chỉ khi bạn cần: máy tính tiền, máy tính bảng, hoặc máy in.",
"The deployment fee is for installation and training your staff.": "Phí triển khai là để cài đặt và đào tạo nhân viên.",
"You don't have to buy all three parts. We choose only what your store needs now.": "Bạn không phải mua cả ba phần. Mình chỉ chọn những gì cửa hàng cần lúc này.",
"The setup fee is paid one time, at the beginning.": "Phí lắp đặt trả một lần, ngay từ đầu.",
"The subscription fee is paid every month or every year, to keep using the software.": "Phí thuê bao trả hằng tháng hoặc hằng năm, để tiếp tục dùng phần mềm.",
"They are two different things, so I separate them in the quote.": "Đó là hai khoản khác nhau, nên tôi tách riêng trong báo giá.",
"The total cost is almost the same. We only changed how the fees are split.": "Tổng chi phí gần như nhau. Mình chỉ thay đổi cách chia các khoản phí.",
"I understand. Let's look at each part and see what you really need.": "Tôi hiểu. Mình cùng xem từng phần và xem bạn thật sự cần gì.",
"If you only need the basic features now, I will quote the smaller package first.": "Nếu giờ bạn chỉ cần tính năng cơ bản, tôi sẽ báo giá gói nhỏ trước.",
"I quote for what you need now. We can add more later if the store grows.": "Tôi báo giá theo nhu cầu hiện tại của bạn. Cửa hàng lớn lên thì mình bổ sung sau.",
"I suggest this option because it balances the first cost and long-term use.": "Tôi đề xuất phương án này vì nó cân bằng giữa chi phí ban đầu và việc dùng lâu dài.",
"I understand. Can I ask — expensive compared to what?": "Tôi hiểu. Cho tôi hỏi — đắt so với cái gì?",
"I understand that price is very important for you.": "Tôi hiểu rằng giá rất quan trọng với bạn.",
"I understand you are thinking about the price.": "Tôi hiểu bạn đang cân nhắc về giá.",
"Instead of looking at the total number first, let me break down each part.": "Thay vì nhìn vào con số tổng trước, để tôi tách nhỏ từng phần.",
"Then we can see which items your store really needs now, and which can wait.": "Rồi mình sẽ thấy khoản nào cửa hàng thật sự cần ngay, khoản nào có thể để sau.",
"This way you choose the right package and don't pay for things you don't need.": "Như vậy bạn chọn đúng gói và không phải trả cho những thứ không cần.",
"So, let me confirm what we agreed.": "Vậy, để tôi xác nhận lại những gì mình đã thống nhất.",
"Five outlets. The POS and the inventory module. No KDS for now.": "Năm chi nhánh. Máy tính tiền và tính năng quản lý kho. Chưa cần màn hình bếp.",
"Setup fee: [X], paid after installation.": "Phí lắp đặt: [X], trả sau khi cài đặt.",
"Monthly fee: [Y] per outlet, for twenty-four months.": "Phí hằng tháng: [Y] mỗi chi nhánh, trong hai mươi tư tháng.",
"We start the installation next month, and go-live in three weeks.": "Chúng tôi bắt đầu lắp đặt vào tháng sau, và chạy chính thức sau ba tuần.",
"Training for your staff is included — two sessions.": "Đã bao gồm đào tạo nhân viên — hai buổi.",
"May I confirm the exact items we finalized?": "Tôi xác nhận lại chính xác các hạng mục mình đã chốt được không?",
"Is this option right for what your store needs now?": "Phương án này có đúng với nhu cầu hiện tại của cửa hàng bạn không?",
"I will prepare the contract and send it for your final check before we sign.": "Tôi sẽ chuẩn bị hợp đồng và gửi bạn kiểm tra lần cuối trước khi mình ký.",
"T — Yes, I really enjoy it.": "T — Vâng, tôi rất thích công việc đó.",
"V — For example, last month I helped launch a new feature for our client.": "V — Ví dụ, tháng trước tôi giúp ra mắt một tính năng mới cho khách hàng của chúng tôi.",
}
