# -*- coding: utf-8 -*-
"""Ban dich 94 cau Tatoeba (giong nguoi that) da loc sach."""
VN = {
"This is a car.": "Đây là một chiếc ô tô.",
"The car is big.": "Chiếc xe thì to.",
"The house is old.": "Ngôi nhà thì cũ.",
"She can come today.": "Hôm nay cô ấy có thể đến.",
"He can see a house.": "Anh ấy thấy một ngôi nhà.",
"I am not a student.": "Tôi không phải là học sinh.",
"We took a bus here.": "Chúng tôi đã đi xe buýt tới đây.",
"Does she have money?": "Cô ấy có tiền không?",
"Can she speak English?": "Cô ấy nói được tiếng Anh không?",
"Yes, I went yesterday.": "Vâng, hôm qua tôi đã đi.",
"Stop it. Get some help.": "Dừng lại đi. Hãy tìm người giúp.",
"Many people say that it is a lie.": "Nhiều người nói đó là lời nói dối.",
"This is not a very good example.": "Đây không phải là một ví dụ hay.",
"He is not a good person.": "Anh ta không phải người tốt.",
"This man is not my husband.": "Người đàn ông này không phải chồng tôi.",
"You will definitely like it here.": "Chắc chắn bạn sẽ thích ở đây.",
"It's a big house.": "Đó là một ngôi nhà lớn.",
"Why do I have it?": "Tại sao tôi lại có nó?",
"I can see a flower.": "Tôi thấy một bông hoa.",
"I made a good deal.": "Tôi đã có một thương vụ hời.",
"I think he is sick.": "Tôi nghĩ anh ấy bị ốm.",
"She had a good idea.": "Cô ấy đã có một ý hay.",
"He is not your enemy.": "Anh ấy không phải kẻ thù của bạn.",
"Does she have a piano?": "Cô ấy có đàn piano không?",
"I do not speak Polish.": "Tôi không nói được tiếng Ba Lan.",
"I read a Spanish book.": "Tôi đọc một cuốn sách tiếng Tây Ban Nha.",
"My father is a tailor.": "Bố tôi là thợ may.",
"That is not my laptop.": "Đó không phải laptop của tôi.",
"It will be my pleasure.": "Đó là niềm hân hạnh của tôi.",
"They know where I work.": "Họ biết tôi làm việc ở đâu.",
"Do you like my language?": "Bạn có thích ngôn ngữ của tôi không?",
"I think, therefore I am.": "Tôi tư duy, vậy nên tôi tồn tại.",
"This must be your drink.": "Đây chắc là đồ uống của bạn.",
"Does he have any children?": "Anh ấy có con không?",
"Does she have a girlfriend?": "Cô ấy có bạn gái không?",
"There is no perfect family.": "Không có gia đình nào hoàn hảo cả.",
"You will eat your chocolate.": "Bạn sẽ ăn sô cô la của mình.",
"The small house is beautiful.": "Ngôi nhà nhỏ thật đẹp.",
"This is wonderful! Thank you.": "Tuyệt vời quá! Cảm ơn bạn.",
"My mother had thirteen children.": "Mẹ tôi có mười ba người con.",
"Do you think we'll make it in time?": "Bạn nghĩ mình có kịp giờ không?",
"I am a cat.": "Tôi là một con mèo.",
"I had a dog.": "Tôi đã từng có một con chó.",
"Is it a bird?": "Đó là một con chim phải không?",
"I do see them.": "Tôi có thấy họ mà.",
"That is a lie.": "Đó là lời nói dối.",
"He is with you.": "Anh ấy đang ở bên bạn.",
"I ate my lemon.": "Tôi đã ăn quả chanh của mình.",
"I like the sea.": "Tôi thích biển.",
"I have a tomcat.": "Tôi có một con mèo đực.",
"I need her here.": "Tôi cần cô ấy ở đây.",
"I only love you.": "Anh chỉ yêu mình em.",
"My name is Jack.": "Tôi tên là Jack.",
"That is a hotel.": "Đó là một khách sạn.",
"This is a tower.": "Đây là một tòa tháp.",
"Tom had a child.": "Tom đã có một đứa con.",
"Tom has a child.": "Tom có một đứa con.",
"We need a queen.": "Chúng ta cần một nữ hoàng.",
"We want a queen.": "Chúng ta muốn có một nữ hoàng.",
"You saw a raven.": "Bạn đã thấy một con quạ.",
"Does she know me?": "Cô ấy có biết tôi không?",
"Have a good trip!": "Chúc bạn một chuyến đi vui vẻ!",
"I like this film.": "Tôi thích bộ phim này.",
"We want a leader.": "Chúng tôi cần một người lãnh đạo.",
"You see a flower.": "Bạn thấy một bông hoa.",
"You wrote a book!": "Bạn đã viết một cuốn sách!",
"I am really sorry.": "Tôi thật sự xin lỗi.",
"I like that movie.": "Tôi thích bộ phim đó.",
"I love your purse.": "Tôi thích chiếc túi của bạn.",
"The tree is small.": "Cái cây thì nhỏ.",
"Do you know German?": "Bạn có biết tiếng Đức không?",
"Does she have rice?": "Cô ấy có cơm không?",
"My friend is Swiss.": "Bạn tôi là người Thụy Sĩ.",
"This is my partner.": "Đây là cộng sự của tôi.",
"You could swim now.": "Bây giờ bạn có thể bơi.",
"A woman was reading.": "Một người phụ nữ đang đọc sách.",
"Because you sell it.": "Bởi vì bạn bán nó.",
"Do you speak Polish?": "Bạn có nói tiếng Ba Lan không?",
"Have a good journey!": "Chúc bạn thượng lộ bình an!",
"He will be sleeping.": "Lúc đó anh ấy sẽ đang ngủ.",
"I love my boyfriend.": "Tôi yêu bạn trai của mình.",
"I love your country.": "Tôi yêu đất nước của bạn.",
"Is your name Edward?": "Bạn tên là Edward phải không?",
"Nobody would say it.": "Chẳng ai chịu nói ra điều đó.",
"The chapel is there.": "Nhà nguyện ở đằng kia.",
"The doctor is there.": "Bác sĩ ở đằng kia.",
"The toilet is there.": "Nhà vệ sinh ở đằng kia.",
"They missed the bus.": "Họ lỡ chuyến xe buýt.",
"I made some biscuits.": "Tôi đã làm ít bánh quy.",
"Is your name Eduardo?": "Bạn tên là Eduardo phải không?",
"The sentence is good.": "Câu này ổn đấy.",
"You saw us yesterday.": "Hôm qua bạn đã thấy chúng tôi.",
"My mother is sleeping.": "Mẹ tôi đang ngủ.",
"The woman was reading.": "Người phụ nữ đang đọc sách.",
}
